//! Bake the mod DLLs into the installer, so the thing a player downloads is one file.
//!
//! # The problem this solves
//!
//! A player finds a release page and downloads the installer. They do not clone the repo, and
//! they may well not unpack a folder either -- they run the executable. An installer that
//! looks for a `dlls` directory beside itself works perfectly on the machine that built it and
//! fails on every machine that matters.
//!
//! # How
//!
//! `ER_INSTALLER_EMBED_DIR` names a directory of built DLLs. When it is set, every artifact
//! the catalog lists is read out of it and `include_bytes!` into the binary, which is 33 MB of
//! payload and the reason this is opt-in: a development build sets nothing and compiles in
//! under a second, and the release build sets it once.
//!
//! # Missing is an error, never a smaller build
//!
//! A directory short one DLL would otherwise produce an installer that offers a mod and cannot
//! install it, and the player finds that out after choosing it. So this fails the build, by
//! name. The list of what must be there comes from `src/catalog.rs`, which
//! `scripts/gen-installer-catalog.py` generates and a check gates -- scanned for its `package`
//! and `artifact` fields rather than parsed, because a build script that needs a TOML parser
//! would defeat the point of the crate having no dependencies.
//!
//! # Stale is an error too, and it is the one that actually shipped
//!
//! `cargo:rerun-if-changed` below puts this build in lockstep with the DLL **files**, and that
//! link has never broken: touch a DLL and the installer relinks. The link it cannot make is the
//! one before it -- DLL file against the source it was built from -- and that is where a bad
//! installer comes from.
//!
//! Measured 2026-09-19. Commit `dcffc4af` changed `er-quit-menu-core`, which four cdylibs link.
//! Only `er-quit-load-character` was rebuilt, so `er_quit_menu.dll` in the embed directory kept
//! the bytes it had from the previous evening. Nothing was wrong with it as a file, so
//! `rerun-if-changed` correctly saw no change, this build correctly embedded it, and the player
//! installed a shell without the fix and reported the bug it had already been fixed for. Seven
//! more artifacts in that same directory were stale against the tree at that moment, including
//! one the player's own profile carried.
//!
//! `scripts/er-dll-provenance.py` already answers exactly this question -- it records a content
//! hash over each package's compiled dependency closure at build time, which is why it can tell
//! "built from this tree" from "written recently". Every launch script in the repo gates on it
//! and refuses to start a game on a stale DLL. This build gates on it for the same reason, with
//! a longer blast radius: a launch that should not have happened costs one run, and an installer
//! that should not have shipped costs everyone who downloads it.
//!
//! The release workflow builds every DLL immediately before this step, and so does
//! `scripts/check-rust-build.sh`, so both were already fresh and neither pays for this. What it
//! catches is a local build over a `target/` directory carrying whatever the last few sessions
//! happened to compile -- which is how the installer above was built.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const EMBED_DIR_VAR: &str = "ER_INSTALLER_EMBED_DIR";

fn main() {
    println!("cargo:rerun-if-env-changed={EMBED_DIR_VAR}");
    println!("cargo:rerun-if-changed=src/catalog.rs");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));
    let destination = out_dir.join("embedded.rs");

    let Some(embed_dir) = env::var_os(EMBED_DIR_VAR).map(PathBuf::from) else {
        fs::write(&destination, empty_table()).expect("writing the empty payload table");
        return;
    };

    let entries = entries_from_catalog();
    assert!(
        !entries.is_empty(),
        "src/catalog.rs listed no artifacts -- regenerate it with \
         scripts/gen-installer-catalog.py"
    );

    let missing: Vec<&str> = entries
        .iter()
        .filter(|entry| !embed_dir.join(&entry.artifact).is_file())
        .map(|entry| entry.artifact.as_str())
        .collect();
    assert!(
        missing.is_empty(),
        "{EMBED_DIR_VAR} is {} but these are not in it:\n{}\n\
         Build them first: scripts/er-build-dlls.sh --all",
        embed_dir.display(),
        missing
            .iter()
            .map(|artifact| format!("  {artifact}\n"))
            .collect::<String>()
    );

    refuse_stale_payload(&embed_dir, &entries);

    let mut table = String::from(
        "// Generated by build.rs from ER_INSTALLER_EMBED_DIR.\n\
         pub const EMBEDDED: &[(&str, &[u8])] = &[\n",
    );
    for entry in &entries {
        let path = embed_dir.join(&entry.artifact);
        println!("cargo:rerun-if-changed={}", path.display());
        // The record beside it, so re-recording provenance re-runs this build even when the
        // rebuild it describes produced identical bytes.
        println!(
            "cargo:rerun-if-changed={}",
            provenance_record(&path).display()
        );
        table.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            entry.artifact,
            path.display().to_string()
        ));
    }
    table.push_str("];\n");
    fs::write(&destination, table).expect("writing the payload table");
}

/// Fail the build unless every DLL about to be embedded was built from this working tree.
///
/// Delegates to `scripts/er-dll-provenance.py verify`, which is the tool the launch scripts
/// already gate on -- one source of truth for what "fresh" means, rather than a second opinion
/// living in a build script. One process per artifact, ~80 ms each, and only when the payload is
/// being embedded at all.
///
/// A verifier that cannot be run is itself a failure. The alternative is a build that quietly
/// skips the check on exactly the machine whose environment is unusual, which is the shape of
/// every gate anyone has ever been burned by.
fn refuse_stale_payload(embed_dir: &Path, entries: &[Entry]) {
    let script = repo_root().join("scripts/er-dll-provenance.py");
    println!("cargo:rerun-if-changed={}", script.display());

    let mut stale = String::new();
    for entry in entries {
        let artifact = embed_dir.join(&entry.artifact);
        let output = Command::new("python3")
            .arg(&script)
            .arg("verify")
            .arg("--package")
            .arg(&entry.package)
            .arg("--artifact")
            .arg(&artifact)
            .output()
            .unwrap_or_else(|error| {
                panic!(
                    "could not run {} to check the payload is fresh: {error}\n\
                     python3 has to be on PATH to build an installer that carries mods.",
                    script.display()
                )
            });
        if !output.status.success() {
            // A refusal message being quoted back to a human. The tool writes ASCII, and a byte
            // that somehow was not is still worth showing as a replacement character inside the
            // list of what to rebuild: dropping the message would turn a named stale DLL into an
            // unexplained build failure.
            // UTF-8 Lossy: displaying a subprocess's own diagnostic, never parsed.
            let said = String::from_utf8_lossy(&output.stdout);
            // UTF-8 Lossy: the other half of the same message.
            let also = String::from_utf8_lossy(&output.stderr);
            let detail = format!("{said}{also}");
            stale.push_str(&format!(
                "  {} ({})\n{}",
                entry.artifact,
                entry.package,
                detail
                    .lines()
                    .map(|line| format!("      {}\n", line.trim()))
                    .collect::<String>()
            ));
        }
    }
    assert!(
        stale.is_empty(),
        "refusing to embed a DLL that was not built from this tree. An installer carrying one \
         installs a mod whose source no longer exists, and the player it reaches has no way to \
         tell:\n\n{stale}\nRebuild the payload, then build this again:\n  \
         scripts/er-build-dlls.sh --all"
    );
}

/// `<artifact>.provenance.json`, beside the artifact, as `er-dll-provenance.py` writes it.
fn provenance_record(artifact: &Path) -> PathBuf {
    let mut name = artifact.file_name().unwrap_or_default().to_os_string();
    name.push(".provenance.json");
    artifact.with_file_name(name)
}

/// The repo root, two directories above this crate's manifest.
fn repo_root() -> PathBuf {
    let manifest =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(Path::parent)
        .map(PathBuf::from)
        .expect("the crate lives at <repo>/tools/er-installer")
}

fn empty_table() -> String {
    String::from(
        "// Generated by build.rs: ER_INSTALLER_EMBED_DIR was not set, so this build installs\n\
         // from a `dlls` directory beside the executable instead of from itself.\n\
         pub const EMBEDDED: &[(&str, &[u8])] = &[];\n",
    )
}

/// One catalog row, reduced to the two fields this build script needs.
struct Entry {
    /// Cargo package name, which is what the provenance tool keys on.
    package: String,
    /// File name in the embed directory.
    artifact: String,
}

/// Every `package`/`artifact` pair in the generated catalog, in the order it appears.
///
/// The generator emits `package` on the line above `artifact` in every row, so the two lists
/// pair up by position. That is asserted rather than assumed: a generator change that broke the
/// pairing would otherwise check each DLL against some other DLL's source and pass.
fn entries_from_catalog() -> Vec<Entry> {
    let catalog = Path::new("src/catalog.rs");
    let text = fs::read_to_string(catalog).expect("src/catalog.rs should be generated and present");
    let packages = field_values(&text, "package: \"");
    let artifacts = field_values(&text, "artifact: \"");
    assert_eq!(
        packages.len(),
        artifacts.len(),
        "src/catalog.rs has {} package fields against {} artifact fields, so they cannot be \
         paired -- regenerate it with scripts/gen-installer-catalog.py",
        packages.len(),
        artifacts.len()
    );
    packages
        .into_iter()
        .zip(artifacts)
        .map(|(package, artifact)| Entry { package, artifact })
        .collect()
}

/// Every string literal introduced by `prefix`, one per line, in source order.
fn field_values(text: &str, prefix: &str) -> Vec<String> {
    text.lines()
        .filter_map(|line| {
            let rest = line.trim().strip_prefix(prefix)?;
            let end = rest.find('"')?;
            Some(rest[..end].to_string())
        })
        .collect()
}
