//! Bake the mod DLLs into the installer, so the thing a player downloads is one file.
//!
//! # The problem this solves
//!
//! A player finds a release page and downloads the installer. They do not clone the repo, and
//! they may well not unpack a folder either -- they run the executable. An installer that
//! looks for a `dlls` directory beside itself works perfectly on the machine that built it and
//! fails on every machine that matters.
//!
//! # How
//!
//! `ER_INSTALLER_EMBED_DIR` names a directory of built DLLs. When it is set, every artifact
//! the catalog lists is read out of it and `include_bytes!` into the binary, which is 33 MB of
//! payload and the reason this is opt-in: a development build sets nothing and compiles in
//! under a second, and the release build sets it once.
//!
//! # Missing is an error, never a smaller build
//!
//! A directory short one DLL would otherwise produce an installer that offers a mod and cannot
//! install it, and the player finds that out after choosing it. So this fails the build, by
//! name. The list of what must be there comes from `src/catalog.rs`, which
//! `scripts/gen-installer-catalog.py` generates and a check gates -- scanned for its `artifact`
//! fields rather than parsed, because a build script that needs a TOML parser would defeat the
//! point of the crate having no dependencies.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const EMBED_DIR_VAR: &str = "ER_INSTALLER_EMBED_DIR";

fn main() {
    println!("cargo:rerun-if-env-changed={EMBED_DIR_VAR}");
    println!("cargo:rerun-if-changed=src/catalog.rs");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));
    let destination = out_dir.join("embedded.rs");

    let Some(embed_dir) = env::var_os(EMBED_DIR_VAR).map(PathBuf::from) else {
        fs::write(&destination, empty_table()).expect("writing the empty payload table");
        return;
    };

    let artifacts = artifacts_from_catalog();
    assert!(
        !artifacts.is_empty(),
        "src/catalog.rs listed no artifacts -- regenerate it with \
         scripts/gen-installer-catalog.py"
    );

    let missing: Vec<&String> = artifacts
        .iter()
        .filter(|artifact| !embed_dir.join(artifact).is_file())
        .collect();
    assert!(
        missing.is_empty(),
        "{EMBED_DIR_VAR} is {} but these are not in it:\n{}\n\
         Build them first: scripts/er-build-dlls.sh --all",
        embed_dir.display(),
        missing
            .iter()
            .map(|artifact| format!("  {artifact}\n"))
            .collect::<String>()
    );

    let mut table = String::from(
        "// Generated by build.rs from ER_INSTALLER_EMBED_DIR.\n\
         pub const EMBEDDED: &[(&str, &[u8])] = &[\n",
    );
    for artifact in &artifacts {
        let path = embed_dir.join(artifact);
        println!("cargo:rerun-if-changed={}", path.display());
        table.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            artifact,
            path.display().to_string()
        ));
    }
    table.push_str("];\n");
    fs::write(&destination, table).expect("writing the payload table");
}

fn empty_table() -> String {
    String::from(
        "// Generated by build.rs: ER_INSTALLER_EMBED_DIR was not set, so this build installs\n\
         // from a `dlls` directory beside the executable instead of from itself.\n\
         pub const EMBEDDED: &[(&str, &[u8])] = &[];\n",
    )
}

/// Every `artifact: "..."` in the generated catalog, in the order it appears.
fn artifacts_from_catalog() -> Vec<String> {
    let catalog = Path::new("src/catalog.rs");
    let text = fs::read_to_string(catalog).expect("src/catalog.rs should be generated and present");
    text.lines()
        .filter_map(|line| {
            let rest = line.trim().strip_prefix("artifact: \"")?;
            let end = rest.find('"')?;
            Some(rest[..end].to_string())
        })
        .collect()
}
