//! Generate the planner's slider layout table from the captured JSON.
//!
//! `data/planner-sliders-layout.json` is the planner's own `q9` table, a `JSON.parse` literal
//! lifted verbatim out of `assets/router-_AV0DRlF.js`. Two hundred rows transcribed by hand into
//! Rust would be two hundred chances to move an offset by one, and the failure would be silent:
//! every byte still decodes, into the wrong slider. So the JSON is the source and this writes the
//! table, which also means re-capturing a newer `q9` is a file copy rather than an edit.
//!
//! Only `key`, `offset`, `type` and `size` are read. The `name`, `options` and `hide` columns are
//! the planner's UI vocabulary -- the option tables that turn `hairModelId = 105` into "21" on a
//! dropdown -- and are kept in the JSON because they document what the numbers mean, not because
//! anything here compiles them.

use std::collections::BTreeMap;
use std::path::Path;

/// The layout covers exactly this many bytes, contiguously, and the generator refuses anything
/// else. It is `FaceDataBuffer.buffer[0..SLIDER_BYTES]`; see `src/sliders.rs` for the alignment.
const SLIDER_BYTES: usize = 264;

fn main() {
    let layout = Path::new("data/planner-sliders-layout.json");
    println!("cargo:rerun-if-changed={}", layout.display());
    println!("cargo:rerun-if-changed=build.rs");

    let text = std::fs::read_to_string(layout)
        .unwrap_or_else(|why| panic!("reading {}: {why}", layout.display()));
    let rows: Vec<BTreeMap<String, serde_json::Value>> = serde_json::from_str(&text)
        .unwrap_or_else(|why| panic!("parsing {}: {why}", layout.display()));

    let mut fields: Vec<(String, usize, &'static str, usize)> = Vec::with_capacity(rows.len());
    for row in &rows {
        let key = row
            .get("key")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| panic!("a layout row has no string `key`: {row:?}"));
        let offset = row
            .get("offset")
            .and_then(serde_json::Value::as_u64)
            .unwrap_or_else(|| panic!("layout row {key:?} has no numeric `offset`"))
            as usize;
        let size = row
            .get("size")
            .and_then(serde_json::Value::as_u64)
            .unwrap_or_else(|| panic!("layout row {key:?} has no numeric `size`"))
            as usize;
        let declared = row
            .get("type")
            .and_then(serde_json::Value::as_str)
            .unwrap_or_else(|| panic!("layout row {key:?} has no string `type`"));

        // `boolean` is not a separate encoding and is deliberately folded into `Byte` here rather
        // than modelled: the planner's own importer assigns the raw byte for `boolean` exactly as
        // it does for `number`, and its exporter pushes it back with `r || 0`. A Rust `bool` would
        // serialise as JSON `true`, which that exporter would then run through `toString(16)` and
        // emit as the four characters `true`. The distinction is a choice of UI widget, nothing
        // more, so it does not survive into the codec.
        let kind = match declared {
            "number" | "boolean" => "Byte",
            "colour" => "Colour",
            "list" => "List",
            other => panic!("layout row {key:?} declares unknown type {other:?}"),
        };
        let expected = match kind {
            "Byte" => 1,
            "Colour" => 3,
            _ => 4,
        };
        assert_eq!(
            size, expected,
            "layout row {key:?} is a {declared} of {size} bytes; that type is {expected}"
        );
        fields.push((key.to_owned(), offset, kind, size));
    }

    fields.sort_by_key(|(_, offset, ..)| *offset);
    let mut covered = 0usize;
    for (key, offset, _, size) in &fields {
        assert_eq!(
            *offset, covered,
            "layout row {key:?} starts at {offset} but the previous row ended at {covered}; the \
             table must tile the range with no gap and no overlap"
        );
        covered += size;
    }
    assert_eq!(
        covered, SLIDER_BYTES,
        "the layout covers {covered} bytes, not {SLIDER_BYTES}"
    );

    let mut out = String::new();
    out.push_str("// Generated by build.rs from data/planner-sliders-layout.json. Do not edit.\n");
    out.push_str("pub(crate) static LAYOUT: [SliderField; ");
    out.push_str(&fields.len().to_string());
    out.push_str("] = [\n");
    for (key, offset, kind, _) in &fields {
        out.push_str(&format!(
            "    SliderField {{ key: {key:?}, offset: {offset}, kind: FieldKind::{kind} }},\n"
        ));
    }
    out.push_str("];\n");

    let dir = std::env::var("OUT_DIR").expect("cargo sets OUT_DIR");
    std::fs::write(Path::new(&dir).join("sliders_layout.rs"), out).expect("writing the table");
}
