use std::{env, fmt::Write as _, fs, path::PathBuf};

use iced_x86::code_asm::*;

const SESSION_MANAGER_PLAYER_ENTRY_BASE_COPY_VA: u64 = 0x1423f1bf0;

macro_rules! session_manager_player_entry_base_copy_prologue {
    ($asm:ident) => {{
        $asm.mov(qword_ptr(rsp + 0x08), rbx)?;
        $asm.mov(qword_ptr(rsp + 0x10), rbp)?;
        $asm.mov(qword_ptr(rsp + 0x18), rsi)?;
        Ok::<(), iced_x86::IcedError>(())
    }};
}

fn assemble_session_manager_player_entry_base_copy_prologue() -> Result<Vec<u8>, iced_x86::IcedError>
{
    let mut asm = CodeAssembler::new(64)?;
    session_manager_player_entry_base_copy_prologue!(asm)?;
    asm.assemble(SESSION_MANAGER_PLAYER_ENTRY_BASE_COPY_VA)
}

fn generated_prologue_const(name: &str, bytes: &[u8]) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "// Generated by crates/er-player-name-filter-dll/build.rs from named iced-x86 CodeAssembler instructions."
    )
    .expect("write to String");
    writeln!(out, "const {name}: [u8; {}] = [", bytes.len()).expect("write to String");
    for chunk in bytes.chunks(12) {
        out.push_str("    ");
        for (index, byte) in chunk.iter().enumerate() {
            if index != 0 {
                out.push_str(", ");
            }
            write!(out, "0x{byte:02x}").expect("write to String");
        }
        out.push_str(",\n");
    }
    out.push_str("];\n");
    out
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=build.rs");
    let bytes = assemble_session_manager_player_entry_base_copy_prologue()?;
    let generated =
        generated_prologue_const("SESSION_MANAGER_PLAYER_ENTRY_BASE_COPY_PROLOGUE", &bytes);
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo sets OUT_DIR for build.rs"));
    fs::write(out_dir.join("generated_prologues.rs"), generated)?;
    Ok(())
}
