use std::{env, fmt::Write as _, fs, path::PathBuf};

use iced_x86::code_asm::*;

const SESSION_MANAGER_PLAYER_ENTRY_BASE_COPY_VA: u64 = 0x1423f1bf0;
const GET_PLAYER_CHR_NAME_VA: u64 = 0x14075f800;
const PLAYER_GAME_DATA_COPY_CHR_NAME_VA: u64 = 0x1402610c0;
/// The bytes `scripts/disas-deobf.sh 0x1402610c0` prints for `CS::PlayerGameData::CopyChrName`.
const PLAYER_GAME_DATA_COPY_CHR_NAME_PROLOGUE_BYTES: [u8; 10] =
    [0x48, 0x89, 0x5c, 0x24, 0x08, 0x57, 0x48, 0x83, 0xec, 0x20];

/// The bytes `scripts/disas-deobf.sh 0x14075f800` prints for the entry of
/// `CS::GetPlayerChrName` in the 1.16.2 image. The assembler below must reproduce these
/// exactly -- `mov rax, rsp` has two encodings (`48 8b c4` and `48 89 e0`) and only the
/// first is what the game ships, so a silent encoding choice would build a prologue that
/// never matches and a hook that always disarms itself.
const GET_PLAYER_CHR_NAME_PROLOGUE_BYTES: [u8; 7] = [0x48, 0x8b, 0xc4, 0x55, 0x57, 0x41, 0x56];

macro_rules! session_manager_player_entry_base_copy_prologue {
    ($asm:ident) => {{
        $asm.mov(qword_ptr(rsp + 0x08), rbx)?;
        $asm.mov(qword_ptr(rsp + 0x10), rbp)?;
        $asm.mov(qword_ptr(rsp + 0x18), rsi)?;
        Ok::<(), iced_x86::IcedError>(())
    }};
}

fn assemble_session_manager_player_entry_base_copy_prologue() -> Result<Vec<u8>, iced_x86::IcedError>
{
    let mut asm = CodeAssembler::new(64)?;
    session_manager_player_entry_base_copy_prologue!(asm)?;
    asm.assemble(SESSION_MANAGER_PLAYER_ENTRY_BASE_COPY_VA)
}

macro_rules! get_player_chr_name_prologue {
    ($asm:ident) => {{
        // `mov rax, rsp`, in the game's encoding. iced picks the other legal encoding for
        // `$asm.mov(rax, rsp)` -- 48 89 e0 rather than the 48 8b c4 the game ships -- and a
        // prologue that differs by one byte is a hook that disarms itself on every launch.
        $asm.db(&[0x48, 0x8b, 0xc4])?;
        $asm.push(rbp)?;
        $asm.push(rdi)?;
        $asm.push(r14)?;
        Ok::<(), iced_x86::IcedError>(())
    }};
}

fn assemble_get_player_chr_name_prologue() -> Result<Vec<u8>, iced_x86::IcedError> {
    let mut asm = CodeAssembler::new(64)?;
    get_player_chr_name_prologue!(asm)?;
    asm.assemble(GET_PLAYER_CHR_NAME_VA)
}

macro_rules! player_game_data_copy_chr_name_prologue {
    ($asm:ident) => {{
        $asm.mov(qword_ptr(rsp + 0x08), rbx)?;
        $asm.push(rdi)?;
        $asm.sub(rsp, 0x20)?;
        Ok::<(), iced_x86::IcedError>(())
    }};
}

fn assemble_player_game_data_copy_chr_name_prologue() -> Result<Vec<u8>, iced_x86::IcedError> {
    let mut asm = CodeAssembler::new(64)?;
    player_game_data_copy_chr_name_prologue!(asm)?;
    asm.assemble(PLAYER_GAME_DATA_COPY_CHR_NAME_VA)
}

fn generated_prologue_const(name: &str, bytes: &[u8]) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "// Generated by crates/er-player-name-filter-dll/build.rs from named iced-x86 CodeAssembler instructions."
    )
    .expect("write to String");
    writeln!(out, "const {name}: [u8; {}] = [", bytes.len()).expect("write to String");
    for chunk in bytes.chunks(12) {
        out.push_str("    ");
        for (index, byte) in chunk.iter().enumerate() {
            if index != 0 {
                out.push_str(", ");
            }
            write!(out, "0x{byte:02x}").expect("write to String");
        }
        out.push_str(",\n");
    }
    out.push_str("];\n");
    out
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=build.rs");
    let bytes = assemble_session_manager_player_entry_base_copy_prologue()?;
    let generated =
        generated_prologue_const("SESSION_MANAGER_PLAYER_ENTRY_BASE_COPY_PROLOGUE", &bytes);
    let chr_name_bytes = assemble_get_player_chr_name_prologue()?;
    assert_eq!(
        chr_name_bytes.as_slice(),
        GET_PLAYER_CHR_NAME_PROLOGUE_BYTES.as_slice(),
        "iced assembled a different encoding than the one the game ships at 0x{GET_PLAYER_CHR_NAME_VA:x}"
    );
    let generated = format!(
        "{generated}{}",
        generated_prologue_const("GET_PLAYER_CHR_NAME_PROLOGUE", &chr_name_bytes)
    );
    let copy_chr_name_bytes = assemble_player_game_data_copy_chr_name_prologue()?;
    assert_eq!(
        copy_chr_name_bytes.as_slice(),
        PLAYER_GAME_DATA_COPY_CHR_NAME_PROLOGUE_BYTES.as_slice(),
        "iced assembled a different encoding than the one the game ships at 0x{PLAYER_GAME_DATA_COPY_CHR_NAME_VA:x}"
    );
    let generated = format!(
        "{generated}{}",
        generated_prologue_const(
            "PLAYER_GAME_DATA_COPY_CHR_NAME_PROLOGUE",
            &copy_chr_name_bytes
        )
    );
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo sets OUT_DIR for build.rs"));
    fs::write(out_dir.join("generated_prologues.rs"), generated)?;
    Ok(())
}
