[package]
name = "er-build-watermark-dll"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "er_build_watermark_dll"
crate-type = ["cdylib"]

[target.'cfg(windows)'.dependencies]
er-build-watermark = { path = "../er-build-watermark" }
er-game-base = { path = "../er-game-base" }

[lints]
workspace = true
