//! Minimal, panic-safe DXBC/DXContainer reflection: the chunk table, the input
//! signature (`ISG1`/`ISGN`), and the resource-definition chunk (`RDEF`).
//!
//! `dxil-spirv` strips HLSL resource names and all signature/cbuffer-layout info from
//! its SPIR-V output, but the original DX container still carries them. This module
//! reads them straight from the container bytes (before translation) so the object
//! renderer can:
//!  * bind FLVER vertex buffers to the native `.vpo` by matching the `ISG1` input
//!    signature (SemanticName + SemanticIndex → input register), and
//!  * place a synthesized WorldViewProj at the right cbuffer byte-offset (when `RDEF`
//!    is present — Elden Ring's shipped DXIL shaders often omit it, so callers must
//!    tolerate `None`).
//!
//! Every read is bounds-checked; malformed/short input yields `None`, never a panic
//! (matching the rest of the host tooling's fail-closed hygiene). Layout validated
//! against a real Elden Ring `.vpo`/`.ppo` (`C[AMSN]_Fwd.vpo`: 6 ISG1 elements, 32-byte
//! stride, POSITION at register 0).

/// Checked little-endian u32 read.
fn u32_at(b: &[u8], off: usize) -> Option<u32> {
    b.get(off..off + 4)
        .map(|s| u32::from_le_bytes([s[0], s[1], s[2], s[3]]))
}

/// Checked little-endian u16 read.
fn u16_at(b: &[u8], off: usize) -> Option<u16> {
    b.get(off..off + 2)
        .map(|s| u16::from_le_bytes([s[0], s[1]]))
}

/// NUL-terminated ASCII string at `off` (bounded by the buffer).
fn cstr_at(b: &[u8], off: usize) -> String {
    let end = b[off.min(b.len())..]
        .iter()
        .position(|&c| c == 0)
        .map_or(b.len(), |p| off + p);
    // DX container semantic/resource names are spec'd ASCII; malformed bytes are diagnostic hints.
    // UTF-8 Lossy: a malformed byte must not panic reflection.
    String::from_utf8_lossy(&b[off.min(b.len())..end]).into_owned()
}

/// One chunk of a DX container. `data_off` points past the 8-byte FourCC+size header.
#[derive(Debug, Clone, Copy)]
pub struct DxbcPart {
    pub fourcc: [u8; 4],
    pub data_off: usize,
    pub size: usize,
}

/// Walk the DX container chunk table. Returns empty if `bytes` is not a `DXBC` blob.
pub fn parts(bytes: &[u8]) -> Vec<DxbcPart> {
    let mut out = Vec::new();
    if bytes.len() < 32 || &bytes[0..4] != b"DXBC" {
        return out;
    }
    let Some(count) = u32_at(bytes, 28) else {
        return out;
    };
    for k in 0..count as usize {
        let Some(off) = u32_at(bytes, 32 + k * 4).map(|v| v as usize) else {
            continue;
        };
        let (Some(size), true) = (u32_at(bytes, off + 4), off + 8 <= bytes.len()) else {
            continue;
        };
        let mut fourcc = [0u8; 4];
        fourcc.copy_from_slice(&bytes[off..off + 4]);
        out.push(DxbcPart {
            fourcc,
            data_off: off + 8,
            size: size as usize,
        });
    }
    out
}

/// Find the first chunk with `fourcc`.
pub fn find_part(bytes: &[u8], fourcc: &[u8; 4]) -> Option<DxbcPart> {
    parts(bytes).into_iter().find(|p| &p.fourcc == fourcc)
}

// --- input signature (ISG1 / ISGN) ------------------------------------------

/// One element of a vertex input signature.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SignatureInput {
    /// D3D SemanticName, e.g. `POSITION`, `NORMAL`, `TEXCOORD`, `BLENDINDICES`.
    pub semantic_name: String,
    /// The `N` in `TEXCOORD0`/`TEXCOORD1`.
    pub semantic_index: u32,
    /// The `vN` input register the vertex shader reads this attribute from.
    pub register: u32,
    /// D3D_NAME system-value type; `0` (UNDEFINED) means a per-vertex, FLVER-bound
    /// input. Non-zero (e.g. `SV_InstanceID`) is generated by the IA, not from a buffer.
    pub system_value: u32,
    /// Component mask (low nibble: bit0=X … bit3=W).
    pub mask: u8,
}

impl SignatureInput {
    /// A per-vertex input bound from a vertex buffer (vs. a system value).
    pub fn is_per_vertex(&self) -> bool {
        self.system_value == 0 && !self.semantic_name.is_empty()
    }
}

/// Parse the input signature of a DX container. Prefers `ISG1` (DXIL/SM6, 32-byte
/// element) and falls back to classic `ISGN` (24-byte). Returns every element
/// (including system values) so the caller decides what to bind; `None` if neither
/// chunk is present or the data is malformed.
pub fn parse_input_signature(container: &[u8]) -> Option<Vec<SignatureInput>> {
    // (part, element stride, field offsets within an element):
    // ISG1 adds a leading u32 Stream, shifting fields +4 vs ISGN.
    let (part, stride, name_o, idx_o, sysval_o, reg_o, mask_o) =
        if let Some(p) = find_part(container, b"ISG1") {
            (p, 32usize, 4, 8, 12, 20, 24)
        } else {
            let p = find_part(container, b"ISGN")?;
            (p, 24usize, 0, 4, 8, 16, 20)
        };
    let d = part.data_off;
    let count = u32_at(container, d)? as usize;
    let table = u32_at(container, d + 4)? as usize;
    let e0 = d + table;

    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let e = e0 + i * stride;
        let name_off = u32_at(container, e + name_o)? as usize;
        out.push(SignatureInput {
            semantic_name: if name_off == 0 {
                String::new()
            } else {
                cstr_at(container, d + name_off)
            },
            semantic_index: u32_at(container, e + idx_o)?,
            register: u32_at(container, e + reg_o)?,
            system_value: u32_at(container, e + sysval_o)?,
            mask: container.get(e + mask_o).copied().unwrap_or(0),
        });
    }
    Some(out)
}

// --- resource definitions (RDEF) --------------------------------------------

/// D3D_SHADER_INPUT_TYPE (resource-binding kind).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RdefBindKind {
    Cbuffer,
    Tbuffer,
    Texture,
    Sampler,
    Uav,
    Structured,
    ByteAddress,
    Other(u32),
}

impl RdefBindKind {
    fn from_u32(v: u32) -> Self {
        match v {
            0 => Self::Cbuffer,
            1 => Self::Tbuffer,
            2 => Self::Texture,
            3 => Self::Sampler,
            4 => Self::Uav,
            5 => Self::Structured,
            6 => Self::Uav, // RWStructured
            7 => Self::ByteAddress,
            8 => Self::Uav, // RWByteAddress
            other => Self::Other(other),
        }
    }
}

/// One bound resource (a `t#`/`s#`/`b#`/`u#` register).
#[derive(Debug, Clone)]
pub struct RdefResource {
    pub name: String,
    pub kind: RdefBindKind,
    /// BindPoint — the register number within its class.
    pub register: u32,
    /// RegisterSpace (0 below SM5.1).
    pub space: u32,
    pub bind_count: u32,
}

/// One variable within a constant buffer.
#[derive(Debug, Clone)]
pub struct RdefVariable {
    pub name: String,
    /// Byte offset of this variable WITHIN its cbuffer — the write location.
    pub start_offset: u32,
    pub size: u32,
    /// A 4×4 float matrix (the shape of a WorldViewProj).
    pub is_float4x4: bool,
    /// HLSL column-major storage (store the transpose). False = row-major.
    pub column_major: bool,
}

/// One constant buffer's variable layout.
#[derive(Debug, Clone)]
pub struct RdefCBuffer {
    pub name: String,
    pub size: u32,
    pub variables: Vec<RdefVariable>,
}

/// Parsed `RDEF` resource definitions.
#[derive(Debug, Clone)]
pub struct Rdef {
    pub target_version: u16,
    pub resources: Vec<RdefResource>,
    pub cbuffers: Vec<RdefCBuffer>,
}

impl Rdef {
    /// The `(register, space)` of a cbuffer by name, from the resource-binding table
    /// (the cbuffer table itself does not carry its own bind slot).
    pub fn cbuffer_slot(&self, name: &str) -> Option<(u32, u32)> {
        self.resources
            .iter()
            .find(|r| r.kind == RdefBindKind::Cbuffer && r.name == name)
            .map(|r| (r.register, r.space))
    }
}

/// Parse the `RDEF` chunk, if present. Returns `None` when absent (common for Elden
/// Ring's shipped DXIL shaders) or malformed.
pub fn parse_rdef(container: &[u8]) -> Option<Rdef> {
    let part = find_part(container, b"RDEF")?;
    let d = part.data_off;

    let cb_count = u32_at(container, d)? as usize;
    let cb_off = u32_at(container, d + 4)? as usize;
    let res_count = u32_at(container, d + 8)? as usize;
    let res_off = u32_at(container, d + 12)? as usize;
    let target_version = u16_at(container, d + 16)?;

    // Resource-binding table: stride 40 for SM5.1+ (carries Space), else 32.
    let res_stride = if target_version >= 0x0501 { 40 } else { 32 };
    let mut resources = Vec::with_capacity(res_count);
    for i in 0..res_count {
        let r = d + res_off + i * res_stride;
        let name_off = u32_at(container, r)? as usize;
        resources.push(RdefResource {
            name: cstr_at(container, d + name_off),
            kind: RdefBindKind::from_u32(u32_at(container, r + 4)?),
            register: u32_at(container, r + 20)?,
            bind_count: u32_at(container, r + 24)?,
            space: if res_stride == 40 {
                u32_at(container, r + 32)?
            } else {
                0
            },
        });
    }

    // Cbuffer table (stride 24) → variable table (stride 40 for SM5+, else 24).
    let var_stride = if target_version >= 0x0500 { 40 } else { 24 };
    let mut cbuffers = Vec::with_capacity(cb_count);
    for i in 0..cb_count {
        let c = d + cb_off + i * 24;
        let name_off = u32_at(container, c)? as usize;
        let var_count = u32_at(container, c + 4)? as usize;
        let var_off = u32_at(container, c + 8)? as usize;
        let size = u32_at(container, c + 12)?;

        let mut variables = Vec::with_capacity(var_count);
        for j in 0..var_count {
            let v = d + var_off + j * var_stride;
            let vname_off = u32_at(container, v)? as usize;
            let start_offset = u32_at(container, v + 4)?;
            let vsize = u32_at(container, v + 8)?;
            let type_off = u32_at(container, v + 16)? as usize;
            // Type record: Class(u16) Type(u16) Rows(u16) Columns(u16) Elements(u16).
            let t = d + type_off;
            let class = u16_at(container, t).unwrap_or(0);
            let ty = u16_at(container, t + 2).unwrap_or(0);
            let rows = u16_at(container, t + 4).unwrap_or(0);
            let cols = u16_at(container, t + 6).unwrap_or(0);
            let elements = u16_at(container, t + 8).unwrap_or(0);
            // Class 2 = MATRIX_ROWS, 3 = MATRIX_COLUMNS; Type 3 = FLOAT.
            let is_float4x4 =
                (class == 2 || class == 3) && ty == 3 && rows == 4 && cols == 4 && elements == 0;
            variables.push(RdefVariable {
                name: cstr_at(container, d + vname_off),
                start_offset,
                size: vsize,
                is_float4x4,
                column_major: class == 3,
            });
        }
        cbuffers.push(RdefCBuffer {
            name: cstr_at(container, d + name_off),
            size,
            variables,
        });
    }

    Some(Rdef {
        target_version,
        resources,
        cbuffers,
    })
}

/// The WorldViewProj-like matrix: its cbuffer, the variable's byte offset, and whether
/// to store the transpose. Prefers a name containing `worldviewproj`/`wvp`/`viewproj`,
/// else the first `float4x4` of size 64. Returns `(cbuffer_name, start_offset, column_major)`.
pub fn find_world_view_proj(rdef: &Rdef) -> Option<(String, u32, bool)> {
    let pick = |pred: &dyn Fn(&RdefVariable) -> bool| {
        rdef.cbuffers.iter().find_map(|cb| {
            cb.variables
                .iter()
                .find(|v| pred(v))
                .map(|v| (cb.name.clone(), v.start_offset, v.column_major))
        })
    };
    let named = |v: &RdefVariable| {
        let n = v.name.to_lowercase();
        v.is_float4x4
            && (n.contains("worldviewproj") || n.contains("wvp") || n.contains("viewproj"))
    };
    pick(&named).or_else(|| pick(&|v: &RdefVariable| v.is_float4x4 && v.size == 64))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Assemble a valid `DXBC` container around the given chunks.
    fn fake_container(chunks: &[(&[u8; 4], Vec<u8>)]) -> Vec<u8> {
        let header = 32 + chunks.len() * 4; // magic+digest+ver+size+count + offset table
        let mut offsets = Vec::new();
        let mut body = Vec::new();
        for (cc, data) in chunks {
            offsets.push((header + body.len()) as u32);
            body.extend_from_slice(*cc);
            body.extend_from_slice(&(data.len() as u32).to_le_bytes());
            body.extend_from_slice(data);
        }
        let mut out = Vec::new();
        out.extend_from_slice(b"DXBC");
        out.extend_from_slice(&[0u8; 16]); // digest
        out.extend_from_slice(&1u32.to_le_bytes()); // version
        out.extend_from_slice(&0u32.to_le_bytes()); // total size (unused by our reader)
        out.extend_from_slice(&(chunks.len() as u32).to_le_bytes());
        for o in offsets {
            out.extend_from_slice(&o.to_le_bytes());
        }
        out.extend_from_slice(&body);
        out
    }

    /// Build a signature chunk body (ISG1=32B stride, ISGN=24B) with the given elements
    /// `(name, semantic_index, register, system_value, mask)` plus a trailing string table.
    fn sig_body(isg1: bool, elems: &[(&str, u32, u32, u32, u8)]) -> Vec<u8> {
        let stride = if isg1 { 32 } else { 24 };
        let header = 8;
        let table_len = elems.len() * stride;
        // String table starts right after the elements; offsets are from data start.
        let mut strtab = Vec::new();
        let mut name_offsets = Vec::new();
        for (name, ..) in elems {
            name_offsets.push(header + table_len + strtab.len());
            strtab.extend_from_slice(name.as_bytes());
            strtab.push(0);
        }
        let mut body = Vec::new();
        body.extend_from_slice(&(elems.len() as u32).to_le_bytes()); // ParamCount
        body.extend_from_slice(&8u32.to_le_bytes()); // ParamOffset
        for (i, &(_, idx, reg, sysval, mask)) in elems.iter().enumerate() {
            let mut e = vec![0u8; stride];
            let put = |e: &mut [u8], off: usize, v: u32| {
                e[off..off + 4].copy_from_slice(&v.to_le_bytes());
            };
            if isg1 {
                put(&mut e, 0, 0); // Stream
                put(&mut e, 4, name_offsets[i] as u32);
                put(&mut e, 8, idx);
                put(&mut e, 12, sysval);
                put(&mut e, 16, 3); // ComponentType=float
                put(&mut e, 20, reg);
                e[24] = mask;
            } else {
                put(&mut e, 0, name_offsets[i] as u32);
                put(&mut e, 4, idx);
                put(&mut e, 8, sysval);
                put(&mut e, 12, 3);
                put(&mut e, 16, reg);
                e[20] = mask;
            }
            body.extend_from_slice(&e);
        }
        body.extend_from_slice(&strtab);
        body
    }

    #[test]
    fn parse_isg1_elements() {
        let body = sig_body(
            true,
            &[
                ("POSITION", 0, 0, 0, 0x07),
                ("TEXCOORD", 1, 3, 0, 0x0f),
                ("SV_InstanceID", 0, 5, 8, 0x01),
            ],
        );
        let c = fake_container(&[(b"ISG1", body)]);
        let sig = parse_input_signature(&c).expect("parse");
        assert_eq!(sig.len(), 3);
        assert_eq!(sig[0].semantic_name, "POSITION");
        assert_eq!(sig[0].register, 0);
        assert!(sig[0].is_per_vertex());
        assert_eq!(sig[1].semantic_name, "TEXCOORD");
        assert_eq!(sig[1].semantic_index, 1);
        assert_eq!(sig[1].register, 3);
        // The system value is parsed but flagged non-per-vertex.
        assert_eq!(sig[2].system_value, 8);
        assert!(!sig[2].is_per_vertex());
    }

    #[test]
    fn parse_isgn_fallback_same_logical_signature() {
        let body = sig_body(
            false,
            &[("POSITION", 0, 0, 0, 0x07), ("NORMAL", 0, 1, 0, 0x07)],
        );
        let c = fake_container(&[(b"ISGN", body)]);
        let sig = parse_input_signature(&c).expect("parse");
        assert_eq!(sig.len(), 2);
        assert_eq!(sig[0].semantic_name, "POSITION");
        assert_eq!(sig[0].register, 0);
        assert_eq!(sig[1].semantic_name, "NORMAL");
        assert_eq!(sig[1].register, 1);
    }

    #[test]
    fn garbage_and_missing_chunks_return_none() {
        assert!(parse_input_signature(&[0u8; 8]).is_none());
        assert!(parse_input_signature(b"not a dxbc container at all").is_none());
        // Valid DXBC but no signature chunk.
        let c = fake_container(&[(b"STAT", vec![0u8; 16])]);
        assert!(parse_input_signature(&c).is_none());
        assert!(parse_rdef(&c).is_none());
    }

    /// Build an RDEF body: one cbuffer with a WorldViewProj float4x4 at offset 0, plus
    /// a CBUFFER resource row and a TEXTURE row at register 7.
    #[test]
    fn parse_rdef_cbuffer_and_resource() {
        // Layout (all offsets from RDEF data start d):
        //   d+0  header (28 bytes through creator offset)
        //   d+28 cbuffer table (1 * 24)
        //   d+52 variable table (1 * 40)
        //   d+92 type record (float4x4)
        //   d+108 resource table (2 * 40)
        //   then string table
        let mut b = vec![0u8; 28];
        let put = |b: &mut Vec<u8>, off: usize, v: u32| {
            b[off..off + 4].copy_from_slice(&v.to_le_bytes());
        };
        let cb_off = 28usize;
        let var_off = 52usize;
        let type_off = 92usize;
        let res_off = 108usize;
        let strtab_off = res_off + 2 * 40;

        // strings
        let mut strtab = Vec::new();
        let s = |strtab: &mut Vec<u8>, base: usize, name: &str| -> u32 {
            let o = base + strtab.len();
            strtab.extend_from_slice(name.as_bytes());
            strtab.push(0);
            o as u32
        };
        let cb_name = s(&mut strtab, strtab_off, "cbInstanceData");
        let var_name = s(&mut strtab, strtab_off, "WorldViewProj");
        let tex_name = s(&mut strtab, strtab_off, "C_X__snp_Texture2D_7_AlbedoMap");

        // header
        put(&mut b, 0, 1); // ConstantBufferCount
        put(&mut b, 4, cb_off as u32); // ConstantBufferOffset
        put(&mut b, 8, 2); // BoundResourceCount
        put(&mut b, 12, res_off as u32); // BoundResourceOffset
        b[16..18].copy_from_slice(&0x0501u16.to_le_bytes()); // target version (SM5.1)

        // grow to strtab end and write the string table in
        b.resize(strtab_off + strtab.len(), 0);
        b[strtab_off..strtab_off + strtab.len()].copy_from_slice(&strtab);

        // cbuffer table entry
        put(&mut b, cb_off, cb_name);
        put(&mut b, cb_off + 4, 1); // VariableCount
        put(&mut b, cb_off + 8, var_off as u32);
        put(&mut b, cb_off + 12, 64); // Size

        // variable entry
        put(&mut b, var_off, var_name);
        put(&mut b, var_off + 4, 0); // StartOffset
        put(&mut b, var_off + 8, 64); // Size
        put(&mut b, var_off + 16, type_off as u32);
        // type record: Class=3 (columns), Type=3 (float), Rows=4, Cols=4, Elements=0
        b[type_off..type_off + 2].copy_from_slice(&3u16.to_le_bytes());
        b[type_off + 2..type_off + 4].copy_from_slice(&3u16.to_le_bytes());
        b[type_off + 4..type_off + 6].copy_from_slice(&4u16.to_le_bytes());
        b[type_off + 6..type_off + 8].copy_from_slice(&4u16.to_le_bytes());
        b[type_off + 8..type_off + 10].copy_from_slice(&0u16.to_le_bytes());

        // resource table: [0]=CBUFFER cbInstanceData b0, [1]=TEXTURE ...AlbedoMap t7
        put(&mut b, res_off, cb_name);
        put(&mut b, res_off + 4, 0); // Type=CBUFFER
        put(&mut b, res_off + 20, 0); // BindPoint
        put(&mut b, res_off + 24, 1); // BindCount
        put(&mut b, res_off + 32, 0); // Space
        put(&mut b, res_off + 40, tex_name);
        put(&mut b, res_off + 44, 2); // Type=TEXTURE
        put(&mut b, res_off + 60, 7); // BindPoint
        put(&mut b, res_off + 64, 1); // BindCount
        put(&mut b, res_off + 72, 0); // Space

        let c = fake_container(&[(b"RDEF", b)]);
        let rdef = parse_rdef(&c).expect("rdef");
        assert_eq!(rdef.cbuffers.len(), 1);
        assert_eq!(rdef.cbuffers[0].name, "cbInstanceData");
        assert_eq!(rdef.cbuffers[0].variables[0].name, "WorldViewProj");
        assert!(rdef.cbuffers[0].variables[0].is_float4x4);

        let tex = rdef
            .resources
            .iter()
            .find(|r| r.kind == RdefBindKind::Texture)
            .unwrap();
        assert_eq!(tex.register, 7);
        assert!(tex.name.contains("AlbedoMap"));
        assert_eq!(rdef.cbuffer_slot("cbInstanceData"), Some((0, 0)));

        let (cb, off, colmajor) = find_world_view_proj(&rdef).unwrap();
        assert_eq!(cb, "cbInstanceData");
        assert_eq!(off, 0);
        assert!(colmajor);
    }
}
