//! er-game-base: shared low-level foundation below the product DLL, the
//! telemetry crate/DLL, and the zero-dep mini-DLLs.
//!
//! Tier A (default, zero external deps): FNV-1a fingerprints, fault-safe RAM readers,
//! game base/rva resolution, the stable singleton RVA/offset table, and a parameterized
//! append-only file logger.
//!
//! Tier B (`game-types` feature, cfg(windows)-gated): a re-export facade over
//! the typed eldenring / fromsoftware-shared accessors so the heavy consumers
//! share one import surface. The mini-DLLs enable tier A only.

pub mod build_id;
/// Tier A: bounded, fault-safe walks over `FD4FileCap`, `DLString<wchar_t>` and the DLIO
/// virtual-root table. Two images read those layouts now -- the product through
/// `er-title-flow`, and the `er-diag-harness` shell that carries the msb-parse / DLC-root /
/// loadlist-wait traces -- and one address must have exactly one declaration, so the walkers
/// live below both rather than being copied into the second one.
pub mod filecap;
pub mod fnv1a;
/// Tier A: which ELDEN RING this DLL is loaded into, read from the running image's own
/// version resource. Every game address here is a 1.16.2 RVA, and 1.17 moved code, so the
/// question "is this the build these addresses came from" has to be answerable BEFORE a
/// detour goes in -- see the module docs for the crash that motivated it.
pub mod game_build;
/// Tier A: does this process have a real, sized, top-level window yet? An overlay that installs
/// its Present hook before the answer is yes can be handed a dead HWND and abort -- see the
/// module for the two runs that died that way and the third that did not.
pub mod game_window;
/// Tier A: one blocking HTTPS GET over WinHTTP. Lives here rather than in the importer that
/// first needed it because a second caller appeared -- the build watermark's release lookup --
/// and a hand-declared WinHTTP ABI is exactly the kind of thing this crate exists to hold once.
#[cfg(windows)]
pub mod http;
pub mod log;
pub mod mem;
/// Tier A: turn a Rust panic in a mod DLL from an anonymous `0xe06d7363` record into a logged
/// line naming the message and the source location. See the module docs for the boot it cost.
pub mod panic_report;
#[cfg(all(windows, feature = "game-types"))]
pub mod pgd;
pub mod profile_summary;
/// Tier A: the masked prologue comparison every byte-checked detour gate runs. Lives here
/// because two crates check prologues generated by the same build support and one rule must
/// have one implementation -- see the module docs for the three 1.17 gates that disarmed on a
/// relocated operand.
pub mod prologue;
pub mod reentry;
pub mod rva;
/// Tier A: bounded, wineserver-friendly polling for a game singleton. The unbounded
/// `loop { yield_now() }` every shell used instead deadlocked a whole boot -- see the module.
pub mod wait;

/// Tier B typed-binding re-export facade. Only compiled when `game-types` is
/// enabled (product + er-telemetry-core); the zero-dep mini-DLLs never pull this in.
#[cfg(all(windows, feature = "game-types"))]
pub mod game_types {
    pub use eldenring;
    pub use fromsoftware_shared;
}
