//! The list the picker shows: every creature the mod can wear, with a name on it.
//!
//! Two shipped tables joined on chr id. `moveset.tbl` says what a creature can DO and is the set
//! of ids the possession engine will accept; `chrnames.tbl` says what to CALL it. The join is
//! left on the moveset table, so the catalogue and the engine agree on membership by
//! construction -- a name with no moveset row is not a creature you can become and does not
//! appear, and a moveset row with no name appears as `cNNNN` rather than being hidden.
//!
//! # Why the row carries move counts and not just a name
//!
//! Four hundred names is a phone book. The counts are what turn it into a choice: a row reading
//! `Malenia c2120  41 moves  L18 H18 M5` and one reading `Wolf c4070  16 moves  L5 H5 R3 M3` tell
//! you, before you commit, that one is a duellist and the other is a small fast thing with a
//! ranged option. Every number here is already in `moveset.tbl` -- this counts them, it does not
//! learn anything new -- and the twenty creatures with no fireable move at all are marked,
//! because becoming one gets you a body that cannot attack and that is worth knowing in the list
//! rather than after the possession.
//!
//! # Built once, on the first open
//!
//! 408 lines of `moveset.tbl` parsed and sorted is not per-frame work, and it is not
//! process-start work either: a session that never opens the picker should not pay for it. The
//! `OnceLock` puts it exactly where it belongs -- the first press of the picker hotkey.

// Pure parsing over two compiled-in tables. Ungated so `cargo test` proves the join, the sort and
// the group keys on the host, where none of the game bindings exist.
#![cfg_attr(not(windows), allow(dead_code))]

use std::sync::OnceLock;

use crate::moveset::table::{self, TABLE_TEXT};
use crate::settings::Bucket;

/// The name table, compiled in beside the moveset table.
///
/// Generated by `scripts/er-chr-names-gen.py`; see that file for where the names come from and
/// why they are Paramdex row names rather than the game's own `NpcName.fmg` (which names 73 of
/// these 408, because the game never displays a name for a wolf).
pub(crate) const NAMES_TEXT: &str = include_str!("../../data/chrnames.tbl");

/// Bumped when the name table's shape changes. Checked against the file at parse time for the
/// same reason `table::TABLE_VERSION` is: a generator and a parser that disagree silently
/// produce a list of wrong names rather than an error.
pub(crate) const NAMES_VERSION: u32 = 1;

/// What the generator writes when no source names a creature.
const NO_NAME: &str = "-";

/// One row of the picker.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct Creature {
    pub(crate) chr_id: u32,
    /// Empty when no source names this id. Use [`Self::label`] rather than reading this.
    pub(crate) name: &'static str,
    /// Fireable moves, i.e. what the dispatcher will have to work with.
    pub(crate) moves: u16,
    /// Animations the offline classifier looked at and withheld. Not shown as a headline number;
    /// it is here because "8 moves out of 60 considered" and "8 out of 8" are different creatures.
    pub(crate) denials: u16,
    /// Fireable moves per bucket, in [`Bucket`] order: light, heavy, ranged, movement.
    pub(crate) buckets: [u16; 4],
}

impl Creature {
    /// What the list draws. The id is always shown as well, by the caller -- a player who knows
    /// they want `c4500` should not have to know it is called Flying Dragon.
    pub(crate) fn label(&self) -> &'static str {
        if self.name.is_empty() {
            // Deliberately not a `format!`: this is called per visible row per frame, and the
            // three unnamed ids are the only rows that would allocate.
            "(unnamed)"
        } else {
            self.name
        }
    }

    /// The character the group jump moves between: the first letter of what the row is sorted
    /// under, uppercased, with everything non-alphabetic collapsed to `#`.
    ///
    /// PRECONDITION, held by the sort rather than by this function: every group key must occupy
    /// ONE contiguous run of the sorted catalogue, because
    /// [`crate::picker::model`]'s group jump treats the run around an index as the whole group.
    /// It holds today -- every shipped name is ASCII with an alphabetic initial, and the three
    /// unnamed rows label as `(unnamed)`, which sorts under `(` (0x28) below `A` and so forms one
    /// run at the top. A future name beginning with something that uppercases ABOVE `Z` (`_`,
    /// a backtick, a non-ASCII letter) would split `#` into two runs and strand rows the jump
    /// cannot reach. `walking_the_group_axis_visits_every_group_of_the_shipped_catalogue` is the
    /// guard that would catch it.
    pub(crate) fn group(&self) -> u8 {
        match self.name.as_bytes().first() {
            Some(byte) if byte.is_ascii_alphabetic() => byte.to_ascii_uppercase(),
            _ => b'#',
        }
    }

    /// True when this creature has nothing to fire -- a variant that owns a model but declares
    /// no animations of its own. TWENTY of the 408, written `<id> -` in `moveset.tbl`: zero
    /// moves and zero denials, because there was nothing to classify rather than everything
    /// being withheld. (Not to be confused with the THREE that have no NAME; different set,
    /// different reason.)
    pub(crate) const fn is_mute(&self) -> bool {
        self.moves == 0
    }

    /// The row's headline, clipped so a long name cannot push the id and the counts off the
    /// panel.
    ///
    /// Here rather than in [`crate::picker::render`] because that module is windows-only, and a
    /// text function whose whole risk is slicing a `str` at the wrong boundary is exactly the
    /// kind that must be provable by `cargo test` on the host.
    pub(crate) fn clipped_label(&self) -> String {
        let label = self.label();
        if label.chars().count() <= LABEL_MAX_CHARS {
            return label.to_owned();
        }
        // CHARACTER boundaries, not bytes: the shipped names are ASCII today and nothing
        // guarantees the next generation will be, and slicing a `str` mid-codepoint panics
        // rather than producing a shorter name.
        let mut out: String = label.chars().take(LABEL_MAX_CHARS - 1).collect();
        out.push('~');
        out
    }

    /// A compact shape for the row -- `L5 H5 R3 M3` -- so the list distinguishes a ranged caster
    /// from a melee brawler before you commit to becoming one.
    pub(crate) fn shape(&self) -> String {
        if self.is_mute() {
            return "no moves".to_owned();
        }
        let mut out = String::new();
        for (count, tag) in self.buckets.iter().zip(BUCKET_TAGS) {
            if *count > 0 {
                if !out.is_empty() {
                    out.push(' ');
                }
                out.push_str(tag);
                out.push_str(&count.to_string());
            }
        }
        out
    }
}

/// How much of a name a row shows.
pub(crate) const LABEL_MAX_CHARS: usize = 32;

/// One letter per bucket, in [`Creature::buckets`] order.
const BUCKET_TAGS: [&str; 4] = ["L", "H", "R", "M"];

/// Parse `chrnames.tbl` into `(chr_id, name)` pairs, in file order.
///
/// Borrowed out of the compiled-in text rather than owned, so a `Creature` is `Copy` and the
/// whole catalogue is one allocation.
fn parse_names(text: &'static str) -> Vec<(u32, &'static str)> {
    // A VERSION THIS PARSER DOES NOT KNOW YIELDS NO NAMES, rather than names read under the wrong
    // rules. Every row then draws as `(unnamed)` beside its id, which is a picker that still
    // works and a failure nobody could mistake for correct -- and the host test
    // `almost_every_creature_has_a_name` goes red the moment it happens, which is where a
    // regeneration mismatch is actually caught.
    if declared_names_version(text) != Some(NAMES_VERSION) {
        return Vec::new();
    }
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') || line.starts_with('v') {
            continue;
        }
        let Some((id, name)) = line.split_once('\t') else {
            continue;
        };
        let Ok(chr_id) = id.trim().parse::<u32>() else {
            continue;
        };
        out.push((chr_id, if name == NO_NAME { "" } else { name }));
    }
    out
}

/// The `vN` marker at the top of the name table, or `None` when it has none.
fn declared_names_version(text: &str) -> Option<u32> {
    text.lines()
        .map(str::trim)
        .find(|line| !line.is_empty() && !line.starts_with('#'))
        .and_then(|line| line.strip_prefix('v'))
        .and_then(|rest| rest.parse().ok())
}

/// Join the two tables and sort the result for display.
///
/// Sort key is the LABEL, case-folded -- the thing on screen -- so the group jump lands where a
/// reader expects. Ties break on chr id so two creatures sharing a name (Rennala is `2030` and
/// `2031`) keep a stable, reproducible order rather than whatever the parse happened to produce.
fn build(moveset_text: &'static str, names_text: &'static str) -> Vec<Creature> {
    let names = parse_names(names_text);
    let mut out = Vec::with_capacity(names.len());
    for line in moveset_text.lines() {
        let Some((chr_id, moveset)) = table::parse_line(line) else {
            continue;
        };
        let mut buckets = [0u16; 4];
        for entry in &moveset.moves {
            let index = match entry.bucket {
                Bucket::Light => 0,
                Bucket::Heavy => 1,
                Bucket::Ranged => 2,
                Bucket::Movement => 3,
            };
            buckets[index] = buckets[index].saturating_add(1);
        }
        let name = names
            .iter()
            .find(|(id, _)| *id == chr_id)
            .map_or("", |(_, name)| *name);
        out.push(Creature {
            chr_id,
            name,
            moves: u16::try_from(moveset.moves.len()).unwrap_or(u16::MAX),
            denials: u16::try_from(moveset.denials.len()).unwrap_or(u16::MAX),
            buckets,
        });
    }
    // DECORATE-SORT-UNDECORATE, because `sort_by` calls its comparator O(n log n) times and a
    // comparator that case-folds would allocate two Strings on every one of them. Keying once
    // per row is 408 allocations instead of ~7000.
    let mut decorated: Vec<(String, Creature)> = out
        .into_iter()
        .map(|creature| (sort_key(&creature), creature))
        .collect();
    decorated.sort_by(|a, b| a.0.cmp(&b.0).then_with(|| a.1.chr_id.cmp(&b.1.chr_id)));
    decorated
        .into_iter()
        .map(|(_, creature)| creature)
        .collect()
}

/// Case-folded label, computed once per row during the sort and never again.
fn sort_key(creature: &Creature) -> String {
    creature.label().to_ascii_uppercase()
}

/// The catalogue, built on first use.
pub(crate) fn creatures() -> &'static [Creature] {
    static CATALOG: OnceLock<Vec<Creature>> = OnceLock::new();
    CATALOG.get_or_init(|| build(TABLE_TEXT, NAMES_TEXT))
}

/// The group key of every row, in row order -- what [`crate::picker::model`] jumps between.
///
/// A second `OnceLock` rather than a method on the model, because the jump reads it for every
/// candidate index and rebuilding it per press would make a keypress O(n) allocations instead of
/// O(n) comparisons.
pub(crate) fn groups() -> &'static [u8] {
    static GROUPS: OnceLock<Vec<u8>> = OnceLock::new();
    GROUPS.get_or_init(|| creatures().iter().map(Creature::group).collect())
}

/// Where a chr id sits in the sorted catalogue, so opening the picker can start on whatever is
/// already staged rather than at the top of the alphabet.
pub(crate) fn index_of(chr_id: u32) -> Option<usize> {
    creatures().iter().position(|c| c.chr_id == chr_id)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_compiled_in_name_table_declares_the_version_this_parser_reads() {
        assert_eq!(declared_names_version(NAMES_TEXT), Some(NAMES_VERSION));
    }

    /// The join is LEFT on the moveset table. Every creature the engine will accept has a row,
    /// and no row exists for an id the engine would refuse -- if these two drift apart the
    /// picker offers something that cannot be possessed, which looks like the possession being
    /// broken rather than the list being wrong.
    #[test]
    fn every_creature_in_the_moveset_table_is_in_the_catalogue_and_nothing_else_is() {
        let catalog = creatures();
        let mut from_table: Vec<u32> = table::chr_ids().collect();
        from_table.sort_unstable();
        let mut from_catalog: Vec<u32> = catalog.iter().map(|c| c.chr_id).collect();
        from_catalog.sort_unstable();
        assert_eq!(from_catalog, from_table);
        assert!(catalog.len() > 400, "{} rows", catalog.len());
    }

    /// The names table covers the ids the moveset table has, not some other set. A generator run
    /// against a stale moveset table would show up here as unnamed rows appearing in bulk.
    #[test]
    fn almost_every_creature_has_a_name() {
        let named = creatures().iter().filter(|c| !c.name.is_empty()).count();
        let total = creatures().len();
        assert!(
            named + 3 >= total,
            "{named}/{total} named; the shipped table had 405/408 and losing more than the three \
             known-unnamed ids means the join broke"
        );
    }

    #[test]
    fn the_catalogue_is_sorted_by_label_then_id() {
        let catalog = creatures();
        for pair in catalog.windows(2) {
            let (a, b) = (&pair[0], &pair[1]);
            assert!(
                (sort_key(a), a.chr_id) <= (sort_key(b), b.chr_id),
                "{:?} before {:?}",
                a.label(),
                b.label()
            );
        }
    }

    #[test]
    fn a_known_creature_carries_the_counts_its_moveset_row_declares() {
        let malenia = creatures()
            .iter()
            .find(|c| c.chr_id == 2120)
            .expect("c2120 is in the shipped table");
        assert_eq!(malenia.name, "Malenia");
        let moveset = table::lookup(2120).expect("c2120 parses");
        assert_eq!(usize::from(malenia.moves), moveset.moves.len());
        assert_eq!(usize::from(malenia.denials), moveset.denials.len());
        assert_eq!(
            usize::from(malenia.buckets.iter().sum::<u16>()),
            moveset.moves.len(),
            "every fireable move lands in exactly one bucket"
        );
        assert_eq!(malenia.group(), b'M');
    }

    #[test]
    fn an_unnamed_creature_is_labelled_rather_than_hidden() {
        let unnamed: Vec<u32> = creatures()
            .iter()
            .filter(|c| c.name.is_empty())
            .map(|c| c.chr_id)
            .collect();
        assert_eq!(unnamed, vec![5194, 5261, 6240], "{unnamed:?}");
        for chr_id in unnamed {
            let row = creatures().iter().find(|c| c.chr_id == chr_id).unwrap();
            assert_eq!(row.label(), "(unnamed)");
            assert_eq!(row.group(), b'#');
        }
    }

    #[test]
    fn the_group_key_is_the_uppercased_first_letter_of_the_label() {
        for creature in creatures() {
            let group = creature.group();
            assert!(
                group.is_ascii_uppercase() || group == b'#',
                "{:?} -> {group}",
                creature.label()
            );
        }
        // Every letter the list actually uses is reachable, which is what makes the group jump a
        // usable index rather than a decoration.
        let distinct: std::collections::BTreeSet<u8> = groups().iter().copied().collect();
        assert!(distinct.len() > 15, "{distinct:?}");
    }

    #[test]
    fn groups_line_up_with_the_catalogue_row_for_row() {
        assert_eq!(groups().len(), creatures().len());
        for (index, creature) in creatures().iter().enumerate() {
            assert_eq!(groups()[index], creature.group());
        }
    }

    #[test]
    fn index_of_finds_a_staged_id_and_rejects_one_the_table_does_not_have() {
        let index = index_of(2120).expect("c2120 is in the catalogue");
        assert_eq!(creatures()[index].chr_id, 2120);
        assert_eq!(index_of(0), None);
        assert_eq!(index_of(999_999), None);
    }

    #[test]
    fn the_name_parser_skips_comments_the_version_marker_and_junk() {
        let parsed = parse_names("# header\nv1\n2120\tMalenia\n5194\t-\nnot a row\n");
        assert_eq!(parsed, vec![(2120, "Malenia"), (5194, "")]);
    }

    #[test]
    fn a_long_name_is_clipped_on_a_character_boundary() {
        let long = Creature {
            chr_id: 1,
            name: "God-Devouring Serpent / Rykard, Lord of Blasphemy",
            moves: 1,
            denials: 0,
            buckets: [1, 0, 0, 0],
        };
        let clipped = long.clipped_label();
        assert_eq!(clipped.chars().count(), LABEL_MAX_CHARS);
        assert!(clipped.ends_with('~'));
    }

    /// Every shipped name has to survive the row formatter, which is the whole risk of slicing a
    /// `str` by a character count.
    #[test]
    fn every_shipped_name_formats_without_panicking() {
        for creature in creatures() {
            assert!(creature.clipped_label().chars().count() <= LABEL_MAX_CHARS);
            let _ = creature.shape();
        }
    }

    #[test]
    fn the_shape_names_only_the_buckets_a_creature_actually_has() {
        let wolf = creatures()
            .iter()
            .find(|c| c.chr_id == 4070)
            .expect("c4070 is in the shipped table");
        let shape = wolf.shape();
        for (count, tag) in wolf.buckets.iter().zip(BUCKET_TAGS) {
            assert_eq!(shape.contains(tag), *count > 0, "{shape:?} vs {tag}");
        }
        let mute = creatures()
            .iter()
            .find(|c| c.is_mute())
            .expect("the shipped table has a creature with nothing fireable");
        assert_eq!(mute.shape(), "no moves");
    }

    /// A table written by a generator this parser does not know yields NO names rather than names
    /// read under the wrong rules. Every row then shows its id, which is usable and unmistakable.
    #[test]
    fn a_name_table_from_a_future_generator_yields_no_names_at_all() {
        assert!(parse_names("v99\n2120\tMalenia\n").is_empty());
        assert!(
            parse_names("2120\tMalenia\n").is_empty(),
            "no marker at all"
        );
    }

    /// Three creatures in the shipped table have nothing fireable. They stay in the list on
    /// purpose -- see the module docs -- so the flag has to be reachable.
    #[test]
    fn creatures_with_no_fireable_move_are_flagged_rather_than_dropped() {
        // Sorted, because the catalogue is ordered by LABEL and these come out interleaved by
        // name. The set is what is being asserted, not the display order.
        let mut mute: Vec<u32> = creatures()
            .iter()
            .filter(|c| c.is_mute())
            .map(|c| c.chr_id)
            .collect();
        mute.sort_unstable();
        // EXACT, not `!is_empty()`. The count is quoted in this module's docs and in the panel's
        // detail line, and a loose assertion is how "three" survived in those two places while
        // the table said twenty.
        assert_eq!(
            mute,
            vec![
                1000, 2050, 2060, 2131, 2160, 2170, 4711, 4751, 5180, 5181, 5330, 5340, 5430, 5480,
                5490, 5910, 6040, 6090, 6100, 8120
            ],
            "{} rows with nothing fireable",
            mute.len()
        );
        for chr_id in mute {
            let row = creatures().iter().find(|c| c.chr_id == chr_id).unwrap();
            assert_eq!(row.buckets, [0; 4]);
            // Zero denials too, which is what the panel's detail line says about them: nothing
            // was classified, rather than everything being withheld.
            assert_eq!(row.denials, 0);
        }
    }
}
