use std::{
    env,
    path::{Path, PathBuf},
};

// Single cc-compile of the vendored MinHook C source, replacing the three near-identical build
// scripts that previously lived in each game cdylib (er-quickload, er-reload-trace,
// er-input-harness). Windows-target gated -- the C uses Win32 APIs, so a host `cargo check`
// (which still runs build scripts) must not try to compile it.
/// Where the verified 1.16.2 -> 1.17 address pairs come from. Tracked, generated by
/// `scripts/verify-rva-map-1170.py`, and read here rather than transcribed: a hand-copied address
/// table is the exact failure this whole migration is about.
const VERIFIED_MAP: &str = "../../docs/recon/rva-map-1162-to-1170.verified.tsv";
/// Only rows the verifier judged the SAME FUNCTION -- normalised instruction sequences identical
/// over at least this many instructions. `NEAR`, `DIVERGES` and `IDENTICAL-SHORT` rows are left
/// out on purpose: an address that merely looks similar is how a detour lands mid-function.
const MIN_VERIFIED_INSNS: u32 = 12;
/// Mappings held back despite verifying, because the HANDLER at that address is what turned out
/// to be stale. See the file's own header for the distinction it exists to record.
const QUARANTINE: &str = "../../docs/recon/rva-1170-quarantine.tsv";

/// 1.16.2 RVAs excluded from translation.
fn quarantined(root_dir: &str) -> Vec<u32> {
    let path = Path::new(root_dir).join(QUARANTINE);
    println!("cargo:rerun-if-changed={}", path.display());
    let mut out = Vec::new();
    if let Ok(text) = std::fs::read_to_string(&path) {
        for line in text.lines() {
            if line.starts_with('#') || line.trim().is_empty() {
                continue;
            }
            if let Some(rva) = line.split('\t').next()
                && let Ok(value) = u32::from_str_radix(rva.trim().trim_start_matches("0x"), 16)
            {
                out.push(value);
            }
        }
    }
    out
}

/// Emit the translation table `er-hook` consults when the running build is not 1.16.2.
fn emit_address_map(root_dir: &str) {
    let map_path = Path::new(root_dir).join(VERIFIED_MAP);
    println!("cargo:rerun-if-changed={}", map_path.display());
    let mut rows: Vec<(u32, u32)> = Vec::new();
    if let Ok(text) = std::fs::read_to_string(&map_path) {
        for line in text.lines() {
            if line.starts_with('#') || line.trim().is_empty() {
                continue;
            }
            let fields: Vec<&str> = line.split('\t').collect();
            if fields.len() < 5 || fields[2] != "IDENTICAL" {
                continue;
            }
            let compared: u32 = fields[4].trim().parse().unwrap_or(0);
            if compared < MIN_VERIFIED_INSNS {
                continue;
            }
            let parse = |s: &str| u64::from_str_radix(s.trim().trim_start_matches("0x"), 16).ok();
            if let (Some(old), Some(new)) = (parse(fields[0]), parse(fields[1])) {
                // Stored as RVAs: the table has to survive a relocated image base.
                rows.push(((old - 0x140000000) as u32, (new - 0x140000000) as u32));
            }
        }
    }
    let held_back = quarantined(root_dir);
    rows.retain(|(old, _)| !held_back.contains(old));
    rows.sort_unstable();
    let mut out = String::from(
        "// GENERATED by er-hook/build.rs from docs/recon/rva-map-1162-to-1170.verified.tsv.\n\
         // Verified 1.16.2 -> 1.17 pairs, as (rva_1162, rva_1170). Do not edit by hand.\n",
    );
    out.push_str(&format!(
        "pub(crate) const VERIFIED_1162_TO_1170: [(u32, u32); {}] = [\n",
        rows.len()
    ));
    for (old, new) in &rows {
        out.push_str(&format!("    ({old:#x}, {new:#x}),\n"));
    }
    out.push_str("];\n");
    let out_dir = env::var("OUT_DIR").unwrap();
    std::fs::write(Path::new(&out_dir).join("address_map_1170.rs"), out).unwrap();
}

fn main() {
    let root_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    // Emitted for every target: the table is plain data the library always includes, and a host
    // `cargo check` must not end up compiling against a stale or missing file.
    emit_address_map(&root_dir);
    let target = env::var("TARGET").unwrap();
    if !target.contains("windows") {
        println!("cargo:rerun-if-changed=build.rs");
        return;
    }

    let arch = target.split('-').next().unwrap_or_default();

    let hde = match arch {
        "i686" => "hde/hde32.c",
        "x86_64" => "hde/hde64.c",
        _ => panic!("Architecture '{arch}' not supported by bundled MinHook"),
    };

    let mh_src_dir = resolve_minhook_src_dir(Path::new(&root_dir));

    cc::Build::new()
        .file(mh_src_dir.join("buffer.c"))
        .file(mh_src_dir.join("hook.c"))
        .file(mh_src_dir.join("trampoline.c"))
        .file(mh_src_dir.join(hde))
        .compile("minhook");

    println!("cargo:rerun-if-env-changed=ER_MINHOOK_SRC_DIR");
    println!("cargo:rerun-if-env-changed=ER_QUICKLOAD_MINHOOK_SRC_DIR");
    println!("cargo:rerun-if-changed={}", mh_src_dir.display());
}

/// The main working tree, asked of git rather than guessed from the directory layout.
///
/// Returns `None` for anything that is not a git checkout, or if git is unavailable -- the caller
/// then falls through to its existing panic, which names the env overrides.
fn git_common_dir_parent(manifest_dir: &Path) -> Option<PathBuf> {
    let output = std::process::Command::new("git")
        .args(["rev-parse", "--path-format=absolute", "--git-common-dir"])
        .current_dir(manifest_dir)
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let common = PathBuf::from(String::from_utf8(output.stdout).ok()?.trim());
    // `<main tree>/.git` -> `<main tree>`. A bare repo has no working tree and yields nothing
    // useful, which the `buffer.c` check at the call site rejects anyway.
    common.parent().map(Path::to_path_buf)
}

fn resolve_minhook_src_dir(manifest_dir: &Path) -> PathBuf {
    for env_name in ["ER_MINHOOK_SRC_DIR", "ER_QUICKLOAD_MINHOOK_SRC_DIR"] {
        if let Ok(dir) = env::var(env_name) {
            let dir = PathBuf::from(dir);
            if dir.join("buffer.c").is_file() {
                return dir;
            }
            panic!("{env_name}={} does not point at MinHook src", dir.display());
        }
    }

    let repo_local = manifest_dir.join("../../vendor/minhook/src");
    if repo_local.join("buffer.c").is_file() {
        return repo_local;
    }

    for ancestor in manifest_dir.ancestors() {
        let candidate = ancestor.join("vendor/minhook/src");
        if candidate.join("buffer.c").is_file() {
            return candidate;
        }
        // `vendor/` is git-excluded and exists only in the MAIN checkout, so a build from a linked
        // git worktree finds nothing above itself. Follow the worktree's `.git` file back to the
        // main working tree and look there before giving up.
        if let Some(main_worktree) = main_worktree_root(ancestor) {
            let candidate = main_worktree.join("vendor/minhook/src");
            if candidate.join("buffer.c").is_file() {
                return candidate;
            }
        }
    }

    // A git WORKTREE has no `vendor/` of its own: the directory is gitignored, so it exists only in
    // the checkout that populated it, and a worktree's ancestors are wherever it happens to sit --
    // typically a sibling of the repo, where the loop above finds nothing. Every worktree therefore
    // failed this build with "set ER_MINHOOK_SRC_DIR", which is a per-agent, per-session workaround
    // for a path the repo can resolve by itself.
    //
    // `--git-common-dir` is the main checkout's `.git` even when invoked from a worktree, so its
    // parent is the main working tree and the vendor drop lives beneath it.
    if let Some(main_tree) = git_common_dir_parent(manifest_dir) {
        let candidate = main_tree.join("vendor/minhook/src");
        if candidate.join("buffer.c").is_file() {
            return candidate;
        }
    }

    panic!(
        "unable to find vendor/minhook/src (checked {} and ancestor vendor dirs; set ER_MINHOOK_SRC_DIR or ER_QUICKLOAD_MINHOOK_SRC_DIR to the MinHook src directory)",
        repo_local.display()
    );
}

/// Main working tree of a linked git worktree, from its `.git` FILE.
///
/// A linked worktree's `.git` is a file reading `gitdir: <main>/.git/worktrees/<name>`, so the main
/// working tree is the grandparent of that `worktrees/<name>` directory, minus the `.git` component.
/// Returns None for a normal checkout (`.git` is a directory) or any shape that does not match.
fn main_worktree_root(dir: &Path) -> Option<PathBuf> {
    let dot_git = dir.join(".git");
    if !dot_git.is_file() {
        return None;
    }
    let contents = std::fs::read_to_string(&dot_git).ok()?;
    let gitdir = Path::new(contents.strip_prefix("gitdir:")?.trim());
    // <main>/.git/worktrees/<name> -> <main>/.git -> <main>
    let worktrees = gitdir.parent()?;
    if worktrees.file_name()? != "worktrees" {
        return None;
    }
    worktrees.parent()?.parent().map(Path::to_path_buf)
}
