#!/usr/bin/env python3
"""Gate: capitals in a comment must name something, never add emphasis.

The rule
========
Capitals in a comment are reserved for tokens that are genuinely spelled in capitals:
a `const`/`static`, an env var, an acronym (`DLL`, `RVA`, `ABI`), an x86 register or
mnemonic, a file or section name, an upstream symbol (`FUN_140679180`). They are never
a way to raise your voice. `this is NOT the same pointer` is banned; `NOT_A_POINTER`
and a backticked `NOT` are fine.

Emphasis-caps are not a style preference. This repo's comments carry the reverse
engineering -- what was measured, what refused, which of two addresses is live -- and
when a third of the words are shouting, the shouting stops marking anything. A reader
skimming for the one load-bearing sentence finds forty.

How a token is judged
=====================
An allowlist of technical vocabulary cannot work: registers, mnemonics, param names,
FromSoft types and `FUN_<addr>` symbols are an open set that grows every session, so an
allowlist rejects new correct writing every week. English is the closed set, so the
list is the English one -- `scripts/comment-caps-words.txt`, generated by
`scripts/gen-comment-caps-words.py` from wordfreq's everyday vocabulary. A capitalised
token whose lowercase form is on that list is emphasis. Everything else is a name.

Three things are never read, so they need no exemption:
  * anything inside backticks -- the escape hatch for quoting the x86 `NOT`, a
    `"NOT RUN"` status string, or a genuine constant that happens to be an English word;
  * a token attached to identifier or path characters -- `SAVE_OWNS`, `AGENTS.md`,
    `crate::THE_ONE`, `ER0000.sl2` are symbols, not sentences;
  * URLs.

The ratchet
===========
The tree had ~27,000 shouted words when this gate landed, so the gate is a ratchet, not
a wall: `scripts/comment-caps.baseline.json` records the count per file, and the gate
fails when a file rises above its number or when it falls below without the baseline
being updated. Both directions matter -- an unupdated decrease turns the recorded debt
into a lie and hands back slack that a later commit can spend. A file with no entry
must have no violations, so new code is held to the real rule from its first line.

`--fix` does the mechanical half (downcase, re-capitalise at sentence starts); read the
diff afterwards, because a shouted word is sometimes load-bearing and wants rewriting
into a sentence rather than downcasing.
"""

from __future__ import annotations

import argparse
import ast
import collections
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
WORDS_PATH = REPO_ROOT / "scripts" / "comment-caps-words.txt"
BASELINE_PATH = REPO_ROOT / "scripts" / "comment-caps.baseline.json"

SCANNED_SUFFIXES = {".rs": "rust", ".py": "python", ".sh": "hash", ".bash": "hash"}
# A local `git ls-files` / `git show` is milliseconds; the cap is the repo-wide safety backstop
# from scripts/check-no-timeouts.py, not a synchronisation mechanism.
GIT_TIMEOUT_SECONDS = 30

# A capitalised run. Two letters minimum: single letters are never shouting.
CAPS = re.compile(r"[A-Z]{2,}")
# Characters that make a token part of a larger name rather than a word in a sentence.
ATTACH = re.compile(r"[A-Za-z0-9_]")
BACKTICKED = re.compile(r"`[^`]*`")
QUOTED = re.compile(r'"[^"]*"')
TRIPLE_QUOTE = re.compile(r'\"\"\"|\'\'\'|[rbfu]{1,2}(?=\"\"\")|[rbfu]{1,2}(?=\'\'\')')
# Comment text other gates read. Downcasing a word inside one of these silently disarms that
# gate, so they are blanked before this one looks. Each is the literal a checker greps for.
MARKERS = (
    "PARITY:",  # scripts/check-lint-parity.py BLANKET_ALLOW_MARKER
    "HOOK-BATCH-ATOMIC:",  # scripts/check-hook-batch-abort.py ATOMIC_MARKER_RE
    "UTF-8 Lossy:",  # scripts/check-no-lossy-utf8.py JUSTIFICATION_MARKER
    "Foreign pointer:",  # scripts/check-no-unguarded-cstr-from-ptr.py
    "AOB signature:",  # scripts/check-prologue-bytes.py AOB_MARKER
    "Not a prologue:",  # scripts/check-prologue-bytes.py NOT_A_PROLOGUE_MARKER
    "GENERATED by",  # generated-file headers, e.g. crates/er-game-base/build.rs
    "SYN_INTEGRATION_TEST",  # scripts/find-dead-items.py fixture marker
)
FENCE = re.compile(r"^\s*(?://+!?|\*)?\s*```")
URL = re.compile(r"\b(?:https?|file|git)://\S+")
# A sentence start, for --fix: comment opener, or terminal punctuation plus space.
SENTENCE_END = re.compile(r"[.!?:;]\s*$|--\s*$")
# Words whose fix is Title Case, not lowercase.
PROPER_NOUNS = {
    "windows", "linux", "python", "rust", "steam", "wine", "june", "july",
    "august", "september", "october", "november", "december", "january",
    "february", "march", "april", "english",
}


@dataclass(frozen=True)
class Finding:
    path: str
    line: int
    word: str
    text: str


def load_words(path: Path = WORDS_PATH) -> frozenset[str]:
    words = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line and not line.startswith("#"):
            words.add(line.lower())
    if not words:
        raise SystemExit(f"{path}: no words loaded")
    return frozenset(words)


def comment_spans(text: str, dialect: str) -> list[tuple[int, str]]:
    """Return (1-based line number, comment text) for every comment in `text`.

    Hand-rolled rather than regexed because the whole point is to not read inside string
    literals: a `"//"` in a Rust string and a `'#'` in a Python one are code, and a gate
    that reads them reports findings in data the author cannot edit into compliance.
    """
    spans: list[tuple[int, str]] = []
    i, line, n = 0, 1, len(text)
    while i < n:
        c = text[i]
        if c == "\n":
            line += 1
            i += 1
            continue
        if dialect == "rust":
            if c == '"':
                j = _skip_rust_string(text, i)
                # Count the newlines inside the literal. Missing them desynchronises every line
                # number after the first multi-line string in the file, which made `--fix` refuse
                # the rewrite (the span was not on the line it named) and silently do nothing.
                line += text.count("\n", i, j)
                i = j
                continue
            if c == "r" and text.startswith(("r#", 'r"'), i):
                j = _skip_raw_string(text, i)
                if j != i:
                    line += text.count("\n", i, j)
                    i = j
                    continue
            if text.startswith("//", i):
                end = text.find("\n", i)
                end = n if end < 0 else end
                spans.append((line, text[i:end]))
                i = end
                continue
            if text.startswith("/*", i):
                depth, j = 1, i + 2
                start_line = line
                while j < n and depth:
                    if text.startswith("/*", j):
                        depth += 1
                        j += 2
                    elif text.startswith("*/", j):
                        depth -= 1
                        j += 2
                    else:
                        j += 1
                body = text[i:j]
                for offset, body_line in enumerate(body.splitlines()):
                    spans.append((start_line + offset, body_line))
                line += body.count("\n")
                i = j
                continue
            if c == "'" and _is_char_literal(text, i):
                j = _skip_char_literal(text, i)
                line += text.count("\n", i, j)
                i = j
                continue
        else:  # hash dialects: python and shell both comment with `#`
            if c in "\"'":
                j = _skip_hash_string(text, i)
                line += text.count("\n", i, j)
                i = j
                continue
            if c == "#":
                end = text.find("\n", i)
                end = n if end < 0 else end
                spans.append((line, text[i:end]))
                i = end
                continue
        i += 1
    return spans


def _skip_rust_string(text: str, i: int) -> int:
    j = i + 1
    while j < len(text):
        if text[j] == "\\":
            j += 2
            continue
        if text[j] == '"':
            return j + 1
        j += 1
    return len(text)


def _skip_raw_string(text: str, i: int) -> int:
    m = re.compile(r'r(#*)"').match(text, i)
    if not m:
        return i
    close = '"' + m.group(1)
    end = text.find(close, m.end())
    return len(text) if end < 0 else end + len(close)


def _is_char_literal(text: str, i: int) -> bool:
    # Distinguish 'a' / '\n' from a lifetime such as `&'static str`.
    return bool(re.compile(r"'(?:\\.|[^\\'])'").match(text, i))


def _skip_char_literal(text: str, i: int) -> int:
    m = re.compile(r"'(?:\\.|[^\\'])'").match(text, i)
    return m.end() if m else i + 1


def _skip_hash_string(text: str, i: int) -> int:
    quote = text[i]
    triple = text.startswith(quote * 3, i)
    close = quote * 3 if triple else quote
    j = i + len(close)
    while j < len(text):
        if text[j] == "\\":
            j += 2
            continue
        if text.startswith(close, j):
            return j + len(close)
        if not triple and text[j] == "\n":
            return j  # an unterminated quote is shell word-splitting, not a string
        j += 1
    return len(text)


def scrub(comment: str) -> str:
    """Blank the spans the gate must not read, keeping offsets so columns stay true.

    Backticks and double quotes both mean "this is a name, quoted" -- a `"NOT RUN"` status
    string in a comment is the code's word, not the author's, and downcasing it would make
    the comment misquote the thing it documents."""
    out = comment
    for pattern in (URL, BACKTICKED, QUOTED):
        out = pattern.sub(lambda m: " " * len(m.group(0)), out)
    for marker in MARKERS:
        start = 0
        while (at := out.find(marker, start)) >= 0:
            out = out[:at] + " " * len(marker) + out[at + len(marker) :]
            start = at + len(marker)
    return out


def shouted_spans(comment: str, words: frozenset[str]) -> list[tuple[int, int, str]]:
    """Return (start, end, word) for every shouted word. Offsets index `comment` itself:
    `scrub` blanks spans without changing their length, so a hit found in the scrubbed
    text sits at the same place in the original and `--fix` can rewrite it directly."""
    scrubbed = scrub(comment)
    spans = []
    for m in CAPS.finditer(scrubbed):
        before = scrubbed[m.start() - 1] if m.start() else ""
        after = scrubbed[m.end()] if m.end() < len(scrubbed) else ""
        # An empty neighbour is the start/end of the comment, i.e. a word boundary --
        # spelled out because `"" in "_.:/"` is True and silently exempts every hit.
        if ATTACH.match(before or " ") or (before and before in "_.:/"):
            continue
        if ATTACH.match(after or " ") or (after and after in "_:/"):
            continue
        if after == "." and ATTACH.match(scrubbed[m.end() + 1 : m.end() + 2] or " "):
            continue
        if m.group(0).lower() in words:
            spans.append((m.start(), m.end(), m.group(0)))
    return spans


def shouted_words(comment: str, words: frozenset[str]) -> list[str]:
    return [w for _, _, w in shouted_spans(comment, words)]


def docstring_spans(text: str) -> list[tuple[int, str]]:
    """Module/class/function docstring lines, as raw source lines.

    A Python docstring is a string to the interpreter and documentation to everyone else, so
    the rule has to reach it -- otherwise the way to keep shouting is to move the sentence
    from a `#` comment into the docstring above it. 6,886 shouted words were sitting there
    when this gate landed, against 32k in comments."""
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []  # a file that does not parse is not this gate's problem
    lines = text.splitlines()
    spans = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        body = getattr(node, "body", None)
        if not body:
            continue
        first = body[0]
        if not (isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant)):
            continue
        if not isinstance(first.value.value, str):
            continue
        for n in range(first.lineno, (first.end_lineno or first.lineno) + 1):
            if n <= len(lines):
                # Blank the delimiters, keeping the line's length: `scrub` treats a double-quoted
                # span as a quotation, and a `"""` would otherwise make the whole docstring one.
                spans.append((n, TRIPLE_QUOTE.sub(lambda m: " " * len(m.group(0)), lines[n - 1])))
    return spans


SHEBANG = re.compile(r"^#!")


def drop_code(spans: list[tuple[int, str]], doctests: bool = False) -> list[tuple[int, str]]:
    """Drop fenced blocks, and doctests where they can occur: both are code that happens to
    live in prose, and lowercasing an identifier inside one changes what the example does.

    `doctests` is off outside Python docstrings on purpose -- a `// ...` continuation is
    ordinary prose in a Rust comment, and reading it as a doctest blinds the gate to the
    line under it."""
    out, fenced, doctest = [], False, False
    for line, body in spans:
        stripped = body.strip()
        if line == 1 and SHEBANG.match(stripped):
            continue  # `#!/usr/bin/env bash` is an interpreter directive, not a sentence
        if FENCE.match(body):
            fenced = not fenced
            continue
        if doctests and stripped.startswith((">>>", "...")):
            doctest = True
            continue
        if doctest:
            if not stripped:  # a blank line ends the expected output
                doctest = False
            continue
        if not fenced:
            out.append((line, body))
    return out


def prose_spans(text: str, dialect: str) -> list[tuple[int, str]]:
    """Every line of prose in the file: comments always, plus docstrings in Python."""
    spans = drop_code(comment_spans(text, dialect))
    if dialect == "python":
        spans += drop_code(docstring_spans(text), doctests=True)
    return sorted(set(spans))


def scan_file(path: Path, words: frozenset[str], rel: str) -> list[Finding]:
    dialect = SCANNED_SUFFIXES[path.suffix]
    text = path.read_text(encoding="utf-8", errors="replace")
    findings = []
    for line, comment in prose_spans(text, dialect):
        for word in shouted_words(comment, words):
            findings.append(Finding(rel, line, word, comment.strip()))
    return findings


def findings_at_head(rel: str, words: frozenset[str]) -> list[Finding] | None:
    """The same scan against `HEAD:<rel>`, or None when the file is new/unreadable there."""
    proc = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "show", f"HEAD:{rel}"],
        capture_output=True,
        text=True,
        timeout=GIT_TIMEOUT_SECONDS,
    )
    if proc.returncode:
        return None
    dialect = SCANNED_SUFFIXES[Path(rel).suffix]
    out = []
    for line, comment in prose_spans(proc.stdout, dialect):
        for word in shouted_words(comment, words):
            out.append(Finding(rel, line, word, comment.strip()))
    return out


def newly_shouted(now: list[Finding], head: list[Finding] | None) -> list[Finding]:
    """The findings this working tree added, by text rather than by line: a comment that only
    moved down the file is not a new violation, and reprinting a file's whole backlog on top of
    two new words is how a gate gets ignored."""
    if head is None:
        return now
    remaining = collections.Counter((f.word, f.text) for f in head)
    added = []
    for f in now:
        key = (f.word, f.text)
        if remaining[key]:
            remaining[key] -= 1
        else:
            added.append(f)
    return added


# Vendored upstream source. Their prose belongs to their authors, and rewriting it makes every
# future diff against upstream noisy for no gain here.
VENDORED = ("third_party/",)


def tracked_files(root: Path) -> list[Path]:
    out = subprocess.run(
        ["git", "-C", str(root), "ls-files", "-z"],
        capture_output=True,
        text=True,
        check=True,
        timeout=GIT_TIMEOUT_SECONDS,
    ).stdout
    return [
        root / p
        for p in out.split("\0")
        if p
        and Path(p).suffix in SCANNED_SUFFIXES
        and not p.startswith(VENDORED)
        and (root / p).is_file()
    ]


LONE_A = re.compile(r"(?<![A-Za-z0-9_])A(?![A-Za-z0-9_])")


def shouted_spans_for_fix(comment: str, words: frozenset[str]) -> list[tuple[int, int, str]]:
    """`shouted_spans`, plus any lone `A` standing inside a shouted run.

    The gate cannot flag a bare `A` -- `Category A` is a name and this is a one-letter word --
    but the fixer knows more: an `A` whose neighbour is being downcased was part of the same
    shouted phrase, and leaving it produces `indistinguishable from A gate`."""
    hits = shouted_spans(comment, words)
    if not hits:
        return hits
    scrubbed = scrub(comment)
    extra = []
    for m in LONE_A.finditer(scrubbed):
        if any(
            (m.end() + 1 == start and scrubbed[m.end() : start] == " ")
            or (end + 1 == m.start() and scrubbed[end : m.start()] == " ")
            for start, end, _ in hits
        ):
            extra.append((m.start(), m.end(), "A"))
    return sorted(hits + extra)


def replacement_for(span: str, start: int, word: str, opens_sentence: bool = True) -> str:
    """The lowercase form, capitalised when the word opens a sentence or is a proper noun.

    `opens_sentence` is what the caller knows and this function cannot: whether the previous
    comment line finished its sentence. A shouted word first on its line is usually mid-sentence
    -- the sentence started one line up -- and capitalising it produces `is Indistinguishable
    from`, which is worse than the shouting was."""
    lead = re.sub(r"^\s*(//+!?|/\*+|\*+|#+)\s*", "", span[:start])
    out = word.lower()
    if out in PROPER_NOUNS:
        return out.capitalize()
    if lead.strip():
        return out.capitalize() if SENTENCE_END.search(lead) else out
    return out.capitalize() if opens_sentence else out


def fix_comment(comment: str, words: frozenset[str], opens_sentence: bool = True) -> str:
    """Downcase shouted words in one span. `apply_fix` is the file-level path; this is the
    single-span form the selftest reads and the two share `replacement_for`."""
    out, last = [], 0
    for start, end, word in shouted_spans_for_fix(comment, words):
        out.append(comment[last:start])
        out.append(replacement_for(comment, start, word, opens_sentence))
        last = end
    out.append(comment[last:])
    return "".join(out)


def opens_a_sentence(previous: tuple[int, str] | None, line_no: int) -> bool:
    """Does a word first on `line_no` start a sentence? Only if the line above it ended one."""
    if previous is None or previous[0] != line_no - 1:
        return True
    body = re.sub(r"^\s*(//+!?|/\*+|\*+|#+)\s*", "", previous[1]).rstrip()
    return not body or bool(SENTENCE_END.search(body))


def span_offset(source_line: str, span: str) -> int:
    """Where `span` starts inside its source line.

    Two shapes reach here. A comment span is a substring of the line -- it starts at the `//`
    or `#`. A docstring span is the whole line with its `\"\"\"` delimiters blanked, so it is
    the same length and starts at column 0. Anything else is a bug in the scanner, and it is
    raised rather than skipped: skipping quietly is what turned `--fix` into a silent no-op."""
    at = source_line.find(span)
    if at >= 0:
        return at
    if len(span) == len(source_line.rstrip("\n")):
        return 0
    raise RuntimeError(f"span does not belong to its line: {span[:60]!r}")


def apply_fix(path: Path, words: frozenset[str]) -> int:
    dialect = SCANNED_SUFFIXES[path.suffix]
    text = path.read_text(encoding="utf-8")
    spans = prose_spans(text, dialect)
    if not spans:
        return 0
    lines = text.splitlines(keepends=True)
    changed = 0
    previous: tuple[int, str] | None = None
    for line_no, span in spans:
        idx = line_no - 1
        if idx >= len(lines):
            raise RuntimeError(f"{path}:{line_no}: past the end of the file")
        source = lines[idx]
        hits = shouted_spans_for_fix(span, words)
        opens = opens_a_sentence(previous, line_no)
        previous = (line_no, span)
        if not hits:
            continue
        base = span_offset(source, span)
        rewritten, last = [], 0
        for start, end, word in hits:
            rewritten.append(source[last : base + start])
            rewritten.append(replacement_for(span, start, word, opens))
            last = base + end
        rewritten.append(source[last:])
        lines[idx] = "".join(rewritten)
        changed += 1
    if changed:
        path.write_text("".join(lines), encoding="utf-8")
    return changed


def counts_by_file(findings: list[Finding]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for f in findings:
        counts[f.path] = counts.get(f.path, 0) + 1
    return counts


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("paths", nargs="*", help="limit the scan (default: every tracked file)")
    ap.add_argument("--fix", action="store_true", help="downcase shouted words in place")
    ap.add_argument("--update-baseline", action="store_true")
    ap.add_argument("--top", type=int, default=0, help="print the N worst files and exit 0")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    words = load_words()
    if args.paths:
        given = [Path(p).resolve() for p in args.paths]
        files = [p for p in given if p.suffix in SCANNED_SUFFIXES]
        for skipped in (p for p in given if p.suffix not in SCANNED_SUFFIXES):
            # Markdown and the rest are documents, not source; say so rather than raising.
            print(f"{skipped}: not a scanned source file, skipped", file=sys.stderr)
    else:
        files = tracked_files(REPO_ROOT)

    if args.fix:
        total = sum(apply_fix(p, words) for p in files)
        print(f"check-comment-caps: rewrote {total} comment lines")
        return 0

    findings: list[Finding] = []
    for path in files:
        findings.extend(scan_file(path, words, str(path.relative_to(REPO_ROOT))))
    counts = counts_by_file(findings)

    if args.top:
        for path, n in sorted(counts.items(), key=lambda kv: -kv[1])[: args.top]:
            print(f"{n:6d}  {path}")
        print(f"{sum(counts.values()):6d}  TOTAL over {len(counts)} files")
        return 0

    if args.update_baseline:
        BASELINE_PATH.write_text(
            json.dumps({"files": dict(sorted(counts.items()))}, indent=2) + "\n",
            encoding="utf-8",
        )
        print(f"{BASELINE_PATH}: {sum(counts.values())} in {len(counts)} files")
        return 0

    baseline = json.loads(BASELINE_PATH.read_text(encoding="utf-8"))["files"]
    if args.paths:  # a scoped run can only judge the files it looked at
        baseline = {k: v for k, v in baseline.items() if k in {str(p.relative_to(REPO_ROOT)) for p in files}}

    rose = {p: (counts[p], baseline.get(p, 0)) for p in counts if counts[p] > baseline.get(p, 0)}
    fell = {p: (counts.get(p, 0), baseline[p]) for p in baseline if counts.get(p, 0) < baseline[p]}

    for path, (now, was) in sorted(rose.items()):
        here = [f for f in findings if f.path == path]
        added = newly_shouted(here, findings_at_head(path, words))
        for f in added or here[: now - was]:
            print(f"{f.path}:{f.line}: {f.word} is emphasis, not a name: {f.text[:100]}", file=sys.stderr)
        print(f"{path}: {now} shouted words, baseline {was}", file=sys.stderr)

    if rose:
        print(
            "\nCaps in comments name things; they do not add emphasis. Lowercase the word,\n"
            "or put it in backticks if it really is a constant/register/symbol. Bulk fix:\n"
            "  python3 scripts/check-comment-caps.py --fix <paths>",
            file=sys.stderr,
        )
    if fell and not rose:
        print(
            f"{len(fell)} file(s) improved below the recorded baseline. Record it:\n"
            "  python3 scripts/check-comment-caps.py --update-baseline",
            file=sys.stderr,
        )
    return 1 if (rose or fell) else 0


def selftest() -> int:
    words = load_words()
    failures = []

    def check(name: str, got, want) -> None:
        if got != want:
            failures.append(f"{name}: got {got!r}, want {want!r}")

    check("emphasis", shouted_words("// this is NOT THE same", words), ["NOT", "THE"])
    check("backticked", shouted_words("// the x86 `NOT`, quoted", words), [])
    check("symbol", shouted_words("// SAVE_OWNS is set", words), [])
    check("filename", shouted_words("// see AGENTS.md", words), [])
    check("path", shouted_words("// docs/NOTES/ONLY.md", words), [])
    check("acronym", shouted_words("// THE DLL exports RVA 0x140 via ABI", words), ["THE"])
    check("upstream symbol", shouted_words("// FUN_140679180 calls it", words), [])
    check("sentence-final", shouted_words("// it does NOT.", words), ["NOT"])
    check("hyphenated", shouted_words("// a NON-BLOCKING read", words), ["NON", "BLOCKING"])
    check("single letter", shouted_words("// A read of B", words), [])
    check("url", shouted_words("// https://example.com/THE/ONLY", words), [])
    check("tag", shouted_words("// SAFETY: the pointer is live", words), [])
    check("register", shouted_words("// AL holds the byte", words), [])

    check("quoted literal", shouted_words('// prints "NOT RUN" and exits', words), [])
    check("gate marker", shouted_words("// PARITY: the two linters disagree", words), [])
    check("atomic marker", shouted_words("// HOOK-BATCH-ATOMIC: dtor needs its ctor", words), [])
    check(
        "python docstring is prose",
        [c.strip() for _, c in prose_spans('"""A DOCSTRING that shouts."""\nx = 1  # and THE comment\n', "python")],
["A DOCSTRING that shouts.", "# and THE comment"],
    )
    check(
        "docstring shouting is caught",
        shouted_words(prose_spans('"""A COMPLETELY shouted docstring."""\n', "python")[0][1], words),
        ["COMPLETELY"],
    )
    check(
        "doctest is code",
        [c.strip() for _, c in prose_spans('"""Text ONLY\n\n>>> f(THE)\nTHE\n\nmore THE\n"""\n', "python")],
["Text ONLY", "", "more THE", ""],
    )
    check(
        "shell is not python",
        [c for _, c in prose_spans("echo \"NOT a comment\"\n# but THIS\n", "hash")],
        ["# but THIS"],
    )
    check(
        "fenced code is not prose",
        [c for _, c in prose_spans("/// text ONLY\n/// ```\n/// let ONE = 1;\n/// ```\n/// more THE\n", "rust")],
        ["/// text ONLY", "/// more THE"],
    )
    check("proper noun keeps its capital", fix_comment("// on WINDOWS only", words), "// on Windows only")

    # The ratchet reports what this tree added, not the file's whole backlog, so a moved comment
    # must not read as new and an added one must not hide behind the count.
    old = [Finding("f.rs", 4, "THE", "// THE old shout"), Finding("f.rs", 9, "NOT", "// NOT this one")]
    moved = [Finding("f.rs", 40, "THE", "// THE old shout"), Finding("f.rs", 41, "NOT", "// NOT this one")]
    check("moved comment is not new", newly_shouted(moved, old), [])
    added = moved + [Finding("f.rs", 50, "EVERY", "// EVERY new word")]
    check("added comment is new", [f.word for f in newly_shouted(added, old)], ["EVERY"])
    check("new file reports everything", newly_shouted(added, None), added)

    rust = 'let s = "// NOT a comment";\n// but THIS is\n/* and THE block */\n'
    check(
        "rust spans",
        [c for _, c in comment_spans(rust, "rust")],
        ["// but THIS is", "/* and THE block */"],
    )
    check(
        "line numbers survive a multi-line string",
        comment_spans('let s = "a\nb\nc";\n// ONLY here\n', "rust"),
        [(4, "// ONLY here")],
    )
    check(
        "line numbers survive a multi-line raw string",
        comment_spans('let s = r#"a\nb"#;\n// ONLY here\n', "rust"),
        [(3, "// ONLY here")],
    )
    check(
        "rust raw string",
        [c for _, c in comment_spans('let s = r#"// NOT"#;\n// yes\n', "rust")],
        ["// yes"],
    )
    check(
        "rust lifetime",
        [c for _, c in comment_spans("fn f<'a>(x: &'a str) {} // ONLY\n", "rust")],
        ["// ONLY"],
    )
    check(
        "hash spans",
        [c for _, c in comment_spans('s = "# NOT"\n# but THIS\n', "hash")],
        ["# but THIS"],
    )
    check(
        "block comment line numbers",
        comment_spans("a\n/* ONE\nTWO */\n", "rust"),
        [(2, "/* ONE"), (3, "TWO */")],
    )

    check(
        "a word first on a continuation line stays lowercase",
        replacement_for("// ONWARD to the next line", 3, "ONWARD", opens_sentence=False),
        "onward",
    )
    check(
        "...and is capitalised when the line above ended its sentence",
        replacement_for("// ONWARD to the next line", 3, "ONWARD", opens_sentence=True),
        "Onward",
    )
    check(
        "a lone A inside a shouted run goes with it",
        fix_comment("// it is NOT A gate", words),
        "// it is not a gate",
    )
    check(
        "...but a lone A on its own is left alone",
        fix_comment("// Category A is checked first", words),
        "// Category A is checked first",
    )
    check(
        "a shebang is not prose",
        [c for _, c in prose_spans("#!/usr/bin/env bash\n# THE rest is\n", "hash")],
        ["# THE rest is"],
    )
    check(
        "a first line after a shebang opens its own sentence",
        fix_comment("# THE rest is", words, opens_a_sentence(None, 2)),
        "# The rest is",
    )
    check("continuation is detected", opens_a_sentence((4, "// a sentence that runs"), 5), False)
    check("full stop opens the next", opens_a_sentence((4, "// a sentence that ends."), 5), True)
    check("a gap opens the next", opens_a_sentence((4, "//"), 5), True)
    check("a distant line opens the next", opens_a_sentence((2, "// unfinished"), 5), True)
    check("fix mid-sentence", fix_comment("// it is NOT live", words), "// it is not live")
    check("fix sentence start", fix_comment("// NOT live", words), "// Not live")
    check("fix after period", fix_comment("// live. NOT dead", words), "// live. Not dead")
    check("fix keeps backticks", fix_comment("// `NOT` and NOT", words), "// `NOT` and not")
    check("fix keeps symbols", fix_comment("// SAVE_OWNS is NOT set", words), "// SAVE_OWNS is not set")

    # End-to-end on real files, because every earlier `--fix` defect was in the file-level path
    # (a line-number desync, then a docstring span that is not a substring of its line) and not
    # in the per-span rewrite the checks above exercise.
    import tempfile

    fixtures = {
        "sample.rs": (
            'let s = "a\nb\nc";\n// it is NOT live\n/// a doc THAT shouts\n',
            'let s = "a\nb\nc";\n// it is not live\n/// a doc that shouts\n',
        ),
        # The continuation case, end to end: the second line's first word belongs to the first
        # line's sentence, the fourth line's does not.
        "wrapped.rs": (
            "// a sentence that runs\n// ONWARD and ends here.\n//\n// ONWARD again\n",
            "// a sentence that runs\n// onward and ends here.\n//\n// Onward again\n",
        ),
        "sample.py": (
            '"""A COMPLETELY shouted docstring."""\n\n\ndef f():\n    """AND another."""\n    return 1  # THE end\n',
            '"""A completely shouted docstring."""\n\n\ndef f():\n    """And another."""\n    return 1  # The end\n',
        ),
        "sample.sh": ("# THE shell too\necho ok\n", "# The shell too\necho ok\n"),
    }
    with tempfile.TemporaryDirectory() as tmp:
        for name, (before, want) in fixtures.items():
            path = Path(tmp) / name
            path.write_text(before, encoding="utf-8")
            apply_fix(path, words)
            check(f"--fix on {name}", path.read_text(encoding="utf-8"), want)
            check(f"{name} is clean afterwards", scan_file(path, words, name), [])

    check(
        "vendored source is out of scope",
        [str(p) for p in tracked_files(REPO_ROOT) if "/third_party/" in str(p)],
        [],
    )

    for f in failures:
        print(f"selftest FAILURE {f}", file=sys.stderr)
    print(f"check-comment-caps selftest: {len(failures)} failure(s)")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
