#!/usr/bin/env python3
"""Ratchet on game addresses that are CALLED without asking where they live on this build.

Every game RVA in this workspace was reverse-engineered against ELDEN RING 1.16.2. On 2026-08-27
the game shipped 1.17 and moved the code. Two things then had to be gated, and only one was:

  DETOURS      `er-hook` resolves the address before installing, translating it when a mapping is
               verified and refusing when it is not. Done, and it turned a boot-killing crash into
               log lines.
  DIRECT CALLS `transmute(base + SOME_RVA)` builds a function pointer and calls it. Nothing looks
               at it. On a moved build this transfers control into whatever now occupies those
               bytes -- routinely the middle of an unrelated function, which faults with no unwind
               information and no exception record naming anything of ours. It is the WORSE of the
               two: a refused detour makes one feature inert and says so, while a stale call takes
               the process down and leaves a backtrace pointing into game code.

The fix per site is `er_game_base::mem::game_rva`, which translates or returns `Err`. Converting
them is ordinary work; what this gate exists to stop is the set GROWING while that happens. It is
a ratchet, not a freeze: removing sites is free, adding one is refused, and `--refresh` accepts a
new baseline as a reviewable diff rather than as an invisible default.

The key is (file, RVA constant), not a line number, so ordinary edits do not churn the baseline.

    python3 scripts/check-stale-rva-calls.py             # enforce
    python3 scripts/check-stale-rva-calls.py --list      # what is still ungated, by crate
    python3 scripts/check-stale-rva-calls.py --refresh   # accept the current set
    python3 scripts/check-stale-rva-calls.py --selftest
"""

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CRATES = os.path.join(ROOT, "crates")
BASELINE = os.path.join(ROOT, "docs", "recon", "stale-rva-call-sites.txt")
# A game function pointer built by adding a named RVA to the module base and transmuted. The
# `_RVA` suffix is this workspace's own naming convention for a 1.16.2 address, which is what
# makes the set findable at all.
CALL_SITE = re.compile(
    r"transmute(?:::<[^>]*>)?\(\s*(?:base|module_base|game_base|image_base)\s*\+\s*"
    r"([A-Z0-9_]*RVA[A-Z0-9_]*)\s*\)"
)


def sites():
    """{(crate-relative path, RVA constant)} for every ungated direct call in the tree."""
    found = set()
    for dirpath, dirnames, filenames in os.walk(CRATES):
        dirnames[:] = [d for d in dirnames if d != "target"]
        for name in filenames:
            if not name.endswith(".rs"):
                continue
            path = os.path.join(dirpath, name)
            relative = os.path.relpath(path, ROOT)
            text = open(path, encoding="utf-8", errors="replace").read()
            for constant in CALL_SITE.findall(text):
                found.add((relative, constant))
    return found


def baseline():
    if not os.path.exists(BASELINE):
        return set()
    out = set()
    for line in open(BASELINE, encoding="utf-8"):
        if line.startswith("#") or not line.strip():
            continue
        path, _, constant = line.strip().rpartition("\t")
        out.add((path, constant))
    return out


def write_baseline(current):
    with open(BASELINE, "w", encoding="utf-8") as handle:
        handle.write(
            "# Game addresses CALLED without resolving them for the running build.\n"
            "#\n"
            "# Generated by scripts/check-stale-rva-calls.py --refresh. One line per\n"
            "# (file, RVA constant). This set may SHRINK freely; growth is refused, because each\n"
            "# entry is a direct transfer of control to a 1.16.2 address on a build that moved the\n"
            "# code. Convert a site by resolving through er_game_base::mem::game_rva and handling\n"
            "# the Err, then re-run --refresh to record the smaller set.\n"
            f"# Currently {len(current)} sites in "
            f"{len({path for path, _ in current})} files.\n"
        )
        for path, constant in sorted(current):
            handle.write(f"{path}\t{constant}\n")


def report(current):
    by_crate = {}
    for path, constant in current:
        crate = path.split(os.sep)[1] if os.sep in path else path
        by_crate.setdefault(crate, set()).add(constant)
    for crate in sorted(by_crate, key=lambda c: (-len(by_crate[c]), c)):
        print(f"{len(by_crate[crate]):4}  {crate}")
    print(f"{len(current):4}  TOTAL across {len(by_crate)} crates")


def enforce():
    current, known = sites(), baseline()
    added = current - known
    removed = known - current
    if added:
        print(f"{len(added)} game address(es) newly CALLED without resolving for the build:\n")
        for path, constant in sorted(added):
            print(f"  {path}\t{constant}")
        print(
            "\nResolve through er_game_base::mem::game_rva, which translates the address when a\n"
            "mapping is verified and returns Err when it is not, and handle the Err. If the site\n"
            "is genuinely version-independent, say so at the call site and re-run --refresh."
        )
        return 1
    if removed:
        print(f"{len(removed)} site(s) resolved since the baseline -- run --refresh to record it:")
        for path, constant in sorted(removed):
            print(f"  {path}\t{constant}")
        return 1
    print(f"stale-rva-calls: {len(current)} known ungated site(s), none new")
    return 0


def selftest():
    """The matcher must find a real site and must not fire on a resolved one."""
    ungated = "let f: F = unsafe { std::mem::transmute(base + SET_SAVE_SLOT_RVA) };"
    gated = "let f: F = unsafe { transmute(game_rva(SET_SAVE_SLOT_RVA)?) };"
    assert CALL_SITE.findall(ungated) == ["SET_SAVE_SLOT_RVA"], "must flag a raw base + RVA call"
    assert not CALL_SITE.findall(gated), "must not flag a call already routed through game_rva"
    turbofish = "unsafe { transmute::<usize, F>(module_base + MENU_RVA) }"
    assert CALL_SITE.findall(turbofish) == ["MENU_RVA"], "must see through a turbofish"
    current = sites()
    assert current, "the tree has known ungated sites; finding none means the walk is broken"
    print(f"selftest OK ({len(current)} sites visible to the matcher)")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--refresh", action="store_true", help="accept the current set")
    parser.add_argument("--list", action="store_true", help="count ungated sites per crate")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()
    if args.selftest:
        return selftest()
    if args.list:
        report(sites())
        return 0
    if args.refresh:
        current = sites()
        write_baseline(current)
        print(f"baseline refreshed: {len(current)} site(s)")
        return 0
    return enforce()


if __name__ == "__main__":
    sys.exit(main())
