#!/usr/bin/env python3
"""Reject hand-written x86 prologue byte arrays in crate source.

This repo detours game functions by BYTE-CHECKING the target's prologue first and disarming with
a log line when it does not match. The expected bytes must therefore be exactly the bytes the game
ships -- and hand-typing them is a trap, because the same instruction often has more than one
legal encoding. `mov rax, rsp` is the concrete case: the game ships `48 8b c4`, an assembler that
is left to choose picks `48 89 e0`, and a prologue that differs by one byte is a hook that
byte-checks itself off on every launch. The feature looks built and does nothing.

So the rule is: a machine-code byte array is GENERATED, in a crate's `build.rs`, from NAMED
`iced-x86` instructions -- see `build-support/prologue_build.rs` and any crate `build.rs` that
uses it -- and reaches the source through `include!(concat!(env!("OUT_DIR"), ...))`.

What this gate flags: a `const`/`static` declaration of a `u8` array or slice, inside a crate's
`src/` (or a `build.rs` that is not a generator), whose initializer is a literal list of at least
MIN_BYTE_COUNT hex byte literals. That shape is machine code or a byte pattern; nothing else in
this tree is written that way.

Not everything with that shape is a prologue, so there are two escapes, both of which make the
author say WHY (the `// UTF-8 Lossy:` convention from `check-no-lossy-utf8.py`):

    // AOB signature: <why iced cannot generate this>
        for a pattern used to FIND code -- wildcards, or bytes that are not a decodable
        instruction sequence starting at a known VA. `iced-x86` assembles instructions; it
        cannot express those, so they are legitimately written out.

    // Not a prologue: <what these bytes are>
        for a payload written INTO the game, a jump stub, a file magic, or any other blob that
        is not compared against a function entry.

Do not reach for a marker to silence this gate on a real prologue: migrate it. The point is the
encoding, and a marker does not fix an encoding.

`build.rs` is scanned too, but a build script that uses `CodeAssembler` is exempt: that is the
generator, and its literals are the pins the generated bytes are asserted against.

KNOWN LIMIT, stated rather than hidden: only `const`/`static` DECLARATIONS are matched. An inline
`assert_eq!(SIG, &[0x48, ..])` in a test is not flagged -- there are ~450 inline hex arrays in
this tree, almost all of them legitimate test fixtures and asset headers, so flagging that shape
would be noise. A prologue smuggled in as an inline literal, or a `build.rs` that writes a
hand-typed array into `OUT_DIR`, is out of reach here and has to be caught in review.

Usage:
    python3 scripts/check-prologue-bytes.py
    python3 scripts/check-prologue-bytes.py --selftest
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
IGNORED_DIRECTORIES = {".git", ".worktrees", ".claude", "target", "third_party", "vendor"}

# Three is the shortest sequence that is unambiguously machine code rather than a small tuple of
# flags: the smallest thing this repo writes at a game function is a three-byte `xor eax,eax; ret`
# stub. (The shortest real detour prologue is seven bytes.)
MIN_BYTE_COUNT = 3

AOB_MARKER = "AOB signature:"
NOT_A_PROLOGUE_MARKER = "Not a prologue:"
MARKERS = (AOB_MARKER, NOT_A_PROLOGUE_MARKER)

# A build script that assembles instructions is the generator, not a hand-typed prologue.
GENERATOR_MARKER = "CodeAssembler"

DECLARATION = re.compile(
    r"(?:pub(?:\s*\([^)]*\))?\s+)?(?:const|static)\s+(?:mut\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*:\s*"
    r"(?:&\s*(?:'[a-z_][a-z0-9_]*\s+)?)?\[\s*u8\s*(?:;[^\]]*)?\]\s*=\s*&?\s*\[([^\]]*)\]\s*;",
    re.DOTALL,
)
HEX_BYTE = re.compile(r"0x[0-9a-fA-F]{1,2}")
BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
RAW_STRING = re.compile(r'(?s)(?:br|r)(?P<hashes>#{0,16})".*?"(?P=hashes)')
STRING = re.compile(r'(?s)(?:b)?"(?:\\.|[^"\\])*"')


@dataclass(frozen=True)
class Finding:
    path: str
    line: int
    name: str
    byte_count: int


def blank_out(match: re.Match[str]) -> str:
    """Replace a span with spaces, keeping every newline so line numbers survive."""
    return "".join("\n" if char == "\n" else " " for char in match.group(0))


def code_only(text: str) -> str:
    text = BLOCK_COMMENT.sub(blank_out, text)
    text = RAW_STRING.sub(blank_out, text)
    text = STRING.sub(blank_out, text)
    return "\n".join(line.split("//", 1)[0] for line in text.splitlines())


def is_scanned(relative: Path) -> bool:
    if any(part in IGNORED_DIRECTORIES for part in relative.parts):
        return False
    if relative.name == "build.rs":
        return True
    return "src" in relative.parts


def justified(lines: list[str], declaration_line: int, last_line: int) -> bool:
    """True when a marker appears on the declaration, inside it, or in the comment block above.

    The comment block is the contiguous run of `//` lines directly above the declaration, so a
    justification stays attached to what it justifies instead of drifting in from elsewhere.
    """
    for index in range(declaration_line - 1, last_line):
        if any(marker in lines[index] for marker in MARKERS):
            return True
    index = declaration_line - 2
    while index >= 0 and lines[index].lstrip().startswith("//"):
        if any(marker in lines[index] for marker in MARKERS):
            return True
        index -= 1
    return False


def scan_text(relative: Path, text: str) -> list[Finding]:
    if relative.name == "build.rs" and GENERATOR_MARKER in text:
        return []
    lines = text.splitlines()
    code = code_only(text)
    findings: list[Finding] = []
    for match in DECLARATION.finditer(code):
        elements = [item.strip() for item in match.group(2).split(",") if item.strip()]
        if len(elements) < MIN_BYTE_COUNT:
            continue
        if not all(HEX_BYTE.fullmatch(element) for element in elements):
            continue
        first = code.count("\n", 0, match.start()) + 1
        last = code.count("\n", 0, match.end()) + 1
        if justified(lines, first, last):
            continue
        findings.append(Finding(relative.as_posix(), first, match.group(1), len(elements)))
    return findings


def rust_files(root: Path) -> list[Path]:
    """Every `.rs` under `root` outside `IGNORED_DIRECTORIES`.

    The walk PRUNES `IGNORED_DIRECTORIES` as it descends instead of enumerating their contents
    and discarding them afterwards, which is what `rglob` forced. Identical by construction: a
    path under an ignored directory carries that directory in its relative `.parts`, so
    `is_scanned` already rejected it. Measured 2026-08-31: `rglob` traversed all 1,118,634
    entries under the repo root -- `.worktrees`, `.claude` and `target` are 99.4% of them -- to
    reach the 513 files this gate scans.
    """
    files: list[Path] = []
    for directory, subdirectories, filenames in os.walk(root):
        subdirectories[:] = [
            name for name in subdirectories if name not in IGNORED_DIRECTORIES
        ]
        base = Path(directory)
        for name in filenames:
            if name.endswith(".rs"):
                files.append(base / name)
    return sorted(files)


def scan(root: Path) -> list[Finding]:
    findings: list[Finding] = []
    for path in rust_files(root):
        relative = path.relative_to(root)
        if not is_scanned(relative):
            continue
        findings.extend(scan_text(relative, path.read_text(encoding="utf-8", errors="replace")))
    return findings


def report(findings: list[Finding]) -> None:
    print(
        "Hand-written machine-code byte arrays are banned in crate source.",
        file=sys.stderr,
    )
    print(
        "Generate the bytes in the crate's build.rs from NAMED iced-x86 instructions -- see\n"
        "build-support/prologue_build.rs and, for a worked example, "
        "crates/er-player-name-filter/build.rs -- and `include!` the result from OUT_DIR.\n"
        "A prologue that is one byte off (the game ships `mov rax, rsp` as 48 8b c4; an\n"
        "assembler left to choose emits 48 89 e0) disarms its own hook on every launch.\n"
        f"If these bytes are genuinely not a detour prologue, say so on the declaration or in\n"
        f"the comment block above it: '// {AOB_MARKER} ...' for a search pattern iced cannot\n"
        f"assemble, '// {NOT_A_PROLOGUE_MARKER} ...' for a payload or data blob.\n",
        file=sys.stderr,
    )
    for finding in findings:
        print(
            f"{finding.path}:{finding.line}: {finding.name}: "
            f"{finding.byte_count} hand-written bytes",
            file=sys.stderr,
        )


SELFTEST_CASES: list[tuple[str, int, dict[str, str]]] = [
    (
        "red: a bare prologue constant in crate src",
        1,
        {
            "crates/a/src/lib.rs": (
                "const APPLY_PROLOGUE: &[u8] = &[0x48, 0x89, 0x6c, 0x24, 0x10];\n"
            )
        },
    ),
    (
        "red: the same bytes as a fixed-size array, and as a static",
        2,
        {
            "crates/a/src/lib.rs": "pub const P: [u8; 4] = [0x48, 0x89, 0x6c, 0x24];\n",
            "crates/a/src/other.rs": (
                "static Q: &'static [u8] = &[0x40, 0x55, 0x56, 0x57];\n"
            ),
        },
    ),
    (
        "red: nested inside a function, which is where a test pin hides",
        1,
        {
            "crates/a/src/lib.rs": (
                "fn t() {\n"
                "    const SHARED: &[u8] = &[0x40, 0x55, 0x56, 0x57];\n"
                "}\n"
            )
        },
    ),
    (
        "green: justified as an AOB search signature",
        0,
        {
            "crates/a/src/lib.rs": (
                "// AOB signature: wildcards, so iced cannot assemble it.\n"
                "const NEEDLE: &[u8] = &[0x48, 0x89, 0x6c, 0x24, 0x10];\n"
            )
        },
    ),
    (
        "green: justified as not a prologue, on the declaration line itself",
        0,
        {
            "crates/a/src/lib.rs": (
                "const DDS_MAGIC: &[u8] = &[0x44, 0x44, 0x53, 0x20]; // Not a prologue: file magic\n"
            )
        },
    ),
    (
        "green: marker sits in the contiguous comment block above a multi-line literal",
        0,
        {
            "crates/a/src/lib.rs": (
                "// Not a prologue: the stub written INTO the game, not compared against it.\n"
                "// Second line of the same block.\n"
                "const STUB: &[u8] = &[\n"
                "    0x31, 0xc0, 0xc3, 0x90,\n"
                "];\n"
            )
        },
    ),
    (
        "red: a marker separated from the declaration by code does not justify it",
        1,
        {
            "crates/a/src/lib.rs": (
                "// Not a prologue: this comment belongs to something else.\n"
                "const OTHER: usize = 1;\n"
                "const P: &[u8] = &[0x48, 0x89, 0x6c, 0x24];\n"
            )
        },
    ),
    (
        "red: a three-byte patch stub is still machine code",
        1,
        {"crates/a/src/lib.rs": "pub const STUB: [u8; 3] = [0x31, 0xc0, 0xc3];\n"},
    ),
    (
        "green: below the byte-count floor",
        0,
        {"crates/a/src/lib.rs": "const FLAGS: &[u8] = &[0x01, 0x02];\n"},
    ),
    (
        "green: not all elements are hex byte literals",
        0,
        {
            "crates/a/src/lib.rs": (
                "const TAG: &[u8] = &[0x41, 0x42, b'C', 0x44];\n"
                "const WIDE: &[u16] = &[0x0048, 0x0049, 0x004a, 0x004b];\n"
            )
        },
    ),
    (
        "green: generated through OUT_DIR, which is the whole point",
        0,
        {
            "crates/a/src/lib.rs": (
                'include!(concat!(env!("OUT_DIR"), "/generated_prologues.rs"));\n'
            )
        },
    ),
    (
        "green: bytes quoted inside a comment or a string are not declarations",
        0,
        {
            "crates/a/src/lib.rs": (
                "// const P: &[u8] = &[0x48, 0x89, 0x6c, 0x24];\n"
                'const NOTE: &str = "const P: &[u8] = &[0x48, 0x89, 0x6c, 0x24];";\n'
                "/* const Q: &[u8] = &[0x48, 0x89, 0x6c, 0x24]; */\n"
            )
        },
    ),
    (
        "green: a build.rs that assembles instructions is the generator",
        0,
        {
            "crates/a/build.rs": (
                "fn main() {\n"
                "    let mut asm = CodeAssembler::new(64).unwrap();\n"
                "    const PIN: &[u8] = &[0x48, 0x89, 0x6c, 0x24, 0x10];\n"
                "}\n"
            )
        },
    ),
    (
        "red: a build.rs with no assembler is just a hand-typed array in a new place",
        1,
        {
            "crates/a/build.rs": (
                "fn main() {\n"
                "    const PIN: &[u8] = &[0x48, 0x89, 0x6c, 0x24, 0x10];\n"
                "}\n"
            )
        },
    ),
    (
        "green: out of scope -- neither crate src nor a build script",
        0,
        {"docs/notes.rs": "const P: &[u8] = &[0x48, 0x89, 0x6c, 0x24, 0x10];\n"},
    ),
    (
        "green: ignored directories are not scanned",
        0,
        {
            "target/debug/build/x/src/lib.rs": (
                "const P: &[u8] = &[0x48, 0x89, 0x6c, 0x24, 0x10];\n"
            )
        },
    ),
]


def selftest() -> int:
    failures: list[str] = []
    for label, expected, files in SELFTEST_CASES:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            for relative, body in files.items():
                target = root / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(body, encoding="utf-8")
            found = scan(root)
            if len(found) != expected:
                failures.append(
                    f"{label}: expected {expected} finding(s), got {len(found)}: "
                    + ", ".join(f"{item.path}:{item.line} {item.name}" for item in found)
                )
    if failures:
        print("check-prologue-bytes selftest FAILED:", file=sys.stderr)
        for failure in failures:
            print(f"  {failure}", file=sys.stderr)
        return 1
    print(f"check-prologue-bytes selftest passed ({len(SELFTEST_CASES)} cases)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--selftest", action="store_true", help=selftest.__doc__)
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    arguments = parser.parse_args()
    if arguments.selftest:
        return selftest()
    findings = scan(arguments.root.resolve())
    if findings:
        report(findings)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
