#!/usr/bin/env python3
"""Which per-run artifact does a run write, where does it go, and does it survive the NEXT run?

THE FAILURE THIS EXISTS TO REFUSE
---------------------------------
A game-directory artifact is SINGLE-SLOT, not a log that accumulates. `er_game_base::log::
begin_fresh_run` renames `<name>` to `<name>.prev` and truncates, ONE generation, on the first
write of each process. Two launches and run N-2 is gone. Several sessions launch concurrently in
this repo, so that is the normal case, not a race.

Measured 2026-08-31: an 11:09 launch destroyed the 5.4 MB `er-quickload-continue-trace.log`
belonging to the 09:07 run, whose evidence nobody had read. The launcher redirected the autoload
debug log and the crash log out of GAME_DIR and not the continue trace, so the trace fell back to
the shared path. One line of env, missing from one array.

There is a SECOND destroyer, and it is worse: a harness that runs `rm -f "$GAME_DIR"/er-quickload-*.log`
before launching deletes the previous run's live file AND -- because `begin_fresh_run` unconditionally
removes `<name>.prev` when the live file is absent -- the generation behind it. That drops two runs
at once, and it is another run's evidence, not the deleting run's.

WHY NOT COPY THE FILES OUT AFTER THE RUN
----------------------------------------
Because by teardown the damage is done: this run clobbered the previous one's file at LAUNCH, before
any copy could happen. A post-run copy preserves only your own output. It also never runs at all when
the run crashes or is killed -- which is exactly when the evidence matters most. Redirecting the
writer at launch, into a directory unique to the run, means two runs never share a path to begin with,
and a run that dies mid-write still leaves everything it wrote where it wrote it.

WHAT THIS SCRIPT CHECKS
-----------------------
The knob table is read out of the Rust sources, not restated here, so it cannot rot: every
`std::env::var[_os]("ER_QUICKLOAD_*_PATH")` that selects an output file is a knob a launcher must set.
Every script that launches the game is then required to set all of them, or to declare an exemption
in its own text with a reason:

    # er-artifact-redirect: exempt ER_QUICKLOAD_TELEMETRY_PATH -- <why>
    # er-artifact-redirect: delegates-to scripts/<other-launcher>.sh
    # er-artifact-redirect: library                     -- the caller owns the redirect
    # er-artifact-redirect: single-slot -- <why>        -- deliberately writes into GAME_DIR

An exemption is a STATED gap, which is the point: a run that does not preserve something must say so
rather than read as "we captured everything".

`single-slot` is the strongest form of that and the newest (2026-08-31). The shipped end-user
launcher generated by `build-user-release-package.py` sets no `ER_QUICKLOAD_*` on purpose, so a
user's logs land beside `eldenring.exe` under one predictable set of names. That was invisible
here -- the generator writes its `me3 launch` inside a heredoc string, so no launch shape matched
and it appeared in no report at all, which reads exactly like a clean tree. It is now discovered,
excluded from the "redirects everything" set, and printed on every successful run with its reason.

Usage:
    python3 scripts/er-artifact-redirect-audit.py              # audit; exit 1 on an undeclared gap
    python3 scripts/er-artifact-redirect-audit.py --table      # the inventory, one row per artifact
    python3 scripts/er-artifact-redirect-audit.py --selftest   # fixtures, incl. a two-run simulation
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CRATES = REPO_ROOT / "crates"
SCRIPTS = REPO_ROOT / "scripts"

EXIT_OK = 0
EXIT_GAP = 1
EXIT_BROKEN = 2

MARKER = "er-artifact-redirect:"

# Knobs that name an INPUT the DLL reads (a driver command channel, an autoload request), not an
# artifact it writes. A launcher is not required to redirect these; losing one loses nothing.
INPUT_CHANNEL_KNOBS = frozenset(
    {
        "ER_QUICKLOAD_COMMAND_PATH",
        "ER_QUICKLOAD_AUTOLOAD_PATH",
        "ER_QUICKLOAD_SAFE_INPUT_PATH",
        "ER_QUICKLOAD_GRSYSMSG_LOG",  # a 0/1 gate, not a path
    }
)

# Artifacts with NO env override: the writer resolves a fixed name against the game directory or the
# process CWD, so a launcher CANNOT move them and the next run destroys them. Each row names the
# source file and a literal that must still be present there, so this list goes red rather than
# quietly describing a crate that has moved on.
#
# EMPTY SINCE 2026-08-31. Every artifact is redirectable; each one that was not is frozen in
# `RECOVERED_KNOBS` below so the fix cannot be undone silently. No count is written here on
# purpose -- the list is the count, and a number in prose beside a list is a number that goes
# stale the next time somebody appends a row.
NO_KNOB_ARTIFACTS: tuple[tuple[str, str, str, str, int], ...] = ()

# The artifacts that had no knob until 2026-08-31, and the knob each must now resolve to.
#
# WHY THIS OUTLIVES THE FIX. Deleting the rows would make the audit shrink quietly if a knob were
# ever removed: the artifact would stop being demanded of launchers, every gap involving it would
# vanish from the report, and a file writing into the single-slot game directory would look like
# progress. Each pair is checked against the knobs parsed out of the Rust, so losing one is a
# failure rather than a smaller number. `er-reload-trace.log` is first because it is the largest
# producer in the repo (~655 MB/hour) and was the least movable.
RECOVERED_KNOBS: tuple[tuple[str, str], ...] = (
    ("er-reload-trace.log", "ER_QUICKLOAD_RELOAD_TRACE_PATH"),
    ("er-input-harness.log", "ER_QUICKLOAD_INPUT_HARNESS_LOG_PATH"),
    ("er-input-harness-phases.jsonl", "ER_QUICKLOAD_INPUT_HARNESS_PHASES_PATH"),
    ("er-diag-harness.log", "ER_QUICKLOAD_DIAG_HARNESS_PATH"),
    ("er-telemetry-timeseries.jsonl", "ER_QUICKLOAD_TIMESERIES_PATH"),
    # Found while wiring the five above: an undeclared artifact this inventory had never listed,
    # written with a bare `fs::write` so it kept ZERO previous generations.
    ("er-cpu-profile.txt", "ER_QUICKLOAD_CPU_PROFILE_PATH"),
    # The badge shell's log, added 2026-08-31 for the same reason and one worse: BOTH of its
    # launchers deleted it from the game directory before launching, which takes the `.prev` with
    # the live file -- two prior runs' evidence, neither of them the deleting run's.
    ("er-armament-icons.log", "ER_QUICKLOAD_ARMAMENT_ICONS_PATH"),
    # The standalone portrait shell's two files, the last artifacts in the repo with no knob. Both
    # resolved against the process CWD rather than even the game directory, so no launcher could
    # move them, and `run-portrait-dll-standalone-smoke.sh` `rm -f`'d BOTH before launching --
    # dropping the live file and the `.prev` behind it, two prior runs at once. They get one knob
    # EACH because that smoke reads them for different verdicts (attach/Present out of the run log,
    # "did anything fault" out of the crash log); a single shared knob would move whichever the
    # launcher named and leave the other where the next launch destroys it.
    ("er-loading-portrait.log", "ER_QUICKLOAD_LOADING_PORTRAIT_PATH"),
    ("er-loading-portrait-crash-log.txt", "ER_QUICKLOAD_LOADING_PORTRAIT_CRASH_LOG_PATH"),
    # The save-census shell's two files, and the last artifacts in the repo without a knob. The
    # telemetry is the one that matters: it is the RUN-STOPPING ORACLE of a save-suppression proof
    # (`escaped_write_sites` must be empty), and it publishes with a write-tmp-then-rename, so it
    # kept ZERO previous generations -- the last run's verdict was gone the instant this run
    # installed, with no `.prev` behind it. `run-save-census-probe.sh` `rm -f`'d BOTH out of the
    # game directory before launching, which also takes the `.prev` behind the live file. They get
    # one knob EACH because that probe reads them for different things (the text log for what the
    # DLL did, the JSON for the verdict); a single shared knob would move whichever the launcher
    # named and leave the other where the next launch destroys it.
    ("er-save-disable.log", "ER_QUICKLOAD_SAVE_DISABLE_LOG_PATH"),
    ("er-save-disable-telemetry.json", "ER_QUICKLOAD_SAVE_DISABLE_TELEMETRY_PATH"),
)

# Artifacts that a knob moves WITHOUT naming, because the writer derives their directory from
# another knob's parent. Recording this is the difference between "the portrait dumps are lost" and
# "the portrait dumps follow the autoload debug log", which is a 63 MB difference per run.
DERIVED_ARTIFACTS: tuple[tuple[str, str, str, str, int], ...] = (
    (
        "portrait-capture-slot*.bin",
        "crates/er-loading-portrait-core/src/dlstring_lookat_math.rs",
        "ER_QUICKLOAD_AUTOLOAD_DEBUG_PATH",
        "NONE -- bare fs::File::create, overwritten in place",
        0,
    ),
)

# A writer that opens with `fs::write` (or write-tmp-then-rename) keeps NO previous generation: the
# run before this one is gone the instant this one starts, with no `.prev` to fall back on.
NO_ROTATION_KNOB_ARTIFACTS = frozenset(
    {
        "er-quickload-telemetry.json",
        "er-quickload-bootstrap-state.json",
        # `er_telemetry_core::profiler::dump` -- a bare `fs::write`, so the previous run's CPU
        # profile is gone the instant this one dumps, with no `.prev` behind it.
        "er-cpu-profile.txt",
        # `er-save-disable/src/telemetry.rs` publishes to a per-serial tmp file and renames over
        # the target, so nothing is ever rotated aside. This is the run-stopping oracle of a
        # save-suppression proof, and it was the LEAST recoverable artifact in the table.
        "er-save-disable-telemetry.json",
    }
)


@dataclass(frozen=True)
class Knob:
    """An `ER_QUICKLOAD_*` env var that redirects one artifact, as read out of the Rust source."""

    env: str
    default_name: str
    source: str


@dataclass
class Launcher:
    path: Path
    sets: set[str] = field(default_factory=set)
    exempt: dict[str, str] = field(default_factory=dict)
    delegates_to: str | None = None
    # A sourced helper that runs the me3 command on a CALLER's behalf. It has no run of its own and
    # no artifact dir; the caller owns the redirect, and each caller is audited separately.
    is_library: bool = False
    # A launcher that DELIBERATELY leaves its artifacts single-slot in the game directory, with a
    # stated reason. Not the same as clean and not the same as a gap: see `SINGLE_SLOT` below.
    single_slot: str | None = None

    @property
    def name(self) -> str:
        return self.path.name


def _rust_sources() -> list[Path]:
    return sorted(
        path
        for path in CRATES.rglob("*.rs")
        if "target" not in path.parts and not path.name.startswith(".")
    )


ENV_LOOKUP = re.compile(r'env::var(?:_os)?\(\s*"(ER_QUICKLOAD_[A-Z0-9_]+)"')
# The fallback the resolver hands back when the env var is unset. Either a literal filename or a
# `const` naming one -- both forms are in the tree, and reading only the literal form picked up an
# unrelated string from a NEIGHBOURING function and reported it as a knob's default.
FALLBACK = re.compile(
    r'(?:join|PathBuf::from)\(\s*(?:"(?P<literal>[A-Za-z0-9._-]+\.(?:log|jsonl|json|txt|bin))"'
    r"|(?P<ident>[A-Z][A-Z0-9_]{3,}))\s*\)"
)
CONST_STR = r'const\s+{name}\s*:\s*&(?:\'static\s+)?str\s*=\s*"([^"]+)"'

# THE SECOND SHAPE, AND THE REASON THERE IS ONE. Five writers had no knob at all, and the obvious
# fix -- paste `input_trace_path()`'s six lines into each -- would have put five copies of the
# GAME_DIR fallback in five crates, which is the duplication `er_game_base::log` exists to end.
# They call the shared resolver instead, naming their own env var and default:
#
#     er_game_base::log::redirected_artifact_path("ER_QUICKLOAD_RELOAD_TRACE_PATH", LOG_PATH)
#
# It is also what keeps `er-reload-trace` inside `.auto/reload_trace_policy.rego`, which forbids
# that crate from reading the environment itself. The knob is still declared AT THE WRITER, so this
# parse still reads the table out of the code rather than out of a list someone must remember to
# update. A trailing comma is optional because rustfmt adds one whenever the call wraps.
SHARED_RESOLVER = re.compile(
    r'redirected_artifact_path\(\s*"(?P<env>ER_QUICKLOAD_[A-Z0-9_]+)"\s*,\s*'
    r'(?:"(?P<literal>[A-Za-z0-9._-]+\.(?:log|jsonl|json|txt|bin))"'
    r'|(?P<ident>[A-Z][A-Z0-9_]{3,}))\s*,?\s*\)'
)


def _resolver_body(text: str, start: int) -> str:
    """The rest of the function containing `start` -- up to the next column-0 `}`.

    Bounding the search to ONE function is the whole correctness of this parse. An unbounded window
    reads across into the next function's string literals: it is how `ER_QUICKLOAD_AUTOLOAD_DEBUG_PATH`
    came back with a default of `portrait-capture.bin`, which belongs to a different writer entirely.
    """
    end = text.find("\n}", start)
    return text[start : end if end >= 0 else start + 1200]


def _record(
    found: dict[str, Knob], env: str, name: str, relative: str
) -> None:
    existing = found.get(env)
    if existing is None:
        found[env] = Knob(env, name, relative)
    elif existing.default_name != name:
        # Two crates disagreeing on a knob's default is a real defect, not a display issue:
        # a launcher redirects one and the other silently keeps writing to GAME_DIR.
        raise SystemExit(
            f"{env} resolves to {existing.default_name!r} in {existing.source} but to "
            f"{name!r} in {relative}; one launcher redirect cannot satisfy both"
        )


def _const_value(text: str, ident: str) -> str | None:
    const = re.search(CONST_STR.format(name=re.escape(ident)), text)
    return const.group(1) if const else None


def discover_knobs() -> list[Knob]:
    """Every `ER_QUICKLOAD_*` env var the DLLs consult for an OUTPUT path, from the code itself."""
    found: dict[str, Knob] = {}
    for source in _rust_sources():
        text = source.read_text(encoding="utf-8", errors="replace")
        relative = str(source.relative_to(REPO_ROOT))
        for match in ENV_LOOKUP.finditer(text):
            env = match.group(1)
            if env in INPUT_CHANNEL_KNOBS or not env.endswith("_PATH"):
                continue
            fallback = FALLBACK.search(_resolver_body(text, match.end()))
            if fallback is None:
                continue
            name = fallback.group("literal")
            if name is None:
                name = _const_value(text, fallback.group("ident"))
                if name is None:
                    continue
            _record(found, env, name, relative)
        for match in SHARED_RESOLVER.finditer(text):
            env = match.group("env")
            if env in INPUT_CHANNEL_KNOBS or not env.endswith("_PATH"):
                continue
            name = match.group("literal") or _const_value(text, match.group("ident"))
            if name is None:
                continue
            _record(found, env, name, relative)
    return sorted(found.values(), key=lambda knob: knob.env)


# A LAUNCH IS A COMMAND, NOT A MENTION. Every shape below requires the me3 binary or the user
# launcher to appear as something the shell RUNS -- `"$ME3" ... launch`, `"$PRODUCT_LAUNCHER"`,
# `bash .../launch.sh`. Matching the bare words `launch -g eldenring` instead pulled in a usage
# comment in a release-staging script and a printed hint string in a read-only diagnostic, and a
# report padded with files that write nothing is how a real finding gets scrolled past.
#
# `\s` after the binary and around `launch` are load-bearing: without them `$ME3_PID` followed later
# on the line by `me3-launch.pid` reads as an me3 launch, and a pid-file write is not a run.
LAUNCH_SHAPES = (
    re.compile(r'"?\$\{?ME3(?:_BIN)?\}?"?\s[^\n]*\slaunch\s'),
    # The me3 subcommand with one of its own flags: catches the wrapped form where the binary sits
    # on an earlier line (`"$ME3" \` / `  --steam-dir ... launch \`).
    re.compile(r"\slaunch\s[^\n]*(?:--steam-dir|-g\s+eldenring)|--steam-dir[^\n]*\slaunch\s"),
    re.compile(r'"\$(?:PRODUCT_LAUNCHER|LAUNCHER)"'),
    re.compile(r"(?:bash|exec|sh)\s+[^\n]*launch\.sh"),
    # THE SHAPE THAT WAS MISSING. `scripts/me3-launch-lib.sh` exists so a caller does not have to
    # spell the me3 command itself, and the effect was that three real launchers -- run-golden-
    # observe.sh, run-portrait-dll-standalone-smoke.sh, smoke-save-picker-dll.sh -- ran the game
    # through `me3_launch "$PROFILE"` and were invisible to this audit entirely. Not "reported and
    # exempt": absent, which reads exactly like a clean tree. The trailing `["'$]` is what keeps the
    # library's own `me3_launch() {` definition from matching its own helper.
    re.compile(r"^\s*me3_launch\s+[\"'$]"),
)
# THE SHELLS THAT WRITE A KNOBBED ARTIFACT. A launcher that loads none of them is not asked to
# redirect anything: demanding it from a vanilla trace run or a release-staging script produces a
# wall of findings about files those runs never create, and a wall of irrelevant findings is how a
# real one gets skipped.
#
# It was `er_quickload.dll` alone until 2026-08-31, which was correct only while the product was the
# only shell with redirect knobs. Giving the reload trace, both input-harness files, the diag harness
# and the telemetry timeseries their own knobs made four MORE shells artifact writers, and
# `run-armament-icons-smoke.sh` -- which loads the harness and telemetry DLLs and never mentions the
# product -- was invisible to this audit until the list grew with them.
ARTIFACT_WRITING_SHELLS = (
    "er_quickload.dll",
    "ER_QUICKLOAD_",
    "er_reload_trace.dll",
    "er_input_harness.dll",
    "er_telemetry.dll",
    "er_diag_harness.dll",
)

# A `#` comment only TALKS about a launch.
NOT_A_COMMAND = re.compile(r"^\s*(?:#|//)")

# ...and so does a HEREDOC BODY, which is data the script prints, not a command it runs.
# `stage-autoload-release.sh` stages a release payload and launches nothing; it was reported for
# all fourteen knobs because its `usage()` heredoc prints the line
#
#     me3 launch -g eldenring -p /path/to/er-quickload.me3
#
# for the human reading `--help`. Fourteen findings about a script that writes no artifact is the
# padding this file's own comment warns about: it is how a real finding gets scrolled past.
#
# Only LAUNCH DETECTION strips heredocs. `read_launcher` still reads the whole text for env
# assignments, because a script that GENERATES a launcher writes that launcher's redirect lines
# inside a heredoc, and those are real.
HEREDOC_START = re.compile(r"<<-?\s*(?P<quote>['\"]?)(?P<tag>[A-Za-z_][A-Za-z0-9_]*)(?P=quote)")


def strip_heredoc_bodies(text: str) -> str:
    """`text` with every heredoc BODY blanked, terminators and all other lines kept."""
    out: list[str] = []
    terminator: str | None = None
    for line in text.splitlines():
        if terminator is not None:
            out.append("")
            if line.strip() == terminator:
                terminator = None
            continue
        out.append(line)
        if not NOT_A_COMMAND.match(line):
            start = HEREDOC_START.search(line)
            if start:
                terminator = start.group("tag")
    return "\n".join(out)

# Python launchers do not match the shell shapes: they spawn the launcher through `subprocess`, and
# its path is a STRING LITERAL (`Path.home() / "Elden" / "launch.sh"`), so neither stripping string
# literals nor keeping them classifies these correctly by regex. Ask the syntax tree instead: a
# `subprocess` call whose arguments name the launcher IS the launch, and a docstring that mentions
# `~/Elden/launch.sh` is not.
SUBPROCESS_CALL = re.compile(r"^subprocess\.(?:Popen|run|call|check_call|check_output)$")
LAUNCH_TARGET = re.compile(r"\bLAUNCHER\b|launch\.sh|\bME3_BIN\b")


def _python_launches(path: Path, text: str) -> bool:
    import ast

    try:
        tree = ast.parse(text)
    except SyntaxError:
        return False
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        target = ast.unparse(node.func) if hasattr(ast, "unparse") else ""
        if not SUBPROCESS_CALL.match(target):
            continue
        for arg in node.args:
            if LAUNCH_TARGET.search(ast.unparse(arg)):
                return True
    return False


def is_launcher(text: str, path: Path | None = None) -> bool:
    """Does this script start a run that WRITES these artifacts?

    Two conditions, both required, because either alone is wrong. It must start the game -- matched
    on the launch command, never on a filename, since a name rule ("anything called run-*.sh") both
    misses launchers and drags in readers. And it must load `er_quickload.dll`, because only that
    shell writes the artifacts these knobs move: demanding a redirect from a vanilla trace run or a
    release-staging script produces a wall of findings about files those runs never create, and a
    wall of irrelevant findings is how a real one gets skipped.

    A script carrying either marker opts in regardless -- that is how a launcher whose shape this
    misses declares itself rather than staying invisible.
    """
    if MARKER in text:
        return True
    if path is not None and path.suffix == ".py":
        launches = _python_launches(path, text)
    else:
        launches = any(
            shape.search(line)
            for line in strip_heredoc_bodies(text).splitlines()
            if not NOT_A_COMMAND.match(line)
            for shape in LAUNCH_SHAPES
        )
    if not launches:
        return False
    return any(shell in text for shell in ARTIFACT_WRITING_SHELLS)


# THE SHARED PYTHON TABLE. Five Python launchers would otherwise each carry their own copy of a
# fourteen-line env dict, and the bug that started all of this WAS a table with one line missing --
# copying it five more times sets the same trap five more times. A launcher that uses
# `scripts/er_artifact_env.py` gets credit for every knob in it, and `verify_shared_table` below
# requires that table to cover every knob the DLLs honour, so the credit can never exceed the truth.
SHARED_ENV_TABLE = SCRIPTS / "er_artifact_env.py"
SHARED_TABLE_USE = re.compile(r"\ber_artifact_env\b|\bartifact_env\s*\(")


def shared_table_knobs() -> set[str]:
    """The env vars `scripts/er_artifact_env.py` redirects, read out of that file."""
    if not SHARED_ENV_TABLE.is_file():
        return set()
    text = SHARED_ENV_TABLE.read_text(encoding="utf-8", errors="replace")
    body = re.search(r"ARTIFACT_ENV: dict\[str, str\] = \{(.*?)\n\}", text, re.S)
    if body is None:
        return set()
    return set(re.findall(r'"(ER_QUICKLOAD_[A-Z0-9_]+)"\s*:', body.group(1)))


def verify_shared_table(knobs: list[Knob]) -> list[str]:
    """The shared table must cover every knob, or a launcher using it is silently short."""
    if not SHARED_ENV_TABLE.is_file():
        return []
    missing = sorted({knob.env for knob in knobs} - shared_table_knobs())
    return [
        f"{SHARED_ENV_TABLE.name}: does not redirect {env}. Every launcher that uses this table "
        f"is credited with it, so a knob missing HERE is missing from all of them at once."
        for env in missing
    ]


def read_launcher(path: Path) -> Launcher:
    text = path.read_text(encoding="utf-8", errors="replace")
    launcher = Launcher(path=path)
    if path.suffix == ".py" and SHARED_TABLE_USE.search(text):
        launcher.sets |= shared_table_knobs()
    # A knob counts as SET when it is assigned in a shell env (`X=...`), named as a Python mapping
    # key (`"X": ...`), or exported into a PowerShell env (`$env:X = ...`). Comment lines are
    # excluded: a script that only DISCUSSES a knob has not redirected anything.
    commands = "\n".join(
        line for line in text.splitlines() if not NOT_A_COMMAND.match(line)
    )
    for match in re.finditer(r"(ER_QUICKLOAD_[A-Z0-9_]+)[\"']?\s*[:=]", commands):
        launcher.sets.add(match.group(1))
    # PowerShell half of a generated launcher: `$env:ER_QUICKLOAD_X = ...`
    for match in re.finditer(r"\$env:(ER_QUICKLOAD_[A-Z0-9_]+)", commands):
        launcher.sets.add(match.group(1))
    for match in re.finditer(
        rf"{re.escape(MARKER)}\s*exempt\s+(ER_QUICKLOAD_[A-Z0-9_]+)\s*--\s*(.+)", text
    ):
        launcher.exempt[match.group(1)] = match.group(2).strip()
    delegate = re.search(rf"{re.escape(MARKER)}\s*delegates-to\s+(\S+)", text)
    if delegate:
        launcher.delegates_to = delegate.group(1)
    launcher.is_library = bool(re.search(rf"{re.escape(MARKER)}\s*library\b", text))
    single_slot = re.search(rf"{re.escape(MARKER)}\s*single-slot\s*--\s*(.+)", text)
    if single_slot:
        launcher.single_slot = single_slot.group(1).strip()
    return launcher


def discover_launchers() -> list[Launcher]:
    launchers = []
    for path in sorted(SCRIPTS.glob("*.sh")) + sorted(SCRIPTS.glob("*.py")):
        if path.name == Path(__file__).name:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if is_launcher(text, path):
            launchers.append(read_launcher(path))
    return launchers


def audit(knobs: list[Knob], launchers: list[Launcher]) -> list[str]:
    """Undeclared gaps, one line each. A declared exemption is reported by `--table`, not here."""
    wanted = {knob.env for knob in knobs}
    problems = []
    for launcher in launchers:
        if launcher.is_library or launcher.single_slot:
            continue
        if launcher.delegates_to:
            target = REPO_ROOT / launcher.delegates_to
            if not target.is_file():
                problems.append(
                    f"{launcher.name}: delegates-to names a file that does not exist "
                    f"({launcher.delegates_to})"
                )
            continue
        missing = sorted(wanted - launcher.sets - set(launcher.exempt))
        for env in missing:
            problems.append(
                f"{launcher.name}: does not redirect {env}; that artifact stays in GAME_DIR, "
                f"where the next launch destroys it. Set it to a path inside this run's artifact "
                f"dir, or declare `# {MARKER} exempt {env} -- <reason>`."
            )
    return problems


def inventory_rows(knobs: list[Knob]) -> list[tuple[str, str, str, str, str]]:
    """(artifact, writer, redirect knob, rotation, generations kept in GAME_DIR)."""
    rows = []
    for knob in knobs:
        rotation = (
            "NONE -- fs::write, overwritten in place"
            if knob.default_name in NO_ROTATION_KNOB_ARTIFACTS
            else ".prev (er_game_base::log::begin_fresh_run)"
        )
        kept = "0" if knob.default_name in NO_ROTATION_KNOB_ARTIFACTS else "1"
        rows.append((knob.default_name, knob.source, knob.env, rotation, kept))
    for artifact, source, literal, rotation, kept in NO_KNOB_ARTIFACTS:
        rows.append((artifact, source, "(none -- needs a DLL knob)", rotation, str(kept)))
    for artifact, source, via, rotation, kept in DERIVED_ARTIFACTS:
        rows.append((artifact, source, f"(follows {via})", rotation, str(kept)))
    return sorted(rows)


def verify_recovered_knobs(knobs: list[Knob]) -> list[str]:
    """The artifacts that used to be unmovable must still have their knob.

    Positive control on the fix itself. Without it, deleting a resolver would REDUCE the reported
    gap count -- the artifact stops being demanded of launchers, its rows drop out of the report --
    and a file writing back into the single-slot game directory would read as progress.
    """
    by_name = {knob.default_name: knob.env for knob in knobs}
    problems = []
    for artifact, env in RECOVERED_KNOBS:
        actual = by_name.get(artifact)
        if actual is None:
            problems.append(
                f"{artifact}: no redirect knob is discoverable in the Rust sources any more. It "
                f"used to be {env}. That artifact is back in the single-slot game directory, "
                f"where the next launch destroys it."
            )
        elif actual != env:
            problems.append(
                f"{artifact}: is redirected by {actual}, not {env}. Renaming a knob breaks every "
                f"launcher that sets the old name, silently and without an error."
            )
    return problems


def verify_no_knob_table() -> list[str]:
    """The hand-written rows must still describe the code. A stale row is a lie in the deliverable."""
    problems = []
    for artifact, source, literal, _rotation, _kept in NO_KNOB_ARTIFACTS:
        path = REPO_ROOT / source
        if not path.is_file():
            problems.append(f"{artifact}: writer source is gone ({source})")
            continue
        if literal not in path.read_text(encoding="utf-8", errors="replace"):
            problems.append(
                f"{artifact}: {source} no longer contains {literal!r}; this row may be stale "
                f"(the artifact may have been renamed, moved, or given an env knob)"
            )
    for artifact, source, via, _rotation, _kept in DERIVED_ARTIFACTS:
        path = REPO_ROOT / source
        if not path.is_file() or via not in path.read_text(encoding="utf-8", errors="replace"):
            problems.append(f"{artifact}: {source} no longer derives its directory from {via}")
    return problems


# --------------------------------------------------------------------------------------------
# The writer's rotation, modelled, so two consecutive runs can be simulated without a game.
# --------------------------------------------------------------------------------------------

PREVIOUS_RUN_SUFFIX = ".prev"


def begin_fresh_run(path: Path) -> None:
    """A Python model of `er_game_base::log::begin_fresh_run`, called once per (process, path).

    Kept honest by `check_model_matches_rust()`: if the Rust stops removing the stale `.prev`
    unconditionally, or stops renaming, the selftest goes red instead of simulating fiction.
    """
    previous = path.with_name(path.name + PREVIOUS_RUN_SUFFIX)
    previous.unlink(missing_ok=True)
    if path.exists():
        path.rename(previous)
    path.write_text("build git=<identity line>\n", encoding="utf-8")


def check_model_matches_rust() -> list[str]:
    source = REPO_ROOT / "crates/er-game-base/src/log.rs"
    text = source.read_text(encoding="utf-8", errors="replace")
    problems = []
    for needed in (
        'pub const PREVIOUS_RUN_SUFFIX: &str = ".prev";',
        "let _ = fs::remove_file(&previous);",
        "let _ = fs::rename(path, &previous);",
        ".truncate(true)",
    ):
        if needed not in text:
            problems.append(
                f"er-game-base/src/log.rs no longer contains {needed!r}; the rotation model in "
                f"this script is simulating behaviour the writer does not have"
            )
    return problems


def simulate_run(
    game_dir: Path,
    artifact_dir: Path | None,
    lines: str,
    names: tuple[str, ...] = ("er-quickload-continue-trace.log",),
) -> None:
    """One launch. `artifact_dir=None` is the unredirected case: the artifact lands in GAME_DIR.

    `names` defaults to the one file the reported bug was about; pass every knob's default name to
    model a whole run's evidence rather than a single log.
    """
    target_dir = artifact_dir if artifact_dir is not None else game_dir
    target_dir.mkdir(parents=True, exist_ok=True)
    for name in names:
        path = target_dir / name
        begin_fresh_run(path)
        with path.open("a", encoding="utf-8") as handle:
            handle.write(lines)


def selftest() -> int:
    import tempfile

    ok = True

    def check(condition: bool, label: str) -> None:
        nonlocal ok
        if not condition:
            ok = False
        print(("  ok   " if condition else "  FAIL ") + label)

    check(not check_model_matches_rust(), "the rotation model still matches er-game-base's writer")
    for problem in check_model_matches_rust():
        print("         " + problem)

    stale = verify_no_knob_table()
    check(not stale, "every hand-written inventory row still describes the code")
    for problem in stale:
        print("         " + problem)

    knobs = discover_knobs()
    envs = {knob.env for knob in knobs}

    shared = verify_shared_table(knobs)
    check(not shared, "the shared Python env table redirects every knob the DLLs honour")
    for problem in shared:
        print("         " + problem)
    check(
        len(shared_table_knobs()) == len(knobs),
        f"the shared table is parsed and complete ({len(shared_table_knobs())} of {len(knobs)})",
    )

    recovered = verify_recovered_knobs(knobs)
    check(
        not recovered,
        f"the {len(RECOVERED_KNOBS)} artifacts that had no knob are still redirectable",
    )
    for problem in recovered:
        print("         " + problem)
    # NON-VACUITY. The check above must be capable of failing, or it is decoration on the one fact
    # this whole task turned on. Drop a knob and it must go red.
    check(
        len(verify_recovered_knobs([k for k in knobs if k.default_name != "er-reload-trace.log"]))
        == 1,
        "losing a recovered knob is a FAILURE, not a smaller gap count",
    )
    # Non-vacuity: the parse must find the knobs this bug was actually about. A regex that silently
    # stops matching would otherwise report a clean tree over a broken one.
    check(len(knobs) >= 6, f"the knob table is parsed out of the Rust sources ({len(knobs)} found)")
    for expected in (
        "ER_QUICKLOAD_TRACE_CONTINUE_PATH",
        "ER_QUICKLOAD_AUTOLOAD_DEBUG_PATH",
        "ER_QUICKLOAD_INPUT_TRACE_PATH",
        "ER_QUICKLOAD_TELEMETRY_PATH",
    ):
        check(expected in envs, f"{expected} is discovered from the code")
    check(
        "ER_QUICKLOAD_COMMAND_PATH" not in envs,
        "an INPUT channel is not demanded of launchers as if it were evidence",
    )
    by_env = {knob.env: knob for knob in knobs}
    check(
        by_env["ER_QUICKLOAD_TRACE_CONTINUE_PATH"].default_name
        == "er-quickload-continue-trace.log",
        "the knob's GAME_DIR default filename is read from its own resolver",
    )

    launchers = discover_launchers()
    names = {launcher.name for launcher in launchers}
    check(len(launchers) >= 8, f"launchers are discovered by their launch command ({len(launchers)})")
    for expected in (
        "run-samechar-3x-threedll.sh",
        "run-me3-product-smoke.sh",
        "run-product-continue-direct-probe.sh",
        "er-smoke-driver.sh",
    ):
        check(expected in names, f"{expected} is recognised as a launcher")
    check(
        "er-artifact-redirect-audit.py" not in names,
        "the audit does not audit itself",
    )

    # A launcher missing a knob must be REPORTED, and the same launcher with an exemption must not.
    synthetic = Launcher(path=Path("synthetic.sh"), sets=set())
    check(
        len(audit(knobs, [synthetic])) == len(knobs),
        "a launcher that redirects nothing is reported once per knob",
    )
    synthetic_exempt = Launcher(
        path=Path("synthetic.sh"),
        sets=set(),
        exempt={knob.env: "stated reason" for knob in knobs},
    )
    check(
        audit(knobs, [synthetic_exempt]) == [],
        "a STATED exemption silences the gap (it is declared, not hidden)",
    )
    synthetic_full = Launcher(path=Path("synthetic.sh"), sets=set(envs))
    check(audit(knobs, [synthetic_full]) == [], "a launcher that redirects everything is clean")
    bad_delegate = Launcher(path=Path("synthetic.sh"), delegates_to="scripts/does-not-exist.sh")
    check(
        len(audit(knobs, [bad_delegate])) == 1,
        "a delegates-to pointing at nothing is a failure, not a free pass",
    )

    # THE SWEPT LAUNCHERS MUST STAY SWEPT. Frozen by name, because a regression here is silent:
    # dropping one env line puts that artifact back in the single-slot game directory and nothing
    # else in the repo notices.
    clean = {
        launcher.name
        for launcher in launchers
        if not launcher.is_library
        and not launcher.delegates_to
        and not launcher.single_slot
        and not (set(envs) - launcher.sets - set(launcher.exempt))
    }
    for expected in (
        "er-run-branch.py",
        "capture-er-frame.sh",
        "er-smoke-driver.sh",
        "run-me3-product-smoke.sh",
        "run-product-continue-direct-probe.sh",
        "run-windows-proof-render-smoke.sh",
        # Added with the two loading-portrait knobs (2026-08-31): the smoke that reads them is the
        # one launcher whose PASS bar depends on finding those exact two files.
        "run-portrait-dll-standalone-smoke.sh",
        # Twenty-plus launches in one `--all` sweep, each of which used to write over the last.
        "sweep-dll-1170-runtime.py",
    ):
        check(expected in clean, f"{expected} still redirects every artifact out of GAME_DIR")

    # THE STATED SINGLE-SLOT LAUNCHER. The shipped end-user helper deliberately redirects nothing,
    # and until 2026-08-31 that was INVISIBLE here -- the generator writes its `me3 launch` inside
    # a heredoc string, so no launch shape matched and it appeared in no report at all. Absence
    # reads as compliance. It is now a declared exemption with a reason, which is a different thing
    # from clean and must keep printing as such.
    by_name = {launcher.name: launcher for launcher in launchers}
    shipped = by_name.get("build-user-release-package.py")
    check(shipped is not None, "the shipped end-user launcher generator is discovered at all")
    check(
        shipped is not None and bool(shipped.single_slot) and len(shipped.single_slot) > 40,
        "it declares single-slot WITH a reason, not a bare marker",
    )
    check(
        shipped is not None and shipped.name not in clean,
        "a stated single-slot launcher is NOT counted among the ones that redirect everything",
    )
    # Non-vacuity: the exemption must silence the gap it declares, and only for the declarer.
    stated = Launcher(path=Path("synthetic.sh"), single_slot="stated reason")
    undeclared = Launcher(path=Path("synthetic-2.sh"))
    check(
        audit(knobs, [stated]) == [] and gap_keys(knobs, [stated]) == [],
        "a stated single-slot launcher raises no gap",
    )
    check(
        len(gap_keys(knobs, [undeclared])) == len(knobs),
        "...and an UNSTATED one still raises one per knob, so the marker is what does the work",
    )

    # THE BACKLOG IS EMPTY, AND THAT HAS TO BE PROVEN RATHER THAN ASSUMED. It held 98 rows across
    # 13 launchers until 2026-08-31. A baseline that silently absorbed everything would turn this
    # audit into a no-op, so an empty file is only acceptable while the STRICT audit -- the one that
    # ignores the baseline entirely -- also comes back with nothing.
    recorded = read_baseline()
    live_gaps = gap_keys(knobs, launchers)
    check(
        not recorded and not live_gaps,
        f"no launcher leaks an artifact into GAME_DIR ({len(live_gaps)} live gap(s), "
        f"{len(recorded)} recorded)",
    )
    for key in sorted(live_gaps)[:20]:
        print("         " + key)
    check(
        all(row.split()[0] not in clean for row in recorded),
        "no launcher is both baselined and clean -- a stale row would hide a real regression",
    )
    check(
        "synthetic-new-launcher.sh ER_QUICKLOAD_TELEMETRY_PATH" not in recorded
        and bool(
            [
                key
                for key in gap_keys(
                    knobs, [Launcher(path=Path("synthetic-new-launcher.sh"))]
                )
                if key not in recorded
            ]
        ),
        "a launcher that is not in the baseline still produces NEW gaps, so drift fails",
    )

    # ---------------------------------------------------------------------------------------
    # TWO CONSECUTIVE RUNS. The whole point, reduced to something that needs no game.
    # ---------------------------------------------------------------------------------------
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        game_dir = root / "Game"
        game_dir.mkdir()

        # (a) UNREDIRECTED, the bug. Run 1 writes into GAME_DIR; run 2 rotates it to `.prev`;
        #     run 3 destroys it outright.
        simulate_run(game_dir, None, "RUN-1 EVIDENCE\n")
        simulate_run(game_dir, None, "RUN-2 EVIDENCE\n")
        live = (game_dir / "er-quickload-continue-trace.log").read_text(encoding="utf-8")
        prev = (game_dir / "er-quickload-continue-trace.log.prev").read_text(encoding="utf-8")
        check("RUN-2 EVIDENCE" in live, "unredirected: run 2's evidence is the live file")
        check("RUN-1 EVIDENCE" in prev, "unredirected: run 1 survives ONE run, as `.prev`")
        simulate_run(game_dir, None, "RUN-3 EVIDENCE\n")
        prev = (game_dir / "er-quickload-continue-trace.log.prev").read_text(encoding="utf-8")
        check(
            "RUN-1 EVIDENCE" not in prev and "RUN-2 EVIDENCE" in prev,
            "unredirected: run 1 is GONE after the second following launch -- the reported bug",
        )

        # (b) THE HARNESS `rm -f`, which is worse: it drops TWO generations at once, because
        #     `begin_fresh_run` removes a stale `.prev` when the live file is absent.
        (game_dir / "er-quickload-continue-trace.log").unlink()
        simulate_run(game_dir, None, "RUN-4 EVIDENCE\n")
        check(
            not (game_dir / "er-quickload-continue-trace.log.prev").exists(),
            "a pre-launch `rm -f` of the live file destroys the surviving `.prev` too",
        )

        # (c) REDIRECTED, the fix. Two runs, two directories, nothing shared, nothing lost.
        run_one = root / "artifacts" / "run-1"
        run_two = root / "artifacts" / "run-2"
        simulate_run(game_dir, run_one, "RUN-1 EVIDENCE\n")
        simulate_run(game_dir, run_two, "RUN-2 EVIDENCE\n")
        first = (run_one / "er-quickload-continue-trace.log").read_text(encoding="utf-8")
        second = (run_two / "er-quickload-continue-trace.log").read_text(encoding="utf-8")
        check(
            "RUN-1 EVIDENCE" in first and "RUN-2 EVIDENCE" in second,
            "redirected: BOTH runs' evidence is readable after the second run",
        )
        check(
            not (run_one / "er-quickload-continue-trace.log.prev").exists(),
            "redirected: run 1's file was never rotated, because run 2 never touched its path",
        )

        # (d) A CRASHED OR KILLED RUN. Nothing runs at teardown -- no copy, no reaper, no trap.
        #     Redirected, everything written before the crash is already in the right place.
        run_three = root / "artifacts" / "run-3"
        simulate_run(game_dir, run_three, "RUN-3 PARTIAL EVIDENCE, then SIGKILL\n")
        # ...and the next run starts, with no cleanup of any kind having happened.
        run_four = root / "artifacts" / "run-4"
        simulate_run(game_dir, run_four, "RUN-4 EVIDENCE\n")
        crashed = (run_three / "er-quickload-continue-trace.log").read_text(encoding="utf-8")
        check(
            "RUN-3 PARTIAL EVIDENCE" in crashed,
            "a crashed run's partial evidence survives the next launch with no teardown step",
        )

        # (e) THE WHOLE INVENTORY, NOT ONE LOG. The counter this task is scored on is "how many of
        #     a run's artifacts can the NEXT launch destroy", and the answer has to be zero for
        #     every row of the table, not for the one file the original bug happened to be about.
        #     Three launches -- two normal, one killed mid-write with no teardown of any kind --
        #     and then every artifact of all three is read back.
        every = tuple(knob.default_name for knob in knobs)
        first, second, killed = (root / "all" / part for part in ("run-1", "run-2", "run-3"))
        simulate_run(game_dir, first, "RUN-1 EVIDENCE\n", every)
        simulate_run(game_dir, second, "RUN-2 EVIDENCE\n", every)
        simulate_run(game_dir, killed, "RUN-3 PARTIAL, then SIGKILL\n", every)
        # ...and a fourth launch starts on top of all of it, having cleaned up nothing.
        simulate_run(game_dir, root / "all" / "run-4", "RUN-4 EVIDENCE\n", every)
        destroyed = [
            f"{directory.name}/{name}"
            for directory, marker in (
                (first, "RUN-1 EVIDENCE"),
                (second, "RUN-2 EVIDENCE"),
                (killed, "RUN-3 PARTIAL"),
            )
            for name in every
            if marker not in (directory / name).read_text(encoding="utf-8")
        ]
        check(
            not destroyed,
            f"all {len(every)} artifacts of THREE prior runs (one of them killed) are still "
            f"readable after a fourth launch -- {len(destroyed)} destroyable",
        )
        for entry in destroyed[:10]:
            print("         destroyed: " + entry)
        # Non-vacuity, on the exact pairs the last two sessions added: the same three launches
        # UNREDIRECTED must lose them, or the check above is proving nothing. Each pair is named
        # rather than folded into one loop over `every`, because these are the artifacts whose
        # knobs are newest and therefore the ones a careless revert would take back out.
        for label, pair in (
            (
                "the portrait pair",
                ("er-loading-portrait.log", "er-loading-portrait-crash-log.txt"),
            ),
            (
                "the save-census pair",
                ("er-save-disable.log", "er-save-disable-telemetry.json"),
            ),
        ):
            for marker in ("RUN-1 EVIDENCE", "RUN-2 EVIDENCE", "RUN-3 EVIDENCE"):
                simulate_run(game_dir, None, marker + "\n", pair)
            check(
                all(
                    "RUN-1 EVIDENCE"
                    not in (game_dir / name).read_text(encoding="utf-8")
                    and "RUN-1 EVIDENCE"
                    not in (game_dir / (name + PREVIOUS_RUN_SUFFIX)).read_text(encoding="utf-8")
                    for name in pair
                ),
                f"...and UNREDIRECTED, {label} loses run 1 after two more launches",
            )

    # ---------------------------------------------------------------------------------------
    # THE READER HALF, WHICH THE REDIRECT MAKES DANGEROUS.
    #
    # Once nothing deletes the game-directory copy, it sits there complete and readable -- the
    # PREVIOUS run's file. A monitor that resolves by existence at t=0 binds to it, counts its
    # lines, and scores a finished run as this one's; and because a stale file's mtime never
    # changes, a freshness check downstream then calls a perfectly healthy game frozen. Measured
    # 2026-08-31: a watcher did exactly this, declared world-stable at elapsed 0.0 s and tore down
    # a game that had not finished booting. So the mtime floor is not a refinement, it is the
    # other half of the fix, and it is exercised here in all four states a reader can meet.
    #
    # `run-save-census-probe.sh resolve` is the SHELL path, not a re-implementation of the Python
    # one: the launcher passes its redirects with an `env VAR=... me3` prefix, which never enters
    # the launcher's own environment, so its reader has to be handed the run directory explicitly.
    # Driving the real subcommand is what proves that wiring, quoting and argument order included.
    # ---------------------------------------------------------------------------------------
    import os
    import subprocess

    # The shared table lives beside this script; `sys.path[0]` already points there when it is run
    # as a script, but say so explicitly so the selftest survives being imported from elsewhere.
    if str(SCRIPTS) not in sys.path:
        sys.path.insert(0, str(SCRIPTS))
    from er_artifact_env import resolve_artifact

    probe = SCRIPTS / "run-save-census-probe.sh"
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        game_dir, run_dir = root / "Game", root / "run-1"
        game_dir.mkdir()
        run_dir.mkdir()
        launch = 1_000_000.0
        stale, fresh = launch - 600, launch + 1

        def write(path: Path, body: str, mtime: float) -> Path:
            path.write_text(body, encoding="utf-8")
            os.utime(path, (mtime, mtime))
            return path

        def resolved(name: str) -> str:
            out = subprocess.run(
                ["bash", str(probe), "resolve", name, str(game_dir), str(run_dir), str(launch)],
                capture_output=True,
                text=True,
                check=False,
                timeout=30,
            )
            return out.stdout.strip()

        name = "er-save-disable-telemetry.json"
        # (1) REDIRECT PENDING. The DLL has not written yet. The honest answer is the run
        #     directory's not-yet-existing path: the caller reads nothing and waits.
        check(
            resolved(name) == str(run_dir / name),
            "reader, redirect pending: resolves to this run's path, which does not exist yet",
        )
        # (2) STALE ONLY. The game directory holds the previous run's file and nothing else.
        #     Returning it would score an ended run as this one -- the measured teardown bug.
        write(game_dir / name, '{"escaped_write_site_count": 3}\n', stale)
        check(
            resolved(name) == str(run_dir / name),
            "reader, stale only: the PREVIOUS run's game-directory file is refused, not read",
        )
        # (3) ENV LOST. The redirect did not survive me3 -> Proton, so the DLL fell back to the
        #     game directory -- and that file is THIS run's, by its mtime. Ignoring it would
        #     report a healthy run as silent, which reads exactly like a broken feature.
        write(game_dir / name, '{"escaped_write_site_count": 0}\n', fresh)
        check(
            resolved(name) == str(game_dir / name),
            "reader, env-lost fallback: a game-directory file newer than the launch IS this run's",
        )
        # (4) REDIRECT LIVE. Once the run directory has it, it wins outright.
        write(run_dir / name, '{"escaped_write_site_count": 0}\n', fresh)
        check(
            resolved(name) == str(run_dir / name),
            "reader, redirect live: the run directory wins over the game directory",
        )
        # NON-VACUITY on the floor itself: drop `newer_than` and state (2) silently returns the
        # previous run's verdict. That is the whole bug, so the check must be able to fail.
        (run_dir / name).unlink()
        write(game_dir / name, '{"escaped_write_site_count": 3}\n', stale)
        check(
            resolve_artifact(name, game_dir, prefer=run_dir) == game_dir / name
            and resolve_artifact(name, game_dir, prefer=run_dir, newer_than=launch)
            == run_dir / name,
            "...and WITHOUT the mtime floor the same call returns the previous run's file",
        )

    print("selftest:", "PASS" if ok else "FAIL")
    return EXIT_OK if ok else EXIT_GAP


def print_table(knobs: list[Knob], launchers: list[Launcher]) -> None:
    rows = inventory_rows(knobs)
    width = max(len(row[0]) for row in rows)
    # Measured, not guessed: a fixed width silently ragged the table the moment a knob name grew
    # past it, and a report whose columns do not line up gets skimmed instead of read.
    knob_width = max(len("redirect knob"), max(len(row[2]) for row in rows))
    print("PER-RUN ARTIFACTS -- what a run writes, and what happens to the run before it")
    print()
    print(f"  {'artifact'.ljust(width)}  {'redirect knob'.ljust(knob_width)}  kept in GAME_DIR  rotation")
    print(f"  {'-' * width}  {'-' * knob_width}  ----------------  --------")
    for artifact, _source, knob, rotation, kept in rows:
        print(f"  {artifact.ljust(width)}  {knob.ljust(knob_width)}  {kept:^16}  {rotation}")
    print()
    print("  'kept in GAME_DIR' is how many PREVIOUS runs survive there: 1 means `<name>.prev`")
    print("  holds the run immediately before the live file and nothing older; 0 means the")
    print("  previous run is gone the moment this one starts. A harness `rm -f` of the live file")
    print("  before launch takes the `.prev` with it, so both numbers become 0.")
    print()
    print("LAUNCHERS")
    print()
    wanted = {knob.env for knob in knobs}
    for launcher in sorted(launchers, key=lambda item: item.name):
        if launcher.is_library:
            print(f"  {launcher.name}: library -- the caller owns the redirect")
            continue
        if launcher.single_slot:
            print(f"  {launcher.name}: SINGLE-SLOT BY DESIGN -- {launcher.single_slot}")
            print(f"      all {len(wanted)} artifacts stay beside eldenring.exe; the run before")
            print("      last is gone. Stated, not fixed.")
            continue
        if launcher.delegates_to:
            print(f"  {launcher.name}: delegates to {launcher.delegates_to}")
            continue
        missing = sorted(wanted - launcher.sets - set(launcher.exempt))
        state = "redirects everything" if not missing else f"MISSING {len(missing)}"
        print(f"  {launcher.name}: {state}")
        for env in missing:
            print(f"      missing  {env}")
        for env, reason in sorted(launcher.exempt.items()):
            print(f"      exempt   {env} -- {reason}")


BASELINE = SCRIPTS / "er-artifact-redirect-audit.baseline.txt"

BASELINE_HEADER = """\
# LAUNCHERS THAT STILL LEAK A PER-RUN ARTIFACT INTO THE GAME DIRECTORY.
#
# This is a TO-DO LIST, not an approval. Every line is a run whose evidence the NEXT launch can
# destroy -- a game-directory artifact is single-slot, and two launches lose the run before last.
# It exists so the audit can fail on NEW drift while the known backlog stays written down and
# counted instead of silently tolerated.
#
# To clear a line: set that env var, in that launcher, to a path inside the run's own artifact
# directory, then delete the line (or re-run with --write-baseline).
#
# One `<launcher> <ENV_VAR>` per line. Regenerate with:
#     python3 scripts/er-artifact-redirect-audit.py --write-baseline
#
# EMPTY SINCE 2026-08-31 -- 98 rows across 13 launchers, all closed. An empty file is not the same
# as no gate: `--selftest` requires the STRICT audit (which ignores this file entirely) to agree
# that nothing leaks, so emptiness has to be earned rather than assumed.
"""


def gap_keys(knobs: list[Knob], launchers: list[Launcher]) -> list[str]:
    """`<launcher> <ENV>` for every undeclared gap -- the baseline's line format."""
    wanted = {knob.env for knob in knobs}
    keys = []
    for launcher in launchers:
        if launcher.is_library or launcher.delegates_to or launcher.single_slot:
            continue
        for env in sorted(wanted - launcher.sets - set(launcher.exempt)):
            keys.append(f"{launcher.name} {env}")
    return sorted(keys)


def read_baseline() -> set[str]:
    if not BASELINE.is_file():
        return set()
    return {
        line.strip()
        for line in BASELINE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--table", action="store_true", help="print the artifact inventory")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="fail on EVERY gap, ignoring the recorded backlog in the baseline file",
    )
    parser.add_argument(
        "--write-baseline",
        action="store_true",
        help="record today's gaps as the accepted backlog (they are still gaps)",
    )
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()

    if args.selftest:
        return selftest()

    knobs = discover_knobs()
    if not knobs:
        print(
            "er-artifact-redirect-audit: found NO redirect knobs in the Rust sources. That is a "
            "broken audit, not a clean tree.",
            file=sys.stderr,
        )
        return EXIT_BROKEN
    launchers = discover_launchers()

    if args.table:
        print_table(knobs, launchers)
        return EXIT_OK

    keys = gap_keys(knobs, launchers)
    if args.write_baseline:
        BASELINE.write_text(BASELINE_HEADER + "\n".join(keys) + "\n", encoding="utf-8")
        print(f"er-artifact-redirect-audit: recorded {len(keys)} known gap(s) in {BASELINE}")
        return EXIT_OK

    baseline = set() if args.strict else read_baseline()
    stale_rows = (
        verify_no_knob_table()
        + verify_recovered_knobs(knobs)
        + verify_shared_table(knobs)
    )
    delegation = [
        problem for problem in audit(knobs, launchers) if "delegates-to" in problem
    ]
    new_gaps = [key for key in keys if key not in baseline]
    resolved = sorted(baseline - set(keys))

    # THE BACKLOG IS PRINTED EVEN WHEN IT PASSES. A gate that says "ok" while 40 launchers still
    # write into a directory the next launch clears is the exact silence this audit was written to
    # break: it would read as "we captured everything".
    carried = sorted(key for key in keys if key in baseline)
    if carried:
        print(
            f"er-artifact-redirect-audit: {len(carried)} KNOWN gap(s) still open across "
            f"{len({key.split()[0] for key in carried})} launcher(s) -- recorded in "
            f"{BASELINE.name}, NOT fixed:"
        )
        for key in carried:
            print(f"  {key}")
        print()

    problems = stale_rows + delegation
    for key in new_gaps:
        launcher_name, env = key.split()
        problems.append(
            f"{launcher_name}: does not redirect {env}; that artifact stays in GAME_DIR, where "
            f"the next launch destroys it. Set it to a path inside this run's artifact dir, or "
            f"declare `# {MARKER} exempt {env} -- <reason>`."
        )
    if problems:
        print("er-artifact-redirect-audit: undeclared per-run artifact gaps\n", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        print(
            f"\n{len(problems)} gap(s). A GAME_DIR artifact is single-slot: the next launch "
            f"destroys it, and a copy at teardown cannot recover what this run already clobbered.",
            file=sys.stderr,
        )
        return EXIT_GAP

    if resolved:
        print(
            f"{len(resolved)} baseline entr(y/ies) no longer leak; drop them with "
            f"--write-baseline: {', '.join(resolved)}"
        )
    # PRINTED ON SUCCESS, LIKE THE BACKLOG ABOVE, AND FOR THE SAME REASON. A stated single-slot
    # launcher is not a clean one: its runs still overwrite each other beside `eldenring.exe`. It
    # was invisible here until 2026-08-31 -- absent from the report entirely, which reads as
    # compliance rather than as a decision somebody made.
    stated = [launcher for launcher in launchers if launcher.single_slot]
    for launcher in sorted(stated, key=lambda item: item.name):
        print(
            f"er-artifact-redirect-audit: {launcher.name} is SINGLE-SLOT BY DESIGN -- "
            f"{launcher.single_slot}"
        )
    print(
        f"er-artifact-redirect-audit: {len(launchers)} launcher(s), {len(knobs)} knob(s), "
        f"{len(stated)} stated single-slot, no NEW gaps"
    )
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
