#!/usr/bin/env python3
"""Regenerate scripts/comment-caps-words.txt, the banned-word list for check-comment-caps.py.

The gate needs to answer one question about a token like `ONLY` or `RVA`: is this an
ordinary English word being shouted, or a name that is genuinely spelled in capitals?
An allowlist of technical vocabulary cannot answer it -- registers, mnemonics, param
names, FromSoft type names and upstream `FUN_1401234ab` symbols are an open set that
grows every session, so an allowlist would reject new correct writing every week.
English is the closed set, so the list here is the English one, and everything not on
it is assumed to be a name.

The words come from `wordfreq`'s frequency-ordered English list, cut where the tail
stops being everyday vocabulary. There is no network access at gate time and no
dependency on wordfreq: this script writes the words to a committed text file, and the
gate reads that file. Re-run it only to widen or narrow the cut:

    uv run --with wordfreq python3 scripts/gen-comment-caps-words.py

`EXEMPT` below is the short list of English-looking words that name real things in this
repo. It is deliberately short: the general escape hatch is backticks (`NOT` inside
backticks is quoting the x86 instruction, not shouting), not a growing exemption list.
"""

from __future__ import annotations

from pathlib import Path

# Two cuts, because the two length classes behave differently. Short capitalised tokens are
# overwhelmingly acronyms and registers -- CS, ER, VA, ABI, RVA, HUD, NPC, RET, AL -- so below the
# everyday-vocabulary line only words of five letters or more are banned; that is where the
# emphasis actually lives (`IDENTICAL`, `MEASURED`, `DELIBERATELY`, `UNRESOLVED`) and where an
# acronym collision is rare. Above the line, length does not matter: `NOT`, `THE`, `ONE`, `ALL`,
# `OWN` are shouting whatever their length.
POOL = 40000  # how deep into the frequency list to look
ALWAYS_ZIPF = 4.5  # everyday vocabulary: banned at any length
LONG_ZIPF = 3.0  # ordinary-but-less-common vocabulary: banned from five letters up
LONG_MIN_LEN = 5

# English-looking tokens that name something real. Each one earns its line.
EXEMPT = {
    # acronyms and units that wordfreq ranks as ordinary English
    "ai", "bin", "cd", "dvd", "hd", "http", "https", "id", "ip", "led", "mac",
    "ok", "os", "pc", "ram", "tv", "usb", "va",
    # x86 registers and mnemonics that collide with English
    "al", "ah", "bl", "ch", "cl", "dh", "dl", "and", "or", "not", "test", "call",
    "push", "pop", "in", "out", "int", "div", "mul", "neg", "set", "sub",
    # this repo's own vocabulary
    "re",  # reverse engineering
    "ring", "elden",  # the game's name
    "safety", "note", "todo", "fixme", "hack", "xxx", "panic",  # comment tags
}

# ...but a few of those collisions are shouted far more often than they are quoted, and
# the quoting case has backticks available. Keep them banned despite the collision.
UNEXEMPT = {"and", "or", "not", "test", "call", "push", "pop", "in", "out", "set", "sub"}

# Short English words the length rule above would spare, kept banned because this repo shouts them
# and they are words, not acronyms. Measured from the tree: after the first sweep these were what
# was left standing next to lowercase prose (`A GATE that never executed`, `the SLOT it loaded`),
# which reads worse than either extreme. Where one of them names something -- a `gate` in a
# ledger, a save `slot` -- backticks say so.
EXTRA_BANNED = {
    "adds", "asks", "bail", "bake", "bare", "boot", "bug", "bugs", "byte", "caps", "clip",
    "deny", "diff", "dim", "dip", "disk", "doc", "dump", "edit", "emit", "exit", "fade",
    "flip", "fold", "font", "fork", "gap", "gaps", "gate", "gem", "git", "heal",
    "hint", "hook", "hooks", "hop", "hung", "hunt", "icon", "idle", "keys", "lazy", "leaf",
    "log", "logs", "loop", "maps", "mask", "menu", "mod", "new", "old", "omit", "ours",
    "out", "owns", "pane", "pin", "pins", "pipe", "poll", "pose", "pump", "root", "row",
    "rows", "rust", "scan", "seam", "seed", "sink", "sits", "skip", "slot", "sole", "span",
    "stub", "sum", "tab", "tag", "tail", "tear", "thin", "tick", "tied", "tier", "tile",
    "torn", "trap", "warp", "wire", "worn", "zoom",
}

HEADER = """\
# Banned in comments when written in ALL CAPS. Generated by
# scripts/gen-comment-caps-words.py; read by scripts/check-comment-caps.py.
#
# These are ordinary English words, so a comment shouting one is using capitals for
# emphasis. Capitals are reserved for things actually named in capitals -- a const, a
# static, an env var, an acronym, a register, a mnemonic, an upstream symbol. To quote
# one of these words as a name (the x86 NOT, a "NOT RUN" status string), put it in
# backticks; the gate does not read inside backticks.
#
# Do not hand-edit: add exemptions in the generator, not here.
"""


def main() -> int:
    from wordfreq import top_n_list  # imported late: only the generator needs it

    exempt = EXEMPT - UNEXEMPT
    from wordfreq import zipf_frequency

    def banned(w: str) -> bool:
        z = zipf_frequency(w, "en")
        return z >= ALWAYS_ZIPF or (z >= LONG_ZIPF and len(w) >= LONG_MIN_LEN)

    words = sorted(
        {
            w
            for w in top_n_list("en", POOL)
            if w.isalpha() and w.isascii() and len(w) >= 2 and w not in exempt and banned(w)
        }
        | (EXTRA_BANNED - exempt)
    )
    out = Path(__file__).resolve().parents[1] / "scripts" / "comment-caps-words.txt"
    out.write_text(HEADER + "\n".join(words) + "\n", encoding="utf-8")
    print(f"{out}: {len(words)} words")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
