#!/usr/bin/env python3
"""Turn the two tables into Rust the installer can link, so it parses nothing at runtime.

`me3-dll-catalog.toml` and `me3-dll-conflicts.toml` are the truth about what ships and what
may share a process. The installer needs both, and the obvious way to get them there is to
read the files at startup -- which would mean shipping them beside the exe, where a user can
edit or lose them, and pulling a TOML parser into a binary that otherwise needs none. This
workspace has a precedent for the other choice: `build-support/prologue_build.rs` generates
constants rather than parsing at runtime.

So the tables are compiled in. The installer ends up with zero dependencies -- no TOML
parser, no serde, no clap -- which is the point of the deliverable: one exe a player
downloads next to the DLLs and runs, having installed nothing.

The conflict `reason` fields are deliberately not carried across. They are reverse-engineering
evidence measured in hooked prologues and register captures, they run to paragraphs, and no
player is served by them. What crosses the boundary is the `kind`, which is the failure mode,
rendered here into one sentence each. A new kind appearing in the conflict table with no
sentence here is an error rather than a blank line.

Usage:
    python3 scripts/gen-installer-catalog.py            # write the file
    python3 scripts/gen-installer-catalog.py --check    # fail if it is out of date
    python3 scripts/gen-installer-catalog.py --selftest

Exit status is 1 on any failure, so `--check` can gate.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_TOML = REPO_ROOT / "scripts" / "me3-dll-catalog.toml"
CONFLICTS_TOML = REPO_ROOT / "scripts" / "me3-dll-conflicts.toml"
DLL_LIST = REPO_ROOT / "scripts" / "me3-dll-list.py"
OUT_RS = REPO_ROOT / "tools" / "er-installer" / "src" / "catalog.rs"

# One sentence per failure mode, addressed to a player rather than to whoever measured it.
# These must cover every `kind` in the conflict table; the generator refuses on a new one,
# because a kind the installer cannot explain becomes a refusal with a blank reason.
KIND_SENTENCE = {
    "hook-collision": (
        "both change the same piece of the game's code, and whichever loads second wins "
        "silently -- nothing crashes and nothing says so"
    ),
    "present-compositor": (
        "both draw over the game's own frame, and they fight for it"
    ),
    "duplicate-owner": (
        "both own the same feature, so pick whichever build of it you want, not both"
    ),
    "drives-input": (
        "one of them takes the controls by merely being loaded, so the other cannot be "
        "trusted to respond to you"
    ),
    "diagnostic-drive": (
        "a development tool that drives menus the other one owns"
    ),
    "corrupt-callback-pointer": (
        "loading both is known to crash the game, and the cause is not yet pinned down"
    ),
}

# The order a picker shows its sections in: what people came for first, tooling last.
CATEGORY_ORDER = [
    ("menus-and-saves", "Menus and saves"),
    ("quality-of-life", "Quality of life"),
    ("multiplayer", "Multiplayer"),
    ("cosmetic", "Cosmetic"),
    ("diagnostics", "Diagnostics"),
]


def shipped_pairs() -> list[tuple[str, str]]:
    spec = importlib.util.spec_from_file_location("me3_dll_list", DLL_LIST)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.dll_pairs()


def rust_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


HEADER = """// GENERATED by scripts/gen-installer-catalog.py -- do not edit.
//
// Source of truth: scripts/me3-dll-catalog.toml (what each mod is called) and
// scripts/me3-dll-conflicts.toml (which pairs must not share a process). Edit those and
// regenerate; `scripts/gen-installer-catalog.py --check` is what keeps the two in step.
//
// Compiled in rather than read at runtime, so the installer ships as one exe with no data
// files beside it to lose and no TOML parser inside it.

/// One ME3-loadable DLL, as a row in the picker.
///
/// `Debug` is derived because these appear in test assertions, and a failing test that can only
/// say "two values differ" costs more than the derive does.
#[derive(Debug)]
pub struct Mod {
    /// Cargo package name -- the key both source tables agree on.
    pub package: &'static str,
    /// File to copy next to the game, and to name in the `[[natives]]` entry.
    pub artifact: &'static str,
    pub label: &'static str,
    pub blurb: &'static str,
    pub category: &'static str,
    /// `player` or `diagnostic`. Diagnostics are never ticked on a first run.
    pub audience: &'static str,
    pub default_on: bool,
    /// Inert, or refusing to arm, unless Seamless Co-op is loaded.
    pub needs_seamless: bool,
    /// Recorded in the conflict table as something a player must ask for by name.
    pub opt_in_only: bool,
    /// A bigger mod that already carries this one, when there is one. Ticking both is safe --
    /// the smaller shell detects the bigger and stands down -- and adds nothing, so the picker
    /// says so instead of refusing.
    pub included_in: Option<&'static str>,
    /// The file in the game directory this mod reads, when it has one.
    pub config: Option<&'static str>,
}

/// A pair that must never share one profile, and why, in words a player can act on.
#[derive(Debug)]
pub struct Conflict {
    pub a: &'static str,
    pub b: &'static str,
    /// The failure mode, as recorded in `scripts/me3-dll-conflicts.toml`.
    pub kind: &'static str,
    pub explanation: &'static str,
}
"""


def render(
    catalog: dict,
    conflicts: dict,
    pairs: list[tuple[str, str]],
) -> str:
    artifacts = dict(pairs)
    opt_in_only = set(conflicts.get("opt_in_only", {}))

    kinds = {row.get("kind", "") for row in conflicts.get("conflict", [])}
    unknown = sorted(kinds - set(KIND_SENTENCE))
    if unknown:
        raise SystemExit(
            f"conflict kinds with no player-facing sentence: {unknown}\n"
            "Add one to KIND_SENTENCE in scripts/gen-installer-catalog.py."
        )

    lines = [HEADER, "/// The categories, in the order a picker should show them."]
    lines.append("pub const CATEGORIES: &[(&str, &str)] = &[")
    for key, title in CATEGORY_ORDER:
        lines.append(f"    ({rust_str(key)}, {rust_str(title)}),")
    lines.append("];")
    lines.append("")
    lines.append("pub const CATALOG: &[Mod] = &[")

    for package in sorted(catalog):
        entry = catalog[package]
        artifact = artifacts.get(package)
        if artifact is None:
            raise SystemExit(
                f"{package}: in the catalog but not a shipped shell. "
                "Run scripts/check-me3-dll-catalog.py for the full picture."
            )
        config = f"Some({rust_str(entry['config'])})" if entry.get("config") else "None"
        included_in = (
            f"Some({rust_str(entry['included_in'])})" if entry.get("included_in") else "None"
        )
        lines += [
            "    Mod {",
            f"        package: {rust_str(package)},",
            f"        artifact: {rust_str(artifact + '.dll')},",
            f"        label: {rust_str(entry['label'])},",
            f"        blurb: {rust_str(entry['blurb'])},",
            f"        category: {rust_str(entry['category'])},",
            f"        audience: {rust_str(entry['audience'])},",
            f"        default_on: {str(bool(entry['default'])).lower()},",
            f"        needs_seamless: {str(bool(entry.get('needs_seamless', False))).lower()},",
            f"        opt_in_only: {str(package in opt_in_only).lower()},",
            f"        included_in: {included_in},",
            f"        config: {config},",
            "    },",
        ]
    lines.append("];")
    lines.append("")
    lines.append("pub const CONFLICTS: &[Conflict] = &[")
    for row in conflicts.get("conflict", []):
        kind = row.get("kind", "")
        lines += [
            "    Conflict {",
            f"        a: {rust_str(row['a'])},",
            f"        b: {rust_str(row['b'])},",
            f"        kind: {rust_str(kind)},",
            f"        explanation: {rust_str(KIND_SENTENCE[kind])},",
            "    },",
        ]
    lines.append("];")
    return "\n".join(lines) + "\n"


def build() -> str:
    catalog = tomllib.loads(CATALOG_TOML.read_text(encoding="utf-8"))
    conflicts = tomllib.loads(CONFLICTS_TOML.read_text(encoding="utf-8"))
    return render(catalog, conflicts, shipped_pairs())


def selftest() -> int:
    """Prove the escaping and the refusal, not just that a render returns a string."""
    catalog = {
        "er-alpha": {
            "label": "Alpha",
            "blurb": 'Quotes "like this" and a backslash \\ survive.',
            "category": "cosmetic",
            "audience": "player",
            "default": True,
            "config": "alpha.toml",
            "included_in": "er-beta",
        },
        "er-beta": {
            "label": "Beta",
            "blurb": "No config.",
            "category": "diagnostics",
            "audience": "diagnostic",
            "default": False,
        },
    }
    conflicts = {
        "conflict": [{"a": "er-alpha", "b": "er-beta", "kind": "hook-collision"}],
        "opt_in_only": {"er-beta": "reason"},
    }
    pairs = [("er-alpha", "er_alpha"), ("er-beta", "er_beta")]
    out = render(catalog, conflicts, pairs)

    checks = [
        ('artifact: "er_alpha.dll"', "artifact is the dll filename, not the package"),
        ('\\"like this\\"', "quotes inside a blurb are escaped"),
        ("backslash \\\\ survive", "backslashes inside a blurb are escaped"),
        ('config: Some("alpha.toml")', "a present config becomes Some(..)"),
        ("config: None", "an absent config becomes None"),
        ('included_in: Some("er-beta")', "a present included_in becomes Some(..)"),
        ("included_in: None", "an absent included_in becomes None"),
        ("opt_in_only: true", "opt_in_only is carried over from the conflict table"),
        ("default_on: true", "the default tick is carried over"),
        ("whichever loads second wins", "the kind is rendered into a sentence"),
    ]
    failures = 0
    for needle, name in checks:
        if needle not in out:
            print(f"SELFTEST FAIL {name}: {needle!r} not in generated output")
            failures += 1

    try:
        render(catalog, {"conflict": [{"a": "er-alpha", "b": "er-beta", "kind": "novel"}]}, pairs)
    except SystemExit:
        pass
    else:
        print("SELFTEST FAIL: an unknown conflict kind was not refused")
        failures += 1

    if failures:
        print(f"selftest: {failures} case(s) failed")
        return 1
    print(f"selftest: {len(checks) + 1} cases passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()

    if args.selftest:
        return selftest()

    generated = build()
    if args.check:
        current = OUT_RS.read_text(encoding="utf-8") if OUT_RS.exists() else ""
        if current != generated:
            print(
                f"{OUT_RS.relative_to(REPO_ROOT)} is out of date with the source tables.\n"
                "Regenerate: python3 scripts/gen-installer-catalog.py"
            )
            return 1
        print(f"{OUT_RS.relative_to(REPO_ROOT)}: up to date.")
        return 0

    OUT_RS.parent.mkdir(parents=True, exist_ok=True)
    OUT_RS.write_text(generated, encoding="utf-8")
    print(f"wrote {OUT_RS.relative_to(REPO_ROOT)} ({len(generated)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
