#!/usr/bin/env python3
"""Record which 1.16.2 addresses the RUNNING game actually asked for and was refused.

`select-needed-1170-rows.py` finds addresses by scanning for `const` declarations whose
name carries the RVA suffix. That misses any address whose constant is named something
else, or is computed rather than declared -- and the miss is not small: of the 54
addresses the build gate refused during the 2026-08-29 boot, 42 were sitting in the
function map already, unused, because nothing connected them to a declaration the scan
could see.

The running game is the authority on which addresses are actually reached. This reads the
`ADDRESS REFUSED` lines out of the DLL logs and writes them to a tracked list, so the next
selection carries them too.

Being wanted is not being known: an address recorded here still has to be found in the
function or data map before it becomes a translation. This file is a work list.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

BASE = 0x140000000
# Both refusal wordings. `ADDRESS REFUSED FOR DETOUR` was added when calls and detours were
# split, and the original pattern -- which required the parenthesis straight after REFUSED --
# silently matched none of them. That hid 72 addresses that no map covers: the ones the boot
# oracles hook, and therefore the reason boot progress reads as zero.
REFUSED = re.compile(r"ADDRESS REFUSED(?: FOR DETOUR)? \([^)]*\): (0x14[0-9a-f]+)")
LOGS = (
    "er-quickload-autoload-debug.log",
    "er-armament-icons.log",
    "er-invasion-warp.log",
    "er-refill-all.log",
)
OUTPUT = "docs/recon/rva-1170-observed-refusals.txt"
DEFAULT_GAME = Path.home() / ".local/share/Steam/steamapps/common/ELDEN RING/Game"

HEADER = [
    "# 1.16.2 RVAs the RUNNING game asked for and the build gate refused.",
    "#",
    "# Generated by scripts/record-1170-refusals.py from the DLL logs of a real run, and read",
    "# by scripts/select-needed-1170-rows.py so these addresses get carried alongside the ones",
    "# found by scanning constant declarations.",
    "#",
    "# Why both sources are needed: the declaration scan missed 42 of the 54 addresses refused",
    "# during the 2026-08-29 boot, all of which the function map could already answer. A",
    "# constant named without the suffix, or computed rather than declared, is invisible to the",
    "# scan and perfectly visible to the game.",
    "#",
    "# Being wanted is not being known. An address here still has to be found in the function or",
    "# data map before it becomes a translation; until then this is a work list, not an answer.",
]


def collect(game: Path) -> tuple[list[int], list[str]]:
    seen: set[int] = set()
    read: list[str] = []
    for name in LOGS:
        path = game / name
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        read.append(name)
        for hit in REFUSED.findall(text):
            seen.add(int(hit, 16) - BASE)
    return sorted(seen), read


def main() -> int:
    repo = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--game", type=Path, default=DEFAULT_GAME)
    ap.add_argument("--merge", action="store_true", help="keep addresses already recorded")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        failures = []
        sample = "[+1ms] ADDRESS REFUSED (game_rva): 0x1409a62c0 -- game FileVersion 2.7.0.0\n"
        if REFUSED.findall(sample) != ["0x1409a62c0"]:
            failures.append("the refusal pattern did not match a real log line")
        detour = "[+1ms] ADDRESS REFUSED FOR DETOUR (register_union_hook 0x140b0f000): 0x140b0f000 -- game\n"
        if REFUSED.findall(detour) != ["0x140b0f000"]:
            failures.append("the detour-refusal wording was not matched; 72 addresses hid behind that once")
        # A line that merely mentions the words must not be harvested as an address.
        if REFUSED.findall("HOOK REFUSED (MhHook::new 0x1411d0fa0): game FileVersion 2.7.0.0\n"):
            failures.append("a HOOK REFUSED line was harvested; only ADDRESS REFUSED carries the address")

        # THE BOUNDED WORDINGS (2026-08-30). `er_game_base::game_build` no longer writes one line
        # per refusal: after 12 of an address it writes a went-quiet marker, then restates at each
        # power of ten. That is safe for THIS script only because it de-duplicates into a set AND
        # because every one of those lines keeps the same prefix. The second half is a contract
        # between two files that nothing else checks, so it is checked here -- from the consuming
        # side -- as well as by `every_refusal_line_stays_harvestable_by_the_refusal_recorder` in
        # game_build.rs. A run whose first 12 lines are lost to log rotation still yields the
        # address, which is the whole reason the later lines repeat it.
        bounded = (
            ("[+9ms] ADDRESS REFUSED (CS_MSB_POINT_CTOR_RVA): 0x140cf9300 -- refusal 13 of this "
             "address; further refusals of it are counted, not written\n", "0x140cf9300"),
            ("[+9ms] ADDRESS REFUSED (CS_MSB_POINT_CTOR_RVA): 0x140cf9300 -- refusal 100 of this "
             "address. Restated so the log carries the MAGNITUDE of a dead path\n", "0x140cf9300"),
            ("[+9ms] ADDRESS REFUSED FOR DETOUR (register_union_hook): 0x140b0f000 -- refusal 13 "
             "of this address; further refusals of it are counted, not written\n", "0x140b0f000"),
        )
        for line, expected in bounded:
            if REFUSED.findall(line) != [expected]:
                failures.append(
                    f"a BOUNDED refusal line was not harvested, so an address whose early lines "
                    f"rotated out of the log would never reach the work list: {line.strip()}"
                )
        for line in failures:
            print(f"SELFTEST FAIL: {line}")
        print(f"selftest: {len(failures)} failure(s)")
        return 1 if failures else 0

    if not args.game.is_dir():
        print(f"SKIP: no game directory at {args.game}")
        return 0
    found, read = collect(args.game)
    if not read:
        print(f"SKIP: no DLL logs under {args.game}")
        return 0

    target = repo / OUTPUT
    # SAY SO WHEN A RUN WOULD DELETE WORK. Without `--merge` this file is OVERWRITTEN by whatever
    # the logs currently in the game directory happen to hold, and those logs are one session --
    # often a short one, sometimes one where a fix means almost nothing is refused any more.
    # Measured 2026-08-30: a plain run against a live directory rewrote a 136-address list down to
    # the single address that session refused, silently, exiting 0. The write still happens (that
    # is the documented contract and `--merge` is how to keep the rest), but it no longer happens
    # quietly.
    existing = 0
    if target.is_file():
        existing = sum(
            1
            for line in target.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.startswith("#")
        )
    if not args.merge and existing > len(found):
        print(
            f"WARNING: this run harvested {len(found)} address(es) from the current logs, but "
            f"{OUTPUT} already lists {existing}. Without --merge the {existing - len(found)} "
            f"not seen in THIS session are about to be dropped. Re-run with --merge to keep them.",
            file=sys.stderr,
        )
    if args.merge and target.is_file():
        for line in target.read_text(encoding="utf-8").splitlines():
            if line.startswith("#") or not line.strip():
                continue
            try:
                found.append(int(line, 16))
            except ValueError:
                pass
        found = sorted(set(found))
    target.write_text("\n".join(HEADER + [f"0x{r:x}" for r in found]) + "\n", encoding="utf-8")
    print(f"recorded {len(found)} refused address(es) from {', '.join(read)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
