#!/usr/bin/env python3
"""Launch each cdylib ALONE on ELDEN RING 1.17 and record what it does, one DLL per run.

WHY ONE DLL AT A TIME
---------------------
On 2026-08-29 the whole mod set was failing and it was being discussed as "the mods break 1.17".
It is not one failure. Nine single-DLL launches found THREE different ones, and the crates that
boot cleanly outnumber the ones that do not:

    er_quickload          0xc0000005 EXECUTE at a CS::CSFadeImp object, +1.7s
    er_loading_portrait   vanishes ~4s after its first Present, leaving NO crash record
    er_armament_icons     0xc000001d ILLEGAL_INSTRUCTION at game+0x32ee2b5

READ THE SIGNATURE, NOT THE LIVENESS. Scoring rows live/dead would have convicted er-gfx (shared
by two dying shells -- but they die differently) and the Present hook (both Present-hooking shells
died -- until er_loading_bar, which hooks Present and boots, killed that theory). A bisect on
liveness alone gets the wrong crate; the crash-log signature is what discriminates.

WHAT IT RECORDS
    boots        the thread-group leader is still alive at the end of the watch window
    dies:<sig>   the leader went `Z` or the process vanished; `<sig>` is the first
                 access-violation / exception line its own crash log carried, if any
    no-launch    the game never came up at all (a launcher or environment problem, not a DLL one)

Results merge into `docs/recon/dll-1170-runtime-results.json`, which
`scripts/audit-1170-readiness.py` prints as its `runtime` column. That file is the ONLY source of
runtime truth: a DLL with zero ungated addresses is not thereby working, and nothing infers one
from the other.

DO NOT REBUILD WHILE THIS RUNS
------------------------------
Measured 2026-08-29, by doing it: a sweep was started, DLLs were rebuilt 10 minutes into it, and
the run silently became a mix -- the first eight DLLs tested one build and the rest another. A
sweep that cannot say which build it measured is not evidence, and 18 verdicts had to be thrown
away. So the sweep now fingerprints every DLL at the start and ABORTS the moment one changes
underneath it, rather than producing a result that looks fine and is not.

SAFETY / HOUSE RULES
  * launches only the approved `~/Elden/launch.sh` path -- never Steam, never the EAC launcher;
  * one game at a time, torn down between runs via `scripts/er-teardown.py`;
  * profiles are written to `~/Elden/sweep-<dll>.me3` and name only the one DLL under test.

USAGE
    python3 scripts/sweep-dll-1170-runtime.py --list
    python3 scripts/sweep-dll-1170-runtime.py --dll er-net-effects
    python3 scripts/sweep-dll-1170-runtime.py --all --watch-seconds 40
    python3 scripts/sweep-dll-1170-runtime.py --selftest
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import time

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(REPO, "docs", "recon", "dll-1170-runtime-results.json")
DLL_DIR = os.path.join(REPO, "target", "x86_64-pc-windows-msvc", "release")
PROFILE_DIR = os.path.join(os.path.expanduser("~"), "Elden")
LAUNCHER = os.path.join(PROFILE_DIR, "launch.sh")
TEARDOWN = os.path.join(REPO, "scripts", "er-teardown.py")
GAME_DIR = os.path.join(
    os.path.expanduser("~"),
    ".local/share/Steam/steamapps/common/ELDEN RING/Game",
)
# Long enough to clear every failure this sweep has seen: the earliest is +1.7s and the latest
# ~+38s. A DLL still alive after this is reported as booting, not as proven healthy.
DEFAULT_WATCH_SECONDS = 45.0
# How long to wait for the game process to appear before calling it a launcher problem.
LAUNCH_TIMEOUT_SECONDS = 25.0
POLL_SECONDS = 2.0

PROFILE_TEMPLATE = """# GENERATED by scripts/sweep-dll-1170-runtime.py -- one DLL, to see what IT does on 1.17.
# Regenerated on every sweep; edit the script, not this file.
profileVersion = "v1"
start_online = false

[[supports]]
game = "eldenring"

[[natives]]
path = '{dll}'
"""


def dll_path(crate: str) -> str:
    return os.path.join(DLL_DIR, crate.replace("-", "_") + ".dll")


def game_pid() -> int | None:
    """The running `eldenring.exe`, by comm -- deliberately name-only.

    The prefix and appid rules in `er-teardown.py` both go false under the Steam Linux Runtime,
    whose bwrap container puts the exe and cwd somewhere neither matches.
    """
    for entry in os.listdir("/proc"):
        if not entry.isdigit():
            continue
        try:
            with open(f"/proc/{entry}/comm", encoding="utf-8") as handle:
                if handle.read().strip() == "eldenring.exe":
                    return int(entry)
        except OSError:
            continue
    return None


def leader_state(pid: int) -> str | None:
    try:
        with open(f"/proc/{pid}/stat", encoding="utf-8") as handle:
            return handle.read().split()[2]
    except (OSError, IndexError):
        return None


def teardown() -> None:
    subprocess.run(
        ["python3", TEARDOWN], capture_output=True, text=True, cwd=REPO, timeout=30, check=False
    )


def crash_signature(crate: str, since: float) -> str:
    """The first fault line from any crash log this DLL touched during the run."""
    best = ""
    try:
        names = os.listdir(GAME_DIR)
    except OSError:
        return best
    for name in names:
        if "crash" not in name or not name.endswith((".txt", ".log")):
            continue
        path = os.path.join(GAME_DIR, name)
        try:
            if os.path.getmtime(path) < since:
                continue
            with open(path, encoding="utf-8", errors="replace") as handle:
                for line in handle:
                    if "access-violation" in line or "exception code" in line:
                        match = re.search(r"(access-violation|exception code)[^;]{0,110}", line)
                        if match:
                            return f"{name}: {match.group(0).strip()}"
        except OSError:
            continue
    return best


def run_one(crate: str, watch_seconds: float) -> str:
    path = dll_path(crate)
    if not os.path.exists(path):
        return "not-built"
    profile = os.path.join(PROFILE_DIR, f"sweep-{crate}.me3")
    with open(profile, "w", encoding="utf-8") as handle:
        handle.write(PROFILE_TEMPLATE.format(dll=path))

    teardown()
    started = time.time()
    environment = dict(os.environ, ME3_PROFILE=profile)
    subprocess.Popen(
        ["setsid", "nohup", "bash", LAUNCHER, "-s"],
        env=environment,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        cwd=os.path.expanduser("~"),
        start_new_session=True,
    )

    pid = None
    while time.time() - started < LAUNCH_TIMEOUT_SECONDS and pid is None:
        time.sleep(POLL_SECONDS)  # the POLL INTERVAL of a wait, not a synchronisation
        pid = game_pid()
    if pid is None:
        teardown()
        return "no-launch"

    verdict = "boots"
    deadline = time.time() + watch_seconds
    while time.time() < deadline:
        time.sleep(POLL_SECONDS)
        state = leader_state(pid)
        if state is None or state == "Z":
            verdict = "dies"
            break
    signature = crash_signature(crate, started)
    teardown()
    stamp = time.strftime("%Y-%m-%d")
    if verdict == "dies":
        return f"dies: {signature or 'no crash record'} ({stamp})"
    return f"boots, leader alive at {watch_seconds:g}s ({stamp})"


def fingerprint(crates: list[str]) -> dict[str, tuple[int, int]]:
    """`{crate: (size, mtime_ns)}` for the built DLLs, cheap enough to re-check between runs."""
    stamps = {}
    for crate in crates:
        try:
            stat = os.stat(dll_path(crate))
        except OSError:
            continue
        stamps[crate] = (stat.st_size, stat.st_mtime_ns)
    return stamps


def load_results() -> dict:
    try:
        with open(RESULTS, encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, ValueError):
        return {}


def save_results(results: dict) -> None:
    with open(RESULTS, "w", encoding="utf-8") as handle:
        json.dump(results, handle, indent=2)
        handle.write("\n")


def cdylibs() -> list[str]:
    meta = json.loads(
        subprocess.run(
            ["cargo", "metadata", "--no-deps", "--format-version", "1"],
            capture_output=True, text=True, cwd=REPO, check=True, timeout=30,
        ).stdout
    )
    return sorted(
        p["name"] for p in meta["packages"] if any("cdylib" in t["kind"] for t in p["targets"])
    )


def selftest() -> int:
    failures = []
    if not os.path.exists(LAUNCHER):
        print(f"selftest SKIP: no launcher at {LAUNCHER}")
        return 0
    if game_pid() is not None and leader_state(game_pid()) is None:
        failures.append("leader_state returned None for a pid game_pid() just found")
    if "steam" in PROFILE_TEMPLATE.lower():
        failures.append("the generated profile must not reference Steam")
    built = [c for c in cdylibs() if os.path.exists(dll_path(c))]
    if not built:
        failures.append("no built DLLs found -- run scripts/er-build-dlls.sh --all first")
    if DEFAULT_WATCH_SECONDS < 40:
        failures.append("watch window is shorter than the latest failure this sweep has seen")
    stamps = fingerprint(cdylibs())
    if stamps and fingerprint(cdylibs()) != stamps:
        failures.append("fingerprint is not stable across two calls on an unchanged tree")
    for line in failures:
        print(f"selftest FAIL {line}")
    print(f"selftest: {len(failures)} failure(s); {len(built)} built cdylib(s)")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dll", action="append", help="crate name; repeatable")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--skip-measured", action="store_true", help="only DLLs with no result yet")
    parser.add_argument("--watch-seconds", type=float, default=DEFAULT_WATCH_SECONDS)
    parser.add_argument("--list", action="store_true")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()
    if args.selftest:
        return selftest()

    results = load_results()
    everything = cdylibs()
    if args.list:
        for crate in everything:
            built = "built" if os.path.exists(dll_path(crate)) else "NOT BUILT"
            print(f"{crate:26s} {built:9s} {results.get(crate, '-')}")
        return 0

    targets = args.dll or (everything if args.all else [])
    if not targets:
        parser.error("give --dll NAME, or --all")
    if args.skip_measured:
        targets = [t for t in targets if t not in results or "pre-gating" in str(results.get(t))]

    baseline = fingerprint(everything)
    for crate in targets:
        drifted = [
            name
            for name, stamp in fingerprint(everything).items()
            if baseline.get(name) not in (None, stamp)
        ]
        if drifted:
            print(
                "[sweep] ABORT -- these DLLs changed on disk mid-sweep: "
                + ", ".join(sorted(drifted))
                + ". Verdicts already recorded describe the OLD build; the rest would describe a "
                "different one, and a mix is not evidence. Let the tree settle, then re-run.",
                flush=True,
            )
            return 1
        print(f"[sweep] {crate} ...", flush=True)
        verdict = run_one(crate, args.watch_seconds)
        print(f"[sweep] {crate}: {verdict}", flush=True)
        results[crate] = verdict
        save_results(results)  # after every DLL, so an interrupted sweep keeps what it measured
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
