#!/usr/bin/env python3
"""Re-validate every RUNTIME byte-signature / AOB scan pattern against ELDEN RING 1.17.

WHY THIS EXISTS
---------------
A hardcoded RVA that moved gets REFUSED by `er-game-base`'s translation gate: loud, safe, one
missing feature.  A SCAN has no such gate.  It runs against whatever image is loaded and answers
with an address, and there are three ways that answer goes wrong:

  (a) it matches NOTHING          -> the feature is refused.  Loud and safe.
  (b) it matches a DIFFERENT site -> a confident wrong address that reads as a live value.
  (c) it matches MORE than once where it used to be unique -> "first match wins" picks silently.

Only (a) is safe, and a bare 1.17 hit count cannot tell the three apart.  The 1.16.2 count is the
CALIBRATION: a pattern that was already non-unique on the image it was authored against was
fragile before 1.17 touched it, and its 1.17 count means nothing without that context.

A scan result is ALREADY a 1.17 address.  It must NEVER be put through the 1.16.2 -> 1.17
translator -- doing that translates a correct address a second time.  That nearly shipped two
crash-hooking rows for `er-armament-icons` (a +0x1e00 jump into mid-function); see the removal
note in `docs/recon/rva-map-1162-to-1170.verified.tsv`.

WHAT IT CHECKS
--------------
  patterns  Every literal AOB in the tree, scanned over BOTH images' first `.text` (which is the
            section the runtime scanners bound themselves to -- see NOTE ON `.text` below), with
            the hits classified and, where the counts agree, checked for 1:1 correspondence by
            `.pdata` function containment.
  needles   The other scan family: pointer-value scans whose needle is built at RUNTIME from an
            RVA constant.  `er_game_base::mem::game_data_addr` answers **0** for an address with
            no verified 1.17 mapping.  A refusal used as a DEREFERENCE target is safe (the read
            faults closed).  A refusal used as a SCAN NEEDLE is the opposite of safe: zero matches
            every zeroed qword in the address space, so the scan returns a confident pointer into
            blank memory.  This section reports, per scan, whether the needle RVA has a ledger row
            and whether the code rejects a zero needle.
  prologues The OTHER runtime byte-signature family: the detour-prologue constants generated by
            `build-support/prologue_build.rs`.  These are not scans -- each is checked at one
            address -- but they are still 1.16.2 bytes compared against live memory, and they
            decide whether a hook arms.  Each is re-checked against the 1.17 image at the address
            the RVA ledger maps it to, so the report says which features the gate will disarm.
  sync      Every pinned pattern literal is re-extracted from the source file it lives in.  This
            is what keeps the answer regenerable instead of a snapshot: edit the constant in the
            crate and this fails until the pin is updated.

`sync` needs no game image and always runs.  `patterns` SKIPS when an image is missing (the same
shape as the corpus-gated tests), unless `--require-images` is passed.

NOTE ON `.text`
---------------
Both images carry TWO sections named `.text`: the real code at 0x140001000, and an Arxan tail at
the very top of the image.  Every runtime scanner in this repo resolves the section by walking the
PE section table and returning the FIRST `.text` (`er_game_base::mem::module_text_range`, and
`find_text_section` in er-quickload's crashlog), so that is the range scanned here.  The tail is
reported separately and is informational only.

USAGE
    python3 scripts/verify-aob-patterns-1170.py                 # everything
    python3 scripts/verify-aob-patterns-1170.py --section needles
    python3 scripts/verify-aob-patterns-1170.py --section prologues
    python3 scripts/verify-aob-patterns-1170.py --selftest
    python3 scripts/verify-aob-patterns-1170.py --require-images

Exit code 0 = every pattern matched its pinned classification and every needle scan is accounted
for; 1 = a drift, a regression, or an unguarded scan whose needle has no 1.17 mapping.
"""

import argparse
import bisect
import importlib.util
import os
import re
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE = 0x140000000
IMAGES = {
    "1162": Path(os.environ.get("ER_DEOBF_1162", ROOT / "eldenring-deobf.bin")),
    "1170": Path(os.environ.get("ER_DEOBF_1170", ROOT / "eldenring-deobf-1.17.bin")),
}
GENERATOR = ROOT / "build-support/prologue_build.rs"


def _load(name, filename):
    """Import a sibling script by path. These are `-`-named files, so a plain import cannot."""
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / filename)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# `check-1170-translation-collisions.py` already parses every admission rule out of
# `er-game-base/build.rs` and reproduces both shipped tables from them.  Measured 2026-08-30:
# its CALL and DETOUR maps are byte-identical to the `address_map_1170.rs` cargo generated.  It
# is imported rather than re-implemented for the reason its own docstring gives -- a COPIED
# admission rule is how a table got reported as 42 rows instead of 374.
_COLLISIONS = _load("check_1170_translation_collisions", "check-1170-translation-collisions.py")

# --- which module a prologue lives in ----------------------------------------------------------
# `build-support/prologue_build.rs` declares `enum Image`, and a `PrologueSpec` names one variant.
# This table says what each variant MEANS here: which of the two flat images can ground-truth it,
# or `None` for a real variant whose module this script does not load.
#
# It is checked for COMPLETENESS against the enum at run time, and a variant the enum declares and
# this table does not model is a hard failure rather than a SKIP.  That rule exists because the
# absence of it cost three pins: `Image::EldenRing1170` was added on 2026-08-30, the dispatch here
# read `image_kind != "EldenRing"`, and `SAVE_REQUEST_RETRACT_B72_SIG`, `..._B73_SIG` and
# `QUIT_PHASE_SETTLE_SIG` were filed as SKIP -- three pins that arm, reported as unverified, in a
# gate whose exit code stayed 0.  A SKIP inside a green gate is indistinguishable from a check
# that ran.
IMAGE_ROLE = {
    "EldenRing": "1162",
    # The pin already holds 1.17 bytes at a 1.17 VA: no ledger hop, compare it in place.
    "EldenRing1170": "1170",
    # Seamless Co-op's `ersc.dll`. A real image with real pins; this script loads only the two
    # eldenring images, so it says so instead of pretending to check them.
    "Ersc": None,
}
_UNMODELLED = object()

# --- pattern registry -------------------------------------------------------------------------
# `symbol` names the Rust constant the literal is extracted from, so the pinned copy below can
# never drift from the code without `sync` saying so.  `literals` picks which string literals in
# that constant's initialiser are FIND patterns (a table of (find, patch) pairs has both).
#
# `consumer` is what the calling code DOES with the result, which is what decides whether a
# non-unique answer is a lost feature or a corruption:
#   unique-or-refuse    the scanner returns None on 0 or >1 hits and the caller disarms.
#   patch-every-match   every hit is written to.  Count is the only thing standing between this
#                       and overwriting unrelated code.
#   structural          not a 1.16.2-derived signature at all (padding runs, PE magic); listed so
#                       the inventory is complete.
REGISTRY = [
    {
        "id": "armament-icons/PARSE_SIG",
        "source": "crates/er-armament-icons/src/gfx_equip_hook.rs",
        "symbol": "PARSE_SIG",
        "literals": [0],
        "consumer": "unique-or-refuse",
        "pattern": "40 53 48 83 EC 40 48 8B 41 18 48 8B D9 C6 44 24 30 01 48 83 C1 50 4C 8B 50 20 4C 8B 58 48",
        "expect": {"1162": 1, "1170": 1},
        "note": "GFx tag-parse entry; hooked. scan_unique() refuses 0 or >1.",
    },
    {
        "id": "invasion-warp/PARSE_SIG",
        "source": "crates/er-invasion-warp/src/map_gfx.rs",
        "symbol": "PARSE_SIG",
        "literals": [0],
        "consumer": "unique-or-refuse",
        "pattern": "40 53 48 83 EC 40 48 8B 41 18 48 8B D9 C6 44 24 30 01 48 83 C1 50 4C 8B 50 20 4C 8B 58 48",
        "expect": {"1162": 1, "1170": 1},
        "note": "Same function as armament-icons/PARSE_SIG; independent copy of the literal.",
    },
    {
        "id": "ersc-sigshim/ALLOCATOR_SHAPE",
        "source": "crates/er-ersc-sigshim/src/fixups.rs",
        "symbol": "ALLOCATOR_SHAPE",
        "literals": [0],
        "consumer": "unique-or-refuse",
        "pattern": "E8 ? ? ? ? 48 8B 15 ? ? ? ? 48 8D 4B ?",
        "expect": {"1162": 1, "1170": 1},
        "note": "Seamless Co-op's allocator landmark; exactly_one() refuses 0 or >1.",
    },
    {
        "id": "ersc-sigshim/SCADUTREE_SHAPE",
        "source": "crates/er-ersc-sigshim/src/fixups.rs",
        "symbol": "SCADUTREE_SHAPE",
        "literals": [0],
        "consumer": "unique-or-refuse",
        "pattern": "80 B9 ? ? 00 00 00 74 08 0F B6 81 ? ? 00 00 C3 0F B6 81 ? ? 00 00 C3",
        "expect": {"1162": 1, "1170": 1},
        "note": "GetScadutreeBlessing; its entry is RE-SHAPED, so a wrong hit would rewrite live code.",
    },
    {
        "id": "quickload/ANTI_ANTIDEBUG check1",
        "source": "crates/er-quickload/src/constants/anti_debug.rs",
        "symbol": "ANTI_ANTIDEBUG_CHECKS",
        "literals": [0],
        "consumer": "patch-every-match",
        "pattern": "7A ?? 75 ?? B9 ?? ?? ?? ?? E8 ?? ?? ?? ?? F3 0F 11 05",
        "expect": {"1162": 181, "1170": 181},
        "note": "ProDebug port. Every hit is patched; the count IS the safety property.",
    },
    {
        "id": "quickload/ANTI_ANTIDEBUG check2",
        "source": "crates/er-quickload/src/constants/anti_debug.rs",
        "symbol": "ANTI_ANTIDEBUG_CHECKS",
        "literals": [2],
        "consumer": "patch-every-match",
        "pattern": "0F 8A ?? ?? ?? ?? 0F 85 ?? ?? ?? ?? B9 ?? ?? ?? ?? E8 ?? ?? ?? ?? F3 0F 11 05",
        "expect": {"1162": 1, "1170": 1},
        "note": "ProDebug port, long form of check1.",
    },
    {
        "id": "quickload/ANTI_ANTIDEBUG check3",
        "source": "crates/er-quickload/src/constants/anti_debug.rs",
        "symbol": "ANTI_ANTIDEBUG_CHECKS",
        "literals": [4],
        "consumer": "patch-every-match",
        "pattern": "73 ?? 0F 2F ?? 76 ?? 48 8D 15",
        "expect": {"1162": 138, "1170": 138},
        "note": "ProDebug port. 10 bytes -- the shortest signature in the tree.",
    },
    {
        "id": "quickload/ANTI_ANTIDEBUG check4",
        "source": "crates/er-quickload/src/constants/anti_debug.rs",
        "symbol": "ANTI_ANTIDEBUG_CHECKS",
        "literals": [6],
        "consumer": "patch-every-match",
        "pattern": "72 ?? 48 8D 4C 24 ?? E8 ?? ?? ?? ?? 90 48 8B 05 ?? ?? ?? ?? FF D0",
        "expect": {"1162": 10, "1170": 10},
        "note": "ProDebug port; patches one byte (72 -> EB) at each hit.",
    },
]

# `er-ersc-sigshim`'s cave allocator scans the SAME `.text` for a run of 0xCC padding.  It is not
# a 1.16.2-derived signature -- 0xCC padding is a property of the de-Arxan'd image, not of a build
# -- so it is checked for AVAILABILITY (does a long enough run still exist?) rather than identity.
CAVE_FILL = 0xCC
CAVE_MARGIN = 1
CAVE_NEEDS = (
    ("ersc-sigshim/ALLOCATOR_LEN", 16),
    ("ersc-sigshim/SCADUTREE_LEN", 25),
)

# --- runtime-built needle registry ------------------------------------------------------------
# These scans compare a qword read out of live memory against `base + RVA`, resolved through
# `game_data_addr`, which answers 0 for an unmapped RVA.  `guard` is the source regex that proves
# the code rejects a zero needle; `guarded` pins whether one is expected to be there today.
NEEDLE_SCANS = [
    {
        "id": "telemetry-core/title_binding::scan_for_owner",
        "source": "crates/er-telemetry-core/src/read/title_binding.rs",
        "needles": [("TITLE_OWNER_VTABLE_RVA", 0x2B63BB0), ("INNER_TITLE_STATE_TABLE_RVA", 0x3D71580)],
        "guard": r"want_vtable\s*==\s*0|want_vtable\s*<\s*HEAP_LO",
        "guarded": True,
        "consumes": "owner pointer cached forever; fields at +0x48/+0xe0/+0x130 read and reported "
        "as title-binding telemetry",
    },
    {
        "id": "input-harness/title_scan::scan_for_owner",
        "source": "crates/er-input-harness/src/title_scan.rs",
        "needles": [("TITLE_OWNER_VTABLE_RVA", 0x2B63BB0), ("INNER_TITLE_STATE_TABLE_RVA", 0x3D71580)],
        "guard": r"want_vtable\s*==\s*0|want_vtable\s*<\s*HEAP_LO",
        "guarded": True,
        "consumes": "title_state()/title_dialog_a40() gate the harness's menu drive",
    },
    {
        "id": "title-flow/profile_select_flow::find_title_owner_by_vtable",
        "source": "crates/er-title-flow/src/profile_select_flow.rs",
        "needles": [("TITLE_OWNER_VTABLE_RVA", 0x2B63BB0), ("INNER_TITLE_STATE_TABLE_RVA", 0x3D71580)],
        "guard": r"target_vtable\s*==\s*0|target_vtable\s*<\s*HEAP_LO",
        "guarded": True,
        "consumes": "the title owner the product's own title/load stepper drives; TITLE_OWNER_MIN_STATE "
        "is 0, so a zeroed block passes the state cross-check too",
    },
    {
        "id": "telemetry-core/dialog_active::scan_for_dialog",
        "source": "crates/er-telemetry-core/src/read/dialog_active.rs",
        "needles": [("MSGBOX_DIALOG_VTABLE_RVA", 0x2B03550), ("SAVE_RETRY_DIALOG_VTABLE_RVA", 0x2AAABF8)],
        "guard": r"if\s+vt\s*==\s*0\s*\{",
        "guarded": True,
        "consumes": "msgbox-active oracle; dialog_class() rejects vt == 0 before anything else",
    },
]


# --- image / matching primitives --------------------------------------------------------------
class Image:
    """A flat (virtual-layout) PE image: file offset == RVA, VA == BASE + offset."""

    def __init__(self, path: Path):
        self.path = path
        self.data = path.read_bytes()
        pe = struct.unpack_from("<I", self.data, 0x3C)[0]
        if self.data[pe : pe + 4] != b"PE\0\0":
            raise SystemExit(f"{path}: not a PE image")
        nsec = struct.unpack_from("<H", self.data, pe + 6)[0]
        optsz = struct.unpack_from("<H", self.data, pe + 20)[0]
        off = pe + 24 + optsz
        self.text = []  # every section named .text, in table order
        self.sections = {}
        for i in range(nsec):
            entry = self.data[off + i * 40 : off + (i + 1) * 40]
            name = entry[:8].rstrip(b"\0").decode("latin1")
            vsz, va, rsz, _raw = struct.unpack_from("<IIII", entry, 8)
            span = (va, max(vsz, rsz))
            self.sections.setdefault(name, span)
            if name == ".text":
                self.text.append(span)
        self._funcs = None

    def functions(self):
        """`.pdata` function extents as a sorted list of (begin_rva, end_rva)."""
        if self._funcs is None:
            va, size = self.sections[".pdata"]
            seen = {}
            for off in range(va, va + size, 12):
                begin, end, _unwind = struct.unpack_from("<III", self.data, off)
                if begin == 0 or end <= begin or end - begin > 0x20000:
                    continue
                seen.setdefault(begin, end)
            self._funcs = sorted(seen.items())
        return self._funcs

    def containing(self, rva):
        """(begin, end) of the `.pdata` function containing `rva`, or None."""
        funcs = self.functions()
        starts = [f[0] for f in funcs]
        i = bisect.bisect_right(starts, rva) - 1
        if i < 0:
            return None
        begin, end = funcs[i]
        return (begin, end) if rva < end else None


def parse_sig(sig):
    """IDA-style signature -> (bytes, mask). `?` and `??` are wildcards."""
    want, mask = [], []
    for token in sig.split():
        if token in ("?", "??"):
            want.append(0)
            mask.append(False)
        else:
            want.append(int(token, 16))
            mask.append(True)
    if not want:
        raise ValueError("empty signature")
    if not any(mask):
        raise ValueError("signature is entirely wildcards")
    return bytes(want), mask


def find_all(data, start, size, want, mask, cap=4096):
    """Every offset in [start, start+size) matching (want, mask), overlapping matches included."""
    n = len(want)
    anchor = next(i for i, keep in enumerate(mask) if keep)
    needle = bytes([want[anchor]])
    hits = []
    end = start + size
    cursor = start
    while len(hits) < cap:
        at = data.find(needle, cursor, end)
        if at < 0:
            break
        off = at - anchor
        cursor = at + 1
        if off < start or off + n > end:
            continue
        if all(not mask[j] or data[off + j] == want[j] for j in range(n)):
            hits.append(off)
    return hits


def cave_runs(data, start, size, needed):
    """How many runs of CAVE_FILL in [start, start+size) are long enough for `needed` bytes."""
    total = needed + CAVE_MARGIN * 2
    count = 0
    i = start
    end = start + size
    while i < end:
        if data[i] != CAVE_FILL:
            i += 1
            continue
        run = i
        while i < end and data[i] == CAVE_FILL:
            i += 1
        if i - run >= total:
            count += 1
    return count


# --- source extraction (the anti-drift half) --------------------------------------------------
_STRING = re.compile(r'"((?:[^"\\]|\\.)*)"')


def extract_literals(path, symbol):
    """Every string literal in the initialiser of `const`/`static` `symbol` in `path`."""
    src = path.read_text(encoding="utf-8", errors="replace")
    decl = re.search(
        r"(?:const|static)\s+" + re.escape(symbol) + r"\s*:", src
    )
    if not decl:
        raise KeyError(f"{path}: no const/static named {symbol}")
    # The initialiser runs to the first `;` at nesting depth 0 after the `=`.
    eq = src.index("=", decl.end())
    depth = 0
    i = eq
    while i < len(src):
        ch = src[i]
        if ch == '"':  # skip a string literal wholesale
            m = _STRING.match(src, i)
            i = m.end() if m else i + 1
            continue
        if ch in "[({":
            depth += 1
        elif ch in "])}":
            depth -= 1
        elif ch == ";" and depth == 0:
            break
        i += 1
    return [m.group(1) for m in _STRING.finditer(src[eq:i])]


def check_sync():
    """Every pinned pattern still matches the literal in its source file."""
    bad = 0
    print("== sync: pinned literals vs. the crates they live in ==")
    for entry in REGISTRY:
        path = ROOT / entry["source"]
        try:
            literals = extract_literals(path, entry["symbol"])
        except (KeyError, OSError, ValueError) as exc:
            print(f"  DRIFT {entry['id']}: {exc}")
            bad += 1
            continue
        for index in entry["literals"]:
            if index >= len(literals):
                print(
                    f"  DRIFT {entry['id']}: {entry['symbol']} has {len(literals)} literal(s), "
                    f"wanted index {index}"
                )
                bad += 1
                continue
            if literals[index] != entry["pattern"]:
                print(f"  DRIFT {entry['id']}: source says\n      {literals[index]}\n    pin says\n      {entry['pattern']}")
                bad += 1
            else:
                print(f"  ok    {entry['id']}  ({entry['symbol']}[{index}] in {entry['source']})")
    return bad


# --- classification ---------------------------------------------------------------------------
def classify(n_1162, n_1170):
    if n_1162 == 1 and n_1170 == 1:
        return "UNIQUE-BOTH"
    if n_1170 == 0:
        return "ZERO-ON-1170"
    if n_1162 == 1 and n_1170 > 1:
        return "MULTI-ON-1170"
    if n_1162 > 1 and n_1170 == n_1162:
        return "MULTI-BOTH-EQUAL"
    if n_1162 > 1:
        return "MULTI-BOTH-DIFFERENT"
    if n_1162 == 0:
        return "ZERO-ON-1162"
    return "UNCLASSIFIED"


def correspondence(images, hits):
    """Do the 1.16.2 and 1.17 hit lists describe the same sites?

    Each hit is reduced to its OFFSET INSIDE the `.pdata` function that contains it.  A function
    that moved without changing produces the identical offset; a hit that landed somewhere new
    does not.  The containing function's EXTENT is reported separately rather than folded into
    the identity, because a function can grow by a few bytes -- 1.17 added 8 bytes to
    `0x140af7cf0` -- while every hit inside it stays at the same offset.  Requiring equal extents
    reported that as five disagreements when nothing had moved.
    """
    reduced = {}
    for build in ("1162", "1170"):
        image = images[build]
        rows = []
        for hit in hits[build]:
            span = image.containing(hit)
            rows.append(None if span is None else (hit - span[0], span[1] - span[0]))
        reduced[build] = rows
    if len(reduced["1162"]) != len(reduced["1170"]):
        return "counts differ", reduced
    total = len(reduced["1162"])
    if total == 0:
        return "no hits to correspond", reduced
    pairs = list(zip(reduced["1162"], reduced["1170"]))
    same_off = sum(1 for a, b in pairs if a is not None and b is not None and a[0] == b[0])
    grew = sum(1 for a, b in pairs if a is not None and b is not None and a[1] != b[1])
    detail = f"{same_off}/{total} at the same offset inside their function"
    if grew:
        detail += f" ({grew} of those functions changed size)"
    return detail, reduced


def run_patterns(require_images):
    missing = [b for b, p in IMAGES.items() if not p.is_file()]
    if missing:
        line = ", ".join(f"{b} ({IMAGES[b]})" for b in missing)
        print(f"== patterns: SKIPPED -- missing image(s): {line}")
        return 1 if require_images else 0
    images = {b: Image(p) for b, p in IMAGES.items()}
    print("== patterns: literal AOB signatures over the runtime-scanned .text ==")
    for build, image in images.items():
        primary, tail = image.text[0], image.text[1] if len(image.text) > 1 else None
        note = (
            f"  tail .text {BASE + tail[0]:#x}+{tail[1]:#x} (Arxan; NOT scanned at runtime)"
            if tail
            else ""
        )
        print(f"  [{build}] runtime .text {BASE + primary[0]:#x}+{primary[1]:#x}{note}")
    bad = 0
    for entry in REGISTRY:
        want, mask = parse_sig(entry["pattern"])
        hits = {}
        for build, image in images.items():
            start, size = image.text[0]
            hits[build] = find_all(image.data, start, size, want, mask)
        n = {b: len(v) for b, v in hits.items()}
        verdict = classify(n["1162"], n["1170"])
        pinned = entry["expect"]
        drift = n["1162"] != pinned["1162"] or n["1170"] != pinned["1170"]
        corr, _ = correspondence(images, hits)
        print(f"\n  {entry['id']}  [{entry['consumer']}]  {len(want)} bytes")
        print(f"    1.16.2 hits={n['1162']:<5d} 1.17 hits={n['1170']:<5d} -> {verdict}")
        print(f"    correspondence: {corr}")
        show = ", ".join(hex(BASE + h) for h in hits["1170"][:4])
        print(f"    1.17 first hits: {show or '(none)'}")
        print(f"    {entry['note']}")
        if drift:
            print(
                f"    REGRESSION: pinned {pinned['1162']}/{pinned['1170']}, "
                f"measured {n['1162']}/{n['1170']}"
            )
            bad += 1
        if verdict in ("MULTI-ON-1170", "MULTI-BOTH-DIFFERENT"):
            bad += 1
        if verdict == "ZERO-ON-1170" and entry["consumer"] != "unique-or-refuse":
            bad += 1
    print("\n== structural scans (no 1.16.2-derived signature) ==")
    for label, needed in CAVE_NEEDS:
        counts = {
            b: cave_runs(img.data, img.text[0][0], img.text[0][1], needed)
            for b, img in images.items()
        }
        ok = counts["1170"] > 0
        print(
            f"  ersc-sigshim cave for {label} ({needed} bytes): "
            f"1.16.2 runs={counts['1162']}  1.17 runs={counts['1170']}  "
            f"{'available' if ok else 'NONE LEFT'}"
        )
        if not ok:
            bad += 1
    return bad


# --- needle audit -----------------------------------------------------------------------------
_TABLES = None


def translation_tables():
    """`(call, detour)` -- the two maps `er-game-base/build.rs` emits, as `{rva: rva}`.

    THE LEDGER IS FOUR FILES, NOT TWO.  `emit_address_map` reads `VERIFIED_MAP`,
    `NEEDED_VERIFIED_MAP`, `FUNCTION_MAP` and `DATA_MAP`, applies a verdict/instruction-count/
    entry-evidence admission rule to the two verdict tables, and subtracts a quarantine and every
    `DIVERGES` row.  This function used to read two of those four files raw, and the cost was not
    a rounding error: 36 of its 37 `NO-ROW` verdicts were wrong.  `NO-ROW` reads as "safe --
    `er-hook` refuses the address before any byte check runs", so 36 pins whose hook DOES install
    on 1.17 were reported as inert, and one of them (`WorldMapAreaConverter::
    ConvertMsbCoordsToMapCoords`) actually DISARMS on 1.17.  A real finding, in a green gate,
    reported as nothing.  Measured 2026-08-30.

    The rules are not copied here.  `check-1170-translation-collisions.py` parses them out of
    `build.rs` itself, and its output was confirmed byte-identical to the `address_map_1170.rs`
    cargo generated (476 CALL rows, 372 DETOUR rows).  If `build.rs` moves in a way that gate
    cannot parse it raises `Refuse`, and that propagates rather than falling back to the partial
    read -- a partial read is the failure this replaced.
    """
    global _TABLES
    if _TABLES is None:
        tables = _COLLISIONS.emit(_COLLISIONS.build_rules())
        _TABLES = (
            {row.src: row.dst for row in tables[_COLLISIONS.CALL]},
            {row.src: row.dst for row in tables[_COLLISIONS.DETOUR]},
        )
    return _TABLES


def ledger_rvas():
    """Every 1.16.2 RVA the shipped CALL map translates. See `translation_tables`."""
    return translation_tables()[0]


def detour_rvas():
    """The subset carrying detour evidence too. A CALL-only row cannot carry a hook."""
    return translation_tables()[1]


def run_needles():
    mapped = ledger_rvas()
    print("== needles: scans whose pattern is BUILT AT RUNTIME from an RVA constant ==")
    print("   game_data_addr() answers 0 for an unmapped RVA. A zero DEREFERENCE faults closed;")
    print("   a zero SCAN NEEDLE matches every zeroed qword in the address space.")
    bad = 0
    for scan in NEEDLE_SCANS:
        path = ROOT / scan["source"]
        src = path.read_text(encoding="utf-8", errors="replace") if path.is_file() else ""
        guarded = bool(re.search(scan["guard"], src))
        print(f"\n  {scan['id']}")
        print(f"    {scan['source']}")
        unmapped = []
        for name, rva in scan["needles"]:
            dst = mapped.get(rva)
            state = f"-> {dst:#x}" if dst is not None else "NO 1.17 ROW"
            if dst is None:
                unmapped.append(name)
            print(f"    needle {name} = {rva:#x}  {state}")
        print(f"    zero-needle guard in source: {'PRESENT' if guarded else 'ABSENT'}")
        print(f"    result feeds: {scan['consumes']}")
        if guarded != scan["guarded"]:
            print(
                f"    DRIFT: pinned guard={'present' if scan['guarded'] else 'absent'}, "
                f"source says {'present' if guarded else 'absent'}"
            )
            bad += 1
        if unmapped and not guarded:
            print(
                f"    LIVE HAZARD: {', '.join(unmapped)} has no 1.17 mapping AND nothing rejects a "
                "zero needle -- this scan will return a pointer into zeroed memory."
            )
            bad += 1
        elif not guarded:
            print(
                "    LATENT: every needle maps today, so the scan works; it is one removed ledger "
                "row away from returning a pointer into zeroed memory."
            )
    return bad


# --- prologue-gate audit ----------------------------------------------------------------------
# `build-support/prologue_build.rs` generates one byte constant per detour target, pinned to the
# bytes 1.16.2 has at that VA.  At runtime the crate re-reads the live bytes and DISARMS on a
# mismatch.  That is fail-closed and correct -- but a prologue containing a RIP-relative
# displacement changes whenever the function OR the global it points at moves, so on 1.17 the
# gate can disarm a hook whose address translated perfectly.  This section says which.
_FIELD = {
    "name": re.compile(r'name:\s*"([A-Za-z0-9_]+)"'),
    "image": re.compile(r"image:\s*Image::(\w+)"),
    "va": re.compile(r"va:\s*([A-Za-z0-9_]+)\s*,"),
    # Either an inline `&[0x.., ..]` or the NAME of a `const .._PIN: &[u8]` in the same build.rs.
    # Both spellings are in the tree, and only the first used to be read: `ERSC_OPTION_ACTION_PIN`
    # and `VALIDATOR_PIN` are shared by two specs each, so four of the 42 `PrologueSpec`s were
    # dropped by the parser and never appeared in the report at all -- not as SKIP, not in the
    # totals, not anywhere. `prologue_spec_gaps()` is what makes that impossible to repeat.
    "pin": re.compile(r"pin:\s*(&\[.*?\]|[A-Z][A-Z0-9_]*)\s*,", re.DOTALL),
}
_HEXBYTE = re.compile(r"0x([0-9A-Fa-f]{1,2})")


def _spec_bodies(src):
    """Every `PrologueSpec { .. }` body, brace-matched.

    A non-greedy `\\{(.*?)\\}\\s*,` stops at the first `}` followed by a comma, so one nested
    struct literal inside a spec would truncate the body, drop the fields after it, and silently
    lose the spec. Counting braces cannot do that, and the count it yields is what
    `prologue_spec_gaps()` compares against.
    """
    bodies = []
    for match in re.finditer(r"PrologueSpec\s*\{", src):
        start = src.index("{", match.start())
        depth = 0
        for index in range(start, len(src)):
            if src[index] == "{":
                depth += 1
            elif src[index] == "}":
                depth -= 1
                if depth == 0:
                    bodies.append(src[start + 1 : index])
                    break
        else:
            bodies.append(src[start + 1 :])  # unbalanced source; the gap check will catch it
    return bodies


def _build_scripts():
    return [
        path
        for path in sorted((ROOT / "crates").glob("*/build.rs"))
        if "PrologueSpec" in path.read_text(encoding="utf-8", errors="replace")
    ]


def _parse_spec(body, crate, consts, pins):
    fields = {}
    for key, rx in _FIELD.items():
        found = rx.search(body)
        if not found:
            return None
        fields[key] = found.group(1)
    literal = fields["pin"]
    if literal.startswith("&["):
        pin = bytes(int(b, 16) for b in _HEXBYTE.findall(literal))
    else:
        if literal not in pins:
            return None
        pin = pins[literal]
    return (crate, fields["name"], fields["image"], consts.get(fields["va"]), fields["va"], pin)


def prologue_specs():
    """(crate, name, image, va, va_symbol, pin_bytes) for every PrologueSpec in the workspace."""
    out = []
    for build in _build_scripts():
        src = build.read_text(encoding="utf-8", errors="replace")
        consts = {
            m.group(1): int(m.group(2), 16)
            for m in re.finditer(r"const\s+([A-Z0-9_]+):\s*u64\s*=\s*(0x[0-9a-fA-F_]+)", src)
        }
        pins = {
            m.group(1): bytes(int(b, 16) for b in _HEXBYTE.findall(m.group(2)))
            for m in re.finditer(
                r"(?:const|static)\s+([A-Z][A-Z0-9_]*):\s*&\[u8\]\s*=\s*&\[(.*?)\]\s*;",
                src,
                re.DOTALL,
            )
        }
        for body in _spec_bodies(src):
            parsed = _parse_spec(body, build.parent.name, consts, pins)
            if parsed is not None:
                out.append(parsed)
    return out


def prologue_spec_gaps():
    """`[(crate, name_or_'<unnamed>')]` for every declared PrologueSpec this parser could not read.

    A spec the parser drops produces NO row and NO tally entry, so the report is short by one and
    says nothing about it. That is strictly worse than a SKIP, and it is what the four
    named-constant pins did for as long as this section has existed. Any gap is a hard failure:
    an audit that cannot enumerate its own subjects is not an audit.
    """
    gaps = []
    for build in _build_scripts():
        src = build.read_text(encoding="utf-8", errors="replace")
        consts = {
            m.group(1): int(m.group(2), 16)
            for m in re.finditer(r"const\s+([A-Z0-9_]+):\s*u64\s*=\s*(0x[0-9a-fA-F_]+)", src)
        }
        pins = {
            m.group(1): bytes(int(b, 16) for b in _HEXBYTE.findall(m.group(2)))
            for m in re.finditer(
                r"(?:const|static)\s+([A-Z][A-Z0-9_]*):\s*&\[u8\]\s*=\s*&\[(.*?)\]\s*;",
                src,
                re.DOTALL,
            )
        }
        for body in _spec_bodies(src):
            if _parse_spec(body, build.parent.name, consts, pins) is not None:
                continue
            named = _FIELD["name"].search(body)
            gaps.append((build.parent.name, named.group(1) if named else "<unnamed>"))
    return gaps


def declared_image_variants(path=GENERATOR):
    """Every variant of `enum Image` the prologue generator declares."""
    src = path.read_text(encoding="utf-8", errors="replace")
    match = re.search(r"enum Image \{(.*?)\n\}", src, re.DOTALL)
    if not match:
        raise SystemExit(f"{path}: could not find `enum Image` -- the generator's shape moved")
    body = re.sub(r"///[^\n]*", "", match.group(1))
    return [name for name in re.findall(r"^\s*([A-Z][A-Za-z0-9_]*)\s*,", body, re.MULTILINE)]


def unmodelled_image_variants():
    """Variants the generator declares that `IMAGE_ROLE` does not describe."""
    return [name for name in declared_image_variants() if name not in IMAGE_ROLE]



def diff_shape(pin, differ):
    """Describe WHY a prologue stopped matching, as far as bytes alone can say.

    The distinction that matters: a prologue whose only drift is inside a 4-byte operand field is
    a hook that lost its gate to a RELOCATION, not to a changed function.  `mov rax,[rip+disp32]`
    re-encodes whenever either the instruction or the global it names moves, and 1.17 moved both,
    so the gate disarms a hook whose ADDRESS translated perfectly.  Re-pinning that one operand
    from the 1.17 image restores the feature; a scattered or wide diff means the body changed and
    the function has to be read before anything is re-pinned.

    This is a heuristic on bytes, not a disassembly, and it says so in the label it returns.
    """
    if not differ:
        return "no difference"
    contiguous = differ == list(range(differ[0], differ[-1] + 1))
    span = differ[-1] - differ[0] + 1
    if contiguous and span <= 4:
        # A rel32/disp32 field is 4 bytes and its high byte often survives a small move, so the
        # observed run is <= 4 rather than exactly 4.
        for field in range(max(0, differ[-1] - 3), differ[0] + 1):
            if field + 4 <= len(pin) and differ[0] >= field and differ[-1] < field + 4:
                return (
                    f"contiguous, inside the 4-byte field at +{field} -- consistent with a "
                    "rel32/disp32 relocation, NOT a changed instruction (byte heuristic)"
                )
    return "contiguous" if contiguous else "scattered -- the body changed"


_SEAM = re.compile(
    r'name:\s*"(?P<name>[^"]+)"\s*,\s*rva:\s*(?P<rva>0x[0-9a-fA-F_]+)\s*,\s*'
    r"prologue:\s*&\[(?P<pin>.*?)\]",
    re.DOTALL,
)


def seam_specs():
    """(crate, name, image, va, va_symbol, pin) for the hand-written `MapSeam` prologue table.

    `er-invasion-warp`'s map seams predate `prologue_build.rs` and carry their expected bytes
    inline beside an RVA.  They are checked by `verify_seam` at exactly the same moment and with
    exactly the same fail-closed consequence as a generated prologue, so leaving them out of this
    audit would report the crate as clean while thirteen of its hooks silently disarmed.
    """
    path = ROOT / "crates/er-invasion-warp/src/map_seams.rs"
    if not path.is_file():
        return []
    src = path.read_text(encoding="utf-8", errors="replace")
    out = []
    for match in _SEAM.finditer(src):
        rva = int(match.group("rva").replace("_", ""), 16)
        pin = bytes(int(b, 16) for b in _HEXBYTE.findall(match.group("pin")))
        out.append(
            ("er-invasion-warp (map_seams)", match.group("name"), "EldenRing", BASE + rva, "inline", pin)
        )
    return out


VERDICTS = ("ARMS", "DISARMS", "NO-ROW", "SKIP", "BAD-PIN", "UNKNOWN-IMAGE")


def classify_prologue(spec, images, mapped, detour):
    """`(verdict, detail)` for one spec. The ONE place an `Image` variant is dispatched.

    `images` is `{"1162": obj, "1170": obj}` where each object has `.data`; the selftest passes
    synthetic ones, so every branch below is reachable without the game files.
    """
    _crate, _name, image_kind, va, va_sym, pin = spec
    role = IMAGE_ROLE.get(image_kind, _UNMODELLED)
    if role is _UNMODELLED:
        # NOT a skip. A variant nobody taught this script about is a pin nobody is checking, and
        # the previous spelling of this branch turned exactly that into three silent SKIPs.
        return "UNKNOWN-IMAGE", (
            f"`Image::{image_kind}` is not in IMAGE_ROLE -- teach this script the variant "
            "instead of letting its pins go unchecked"
        )
    if role is None:
        return "SKIP", f"{image_kind} module, which this script does not load"
    if va is None:
        return "SKIP", f"could not resolve {va_sym}"
    rva = va - BASE
    if role == "1170":
        # The spec pins 1.17 bytes at a 1.17 VA. No ledger hop: compare in place. There is no
        # DISARMS branch here -- if these bytes do not match, the pin is wrong about its own
        # declared ground truth, which is the BAD-PIN defect, and the hook disarms as well.
        after = images["1170"].data[rva : rva + len(pin)]
        if len(after) != len(pin):
            return "SKIP", f"{va:#x} is past the end of the 1.17 image"
        if after == pin:
            return "ARMS", f"{va:#x} (pinned to 1.17 directly; no ledger hop)"
        differ = [i for i in range(len(pin)) if pin[i] != after[i]]
        return "BAD-PIN", (
            f"{va:#x} claims 1.17 bytes and the 1.17 image holds {after.hex()}, not {pin.hex()} "
            f"(byte(s) {differ}); the gate will disarm"
        )
    have = images["1162"].data[rva : rva + len(pin)]
    if have != pin:
        return "BAD-PIN", f"{va:#x} holds {have.hex()} but the pin is {pin.hex()}"
    dst = mapped.get(rva)
    if dst is None:
        return "NO-ROW", f"{va:#x} has no 1.17 row"
    after = images["1170"].data[dst : dst + len(pin)]
    if len(after) != len(pin):
        return "SKIP", f"1.17 row {BASE + dst:#x} is past the end of the image"
    # A row in the CALL map but not the DETOUR map translates for a call and is refused for a
    # hook, so the byte verdict below is real but a detour never gets that far.
    route = "" if rva in detour else "  [CALL-only row: a detour here is refused first]"
    if after == pin:
        return "ARMS", f"{va:#x} -> {BASE + dst:#x}{route}"
    differ = [i for i in range(len(pin)) if pin[i] != after[i]]
    return "DISARMS", (
        f"{va:#x} -> {BASE + dst:#x}{route}: byte(s) {differ} differ "
        f"({diff_shape(pin, differ)}); want {pin.hex()} got {after.hex()}"
    )


def run_prologues(require_images):
    bad = 0
    unmodelled = unmodelled_image_variants()
    if unmodelled:
        print(
            "== prologues: the generator declares `Image` variant(s) this script does not model: "
            + ", ".join(unmodelled)
        )
        bad += len(unmodelled)
    gaps = prologue_spec_gaps()
    for crate, name in gaps:
        print(f"== prologues: UNPARSED PrologueSpec {crate}/{name} -- it has no verdict at all")
    bad += len(gaps)
    missing = [b for b, p in IMAGES.items() if not p.is_file()]
    if missing:
        line = ", ".join(f"{b} ({IMAGES[b]})" for b in missing)
        print(f"== prologues: SKIPPED -- missing image(s): {line}")
        return bad + (1 if require_images else 0)
    images = {b: Image(p) for b, p in IMAGES.items()}
    mapped = ledger_rvas()
    detour = detour_rvas()
    specs = prologue_specs() + seam_specs()
    print("== prologues: 1.16.2 byte gates re-checked at their 1.17 addresses ==")
    print("   ARMS      the gate passes on 1.17 and the hook installs.")
    print("   DISARMS   the address maps but the bytes differ -- fail-closed, feature lost.")
    print("   NO-ROW    no 1.17 mapping, so `er-hook` refuses before the byte check runs.")
    tally = dict.fromkeys(VERDICTS, 0)
    rows = []
    for spec in specs:
        verdict, detail = classify_prologue(spec, images, mapped, detour)
        tally[verdict] += 1
        rows.append((spec[0], spec[1], verdict, detail))
    width = max((len(r[1]) for r in rows), default=0)
    last_crate = None
    for crate, name, verdict, detail in rows:
        if crate != last_crate:
            print(f"\n  {crate}")
            last_crate = crate
        print(f"    {verdict:<13s} {name:<{width}s}  {detail}")
    print(
        "\n  totals: "
        + "  ".join(f"{k}={v}" for k, v in tally.items())
        + f"  (of {len(specs)} specs)"
    )
    # A DISARMS is fail-closed, so it is reported, not failed.  A BAD-PIN means this script and
    # the build script disagree about the image the spec names, which is a defect in one of them.
    # An UNKNOWN-IMAGE means this script does not know what it is looking at.
    return bad + tally["BAD-PIN"] + tally["UNKNOWN-IMAGE"]


# --- selftest ---------------------------------------------------------------------------------
def selftest():
    failures = []

    def check(label, got, want):
        if got != want:
            failures.append(f"{label}: got {got!r}, wanted {want!r}")

    want, mask = parse_sig("48 ?? 8B ?")
    check("parse_sig bytes", want, bytes([0x48, 0, 0x8B, 0]))
    check("parse_sig mask", mask, [True, False, True, False])
    for bad_sig in ("", "?? ??"):
        try:
            parse_sig(bad_sig)
            failures.append(f"parse_sig({bad_sig!r}) should have raised")
        except ValueError:
            pass

    # A wildcard-leading signature must still anchor on a concrete byte.
    data = bytes.fromhex("00" * 4 + "AA48BB" + "00" * 4 + "CC48DD" + "00" * 4)
    want, mask = parse_sig("?? 48 ??")
    check("anchor past a leading wildcard", find_all(data, 0, len(data), want, mask), [4, 11])

    # Overlapping matches are all reported -- a scanner that skipped them would under-count and
    # a "unique" verdict would be wrong.
    data = b"\xaa\xaa\xaa\xaa"
    want, mask = parse_sig("AA AA")
    check("overlapping matches", find_all(data, 0, len(data), want, mask), [0, 1, 2])

    # A match must not straddle the end of the scanned range.
    data = b"\x00\x11\x22\x33"
    want, mask = parse_sig("33 44")
    check("no match past the range end", find_all(data, 0, len(data), want, mask), [])
    # ...nor start before it.
    data = b"\x11\x22\x33\x44"
    want, mask = parse_sig("11 22")
    check("range start respected", find_all(data, 2, 2, want, mask), [])

    # Ledger normalisation: both column formats must reduce to RVAs.
    ledger = ledger_rvas()
    if ledger:
        stray = [k for k in ledger if k >= BASE] + [v for v in ledger.values() if v >= BASE]
        if stray:
            failures.append(f"ledger_rvas() left {len(stray)} VA(s) unnormalised, e.g. {stray[0]:#x}")
        oversize = [v for v in ledger.values() if v > 0x0800_0000]
        if oversize:
            failures.append(
                f"ledger_rvas() produced an RVA past any plausible image size: {oversize[0]:#x}"
            )

    check("classify unique", classify(1, 1), "UNIQUE-BOTH")
    check("classify zero", classify(1, 0), "ZERO-ON-1170")
    check("classify multi", classify(1, 3), "MULTI-ON-1170")
    check("classify shotgun stable", classify(181, 181), "MULTI-BOTH-EQUAL")
    check("classify shotgun drifted", classify(181, 174), "MULTI-BOTH-DIFFERENT")
    check("classify already fragile", classify(0, 1), "ZERO-ON-1162")

    # Cave runs: 0xCC padding long enough for `needed` + a margin at each end.
    data = b"\x90" + b"\xcc" * 6 + b"\x90" + b"\xcc" * 3 + b"\x90"
    check("cave run counted", cave_runs(data, 0, len(data), 4), 1)
    check("cave run too short", cave_runs(data, 0, len(data), 5), 0)

    # Source extraction handles a multi-line const and a table of tuples.
    sample = ROOT / "target" / "verify-aob-selftest.rs"
    sample.parent.mkdir(parents=True, exist_ok=True)
    sample.write_text(
        'const OTHER: &str = "not me";\n'
        "const SIG: &str =\n"
        '    "40 53 48";\n'
        "static TABLE: &[(&str, &str)] = &[\n"
        '    ("7A ?? 75", "?? 02"),\n'
        '    ("0F 8A ??", "?? ?? 06"),\n'
        "];\n",
        encoding="utf-8",
    )
    try:
        check("extract single literal", extract_literals(sample, "SIG"), ["40 53 48"])
        check(
            "extract table literals",
            extract_literals(sample, "TABLE"),
            ["7A ?? 75", "?? 02", "0F 8A ??", "?? ?? 06"],
        )
        try:
            extract_literals(sample, "NOPE")
            failures.append("extract_literals(NOPE) should have raised")
        except KeyError:
            pass
    finally:
        sample.unlink(missing_ok=True)

    # Every registry pattern parses, and every registry source file exists.
    for entry in REGISTRY:
        try:
            parse_sig(entry["pattern"])
        except ValueError as exc:
            failures.append(f"{entry['id']}: {exc}")
        if not (ROOT / entry["source"]).is_file():
            failures.append(f"{entry['id']}: missing source {entry['source']}")
    for scan in NEEDLE_SCANS:
        if not (ROOT / scan["source"]).is_file():
            failures.append(f"{scan['id']}: missing source {scan['source']}")
        re.compile(scan["guard"])

    # The PrologueSpec parser must resolve a symbolic `va` and decode the pin, or the whole
    # prologue section silently reports nothing.
    specs = prologue_specs() + seam_specs()
    if not specs:
        failures.append("prologue_specs() found no PrologueSpec in crates/*/build.rs")
    unresolved = [f"{c}/{n}" for c, n, _i, va, sym, _p in specs if va is None]
    if unresolved:
        failures.append(f"prologue_specs() could not resolve va for: {', '.join(unresolved)}")
    empty = [f"{c}/{n}" for c, n, _i, _v, _s, pin in specs if not pin]
    if empty:
        failures.append(f"prologue_specs() decoded an empty pin for: {', '.join(empty)}")
    seams = seam_specs()
    if not seams:
        failures.append("seam_specs() found no MapSeam prologue in er-invasion-warp/map_seams.rs")
    if any(not pin for _c, _n, _i, _v, _s, pin in seams):
        failures.append("seam_specs() decoded an empty pin")

    check(
        "diff_shape rel32",
        "rel32/disp32" in diff_shape(bytes(8), [3, 4, 5]),
        True,
    )
    check("diff_shape body change", diff_shape(bytes(16), [1, 9]), "scattered -- the body changed")
    check("diff_shape none", diff_shape(bytes(4), []), "no difference")

    for line in failures:
        print(f"  FAIL {line}")
    print(f"selftest: {'FAILED' if failures else 'ok'} ({len(failures)} failure(s))")
    return 1 if failures else 0


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--section",
        choices=("all", "patterns", "needles", "prologues", "sync"),
        default="all",
    )
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument(
        "--require-images",
        action="store_true",
        help="fail instead of skipping when a deobfuscated image is missing",
    )
    args = ap.parse_args()
    if args.selftest:
        return selftest()
    bad = 0
    if args.section in ("all", "sync"):
        bad += check_sync()
        print()
    if args.section in ("all", "patterns"):
        bad += run_patterns(args.require_images)
        print()
    if args.section in ("all", "needles"):
        bad += run_needles()
        print()
    if args.section in ("all", "prologues"):
        bad += run_prologues(args.require_images)
        print()
    print(f"verdict: {'FAILED' if bad else 'ok'} ({bad} problem(s))")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
