[package]
name = "er-death-persist-dll"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "er_death_persist"
crate-type = ["cdylib"]

[target.'cfg(windows)'.dependencies]
er-game-base = { path = "../er-game-base" }
eldenring = { path = "../../../fromsoftware-rs/crates/eldenring" }
fromsoftware-shared = { path = "../../../fromsoftware-rs/crates/shared" }

[lints]
workspace = true
